### ISSUE TITLE
DTLA - September 6th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#10]
# DTLA
### lunch.js - downtown tacos.js edition: 
- Guuisados (gee SA dos - not goo-ey-sados)
- 541 S. Spring St. # 101
- Tues. Sep. 6th
- 🚇   Red Line / 7th St Metro Center Station (Avoid Pershing Square Station if you can)
- http://www.guisados.co/contact/

Championed By: Machiko @machikoyasuda

**Comment by ashwell** [comment]
@machikoyasuda you kinda took the lead last month so I made you the champion of the DTLA Lunch.js group.

We still need to write up what the champion is/does but basically you'd organize the location.

**Comment by machikoyasuda** [comment]
I added a 12:30 lunch appointment to my Google Calendar, so I'll be there / do that :) let's lunch & chat about js, downtown-working js-writing pals: - @kit_pearson, @cacheflow, @learningnerd, @ezraez, @matikin9, @jdorfman, @jschleuss, @lenkli67, @anderjason, @brancusi, @kennethlee, @sannsann, @joemeneses, @courdek, @jackieb500, @Gio-aguirre19, @eirinikos.

**Comment by machikoyasuda** [comment]
### lunch.js - downtown tacos.js edition: 
- Guuisados (gee SA dos - not goo-ey-sados)
- 541 S. Spring St. # 101
- Tues. Sep. 6th
- 🚇   Red Line / 7th St Metro Center Station (Avoid Pershing Square Station if you can)
- http://www.guisados.co/contact/

**Comment by jdorfman** [comment]
lol this is my building. I will be there.

**Comment by kennethlee** [comment]
I'm down

**Comment by matikin9** [comment]
Sweet! see you guys there!

**Comment by iwilliams** [comment]
Pxlbros will be there. Looks like we are going to shut Guisados down!

**Comment by machikoyasuda** [comment]
js.la guisados take over :) maybe weho jsla people could go to guisados in weho too, and javascript will basically just be fueling the los angeles taco economy.

**Comment by LearningNerd** [comment]
I'm in! Thanks for the invite @machikoyasuda this is a fun idea! :)

**Comment by lenkli67** [comment]
I'll be there!

**Comment by ashwell** [comment]
you hear that @davidguttman? @LearningNerd thinks this is a fun idea! :+1:

**Comment by itsjustmath** [comment]
You can't go wrong with Guisados. I highly recommend you guys try the [Horchata x Stumptown cold brew](https://www.yelp.com/biz_photos/guisados-dtla-los-angeles-2?select=qLPA0hjcXEhKjSN_KHB53w)

**Comment by ezRAez** [comment]
Might be a lil late, but I'll be there!

**Comment by machikoyasuda** [comment]
Oops. I'm gonna be in Japan this day. Who can hold down this taco event instead? I'll invite people and y'all can Skype me in :D

**Comment by matikin9** [comment]
@machikoyasuda I can!  my work is just a few blocks away so it's easy for me to get to

**Comment by jimthoburn** [comment]
@machikoyasuda, I’d love to join in as well!

**Comment by ZLester** [comment]
I'll be there!

**Comment by eirinikos** [comment]
See you guys tomorrow! @machikoyasuda Just curious, what's wrong with Pershing Square station? It's a 4-minute walk away, whereas 7th St is a 12-minute walk.

**Comment by machikoyasuda** [comment]
Andrea, Pershing Sq station is under heavy construction and is smellier. It's not terrible. 7th St is just cleaner and less smelly. 






On Tue, Sep 6, 2016 at 2:22 PM +0900, "Andrea Kao" <notifications@github.com> wrote:












See you guys tomorrow! @machikoyasuda Just curious, what's wrong with Pershing Square station? It's a 4-minute walk away, whereas 7th St is a 12-minute walk.

**Comment by ezRAez** [comment]
Ah man @machikoyasuda  - I can't make it after all. Ended up getting pulled into a meeting for lunch. Hope to make it to the next one!!!

**Comment by matikin9** [comment]
@LearningNerd in addition to Il Caffe, there's another coffee shop you should check out - Cognoscenti!  it's a brand new spot near south park

**Comment by ashwell** [comment]
I hope everyone enjoyed the tacos!

**Comment by ashwell** [comment]
DTLA lunch.js October is posted! https://github.com/jsla/lunch.js/issues/17
