### ISSUE TITLE
Calling All Champions - January 2nd, 2018

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#100]
## Hey lunch.js Champions!

The next first Tuesday of the month is January 2nd, 2018
Please create new issues when you get the chance.

## Lunch Locations
Los Feliz / West Hollywood - #103 
Culver City
Playa Vista
Santa Monica 
Sherman Oaks - #104 
Thousand Oaks - #101 
Burbank
DTLA
South Bay
Valencia / Santa Clarita - #102 
Long Beach

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js comment here to get started!

cc previous champions:
@anguspiv, @fhwrdh, @bradstemke, @rouzbeh84, @mnicole,  @enminc, @meganmcgeee

**Comment by ashwell** [comment]
@jcblw, @mnicole would either of you like to champion SM for next week?

**Comment by mnicole** [comment]
@ashwell sorry, i'm not going to be around tues, but i can next month!

**Comment by ashwell** [comment]
I hope all the events went well today, next month lunch.js will be on the 6th.

[Comment here #107](https://github.com/jsla/lunch.js/issues/107) if you need help finding another / new champion.
