### ISSUE TITLE
Thousand Oaks - Jan 2nd, 2018

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#101]
# Thousand Oaks
### @ [Brent's Deli](https://www.yelp.com/biz/brents-delicatessen-and-restaurant-westlake-village?osq=lunch)

Championed By: Franklin H @fhwrdh

Happy New Year everyone! Let's pick a place for lunch. I've added a couple of ideas, but always open to other suggestions.

**Comment by cdransf** [comment]
Is this still on, or did it get moved?

**Comment by fhwrdh** [comment]
HI @cdransf, I am sick at the moment and will not personally make it tomorrow. However, some of the other CJ folks should be there. I will update the location based on the voting.

**Comment by Zhuochengyu** [comment]
@cdransf I am going to be there tomorrow.

**Comment by Zhuochengyu** [comment]
I am going to head over to Brent's Deli now. I am wearing a blue sweater today if you want to look for me.

**Comment by Zhuochengyu** [comment]
I am sitting outside of the entrance. I will get a small table at 12:30.

**Comment by Zhuochengyu** [comment]
Its great seeing you all. Let's meet again next month!

**Comment by fhwrdh** [comment]
Thanks @Zhuochengyu for hosting in my absence.

**Comment by cdransf** [comment]
Cya guys next month!
