### ISSUE TITLE
Valencia / Santa Clarita - Tuesday, January 2nd, 2018

### ISSUE THREAD

**Issue by enminc** [jsla/lunch.js#102]
# Valencia / Santa Clarita
### @ Iconic Eats (prev known as: BlaqSquare)

Happy New Year everyone. I would really like to hear from anyone my area, even if you can't make the lunch it would be great to connect. 

Championed By: Adam Smith @enminc

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
@enminc I hope someday you get some takers!
