### ISSUE TITLE
Los Feliz - January 2nd, 2018

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#103]
# Los Feliz
### @ Spitz on Hillhurst

1725 Hillhurst Ave
Los Angeles, CA 90027
[yelp page](http://yelp.com/biz/spitz-los-feliz-los-angeles-2)

Championed By: @billbitt && @laras126
I will be out of town for the holidays, so looking for someone to help champion this specific lunch.

If you are planning to attend subscribe to the issue to get notifications for new comments.

Please RSVP on this issue with an emoji:
:+1: == yes, I am planning to attend!

**Comment by billbitt** [comment]
Given the holidays, we have some people out of town.  Please leave an 'rsvp' with the +1 emoji if you are able and planning to attend, so that we can get an idea of numbers for this month.
:+1: == yes, I am planning to attend!

**Comment by laras126** [comment]
I'm assuming champion duties for tomorrow – let's meet at Spitz on Hillhurst: https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2

**Comment by ashwell** [comment]
Thanks for picking this up @laras126! I hope it was a good lunch!
