### ISSUE TITLE
CANCELLED - Sherman Oaks - Tuesday, January 2nd, 2018

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#104]
# Sherman Oaks
### @ [Garden Cafe](https://www.yelp.com/biz/garden-cafe-sherman-oaks)

Hey Everyone, since I was a little late to party on this I'll choose the venue this time. That said I'm hoping to see you all soon! (If someone has a much better suggestion let me know)

Championed By: Angus Perkerson @anguspiv

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by sheelah** [comment]
Argh bummer... Not going to be able to make this one. Next time!

**Comment by anguspiv** [comment]
Soooo anyone coming? Otherwise I'll cancel by 10

**Comment by anguspiv** [comment]
Since No One is attending, besides me I will cancel the event
