### ISSUE TITLE
Playa Vista - February 6th, 2018

### ISSUE THREAD

**Issue by aaroncraigongithub** [jsla/lunch.js#109]
# Playa Vista
### @ The lunch trucks off of Bluff Creek Dr in the Hercules East campus (or suggest a place!)
https://www.google.com/maps/@33.9825884,-118.4034461,18.58z

Championed By: Aaron Craig @aaroncraigongithub

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by leggomuhgreggo** [comment]
Still planning to join! Hope others will be able to make it too

**Comment by ashwell** [comment]
I hope lunch went well! I'm going to go ahead and close this for now but feel free to get the next ticket setup when you have the time.
