### ISSUE TITLE
Santa Monica - September 6th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#11]
# Santa Monica
### Lunch Poll! (Has Concluded)
👍  ~~Wokano - Sushi - (Santa Monica & 5th)~~
:heart: Misfit - American - (Santa Monica & 2nd)
:tada: ~~Sweetfin Poké - Hawaiian (Lincoln & Broadway)~~

Championed By: Nate @etanlubeck

**Comment by machikoyasuda** [comment]
@christinejavier @gr2m

**Comment by gr2m** [comment]
I’m in 👋

**Comment by ashwell** [comment]
![](https://media.giphy.com/media/zaezT79s3Ng7C/giphy.gif)

**Comment by mobianboy** [comment]
I'm in

**Comment by jjkeith** [comment]
Looking forward to it.

**Comment by etanlubeck** [comment]
@jjkeith @mobianboy cast your vote up top, please!

**Comment by mobianboy** [comment]
@etanlubeck Done

**Comment by jjkeith** [comment]
@etanlubeck done!

**Comment by ashwell** [comment]
My car got a flat and I'm getting it fixed tomorrow so I have to miss lunch.js again :(

**Comment by mobianboy** [comment]
Sorry, but I will have to miss this one. I threw my back out and am now confined to laying at home until it heals. Hope you guys have a good one and I'll see you at the next one.

**Comment by gr2m** [comment]
Looking forward to meet you all tomorrow :wave:

**Comment by etanlubeck** [comment]
looking forward to meeting you all. bummer @ashwell

**Comment by dqingram** [comment]
Is it too late to crash the party? I'm coming anyways.

**Comment by etanlubeck** [comment]
never too late. here's my number just in case: 8189614222

**Comment by etanlubeck** [comment]
Good meeting and chopping it up with @dqingram, @gr2m Catch you all next month!

**Comment by ashwell** [comment]
October is up, suggest a place! https://github.com/jsla/lunch.js/issues/20
