### ISSUE TITLE
Los Feliz - 02/06/2018 @ 12:30PM

### ISSUE THREAD

**Issue by laras126** [jsla/lunch.js#110]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2), 1725 Hillhurst Ave (or suggest otherwise!)

Championed By: Lara Schenck @laras126

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by powernerd** [comment]
Looking forward to it!

**Comment by davidguttman** [comment]
I'll be there!

**Comment by davidguttman** [comment]
@billbitt ?

**Comment by billbitt** [comment]
@davidguttman @laras126 I'm in too!

**Comment by alexfarrill** [comment]
nice, i'm in 👍

**Comment by davidguttman** [comment]
30% off =)

https://www.blackboardeats.com/sp/spitz-los-angeles

**Comment by skycoin-hung** [comment]
i might be able to make this one 👍

**Comment by psugihara** [comment]
cool, our office is just around the block 👍

**Comment by danarmulder** [comment]
I have a long standing 1pm meeting Tuesday so won't be able to make this time!  Wish I could come! :(

**Comment by ian-bartholomew** [comment]
ill be there too! 👍

**Comment by jjandoc** [comment]
I'll be there.

**Comment by nickbruun** [comment]
I'll head up and say hi too!

**Comment by reactiongears** [comment]
I, unfortunately, can't make it this time. See you guys at the next one!

**Comment by alexfarrill** [comment]
hey, was great to meet you all this afternoon!  we're going to be doing an event Downtown on Feb 19 with Alexis Ohanian (and dinner/drinks), if anyone wants to come, sign up here or send me a message https://bit.ly/hustlewhileyouwork

**Comment by ashwell** [comment]
I hope lunch went well! I'm going to go ahead and close this for now but feel free to get the next ticket setup when you have the time.
