### ISSUE TITLE
Thousand Oaks - February 6th, 2018

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#111]
### @ [Bad Ass Tacos](https://www.yelp.com/biz/bad-ass-tacos-thousand-oaks)

Championed By: Franklin Henderson // @fhwrdh

**Comment by hippee-lee** [comment]
I voted for the Taco's

**Comment by fhwrdh** [comment]
Looks like Bad Ass Tacos it is! See you all tomorrow.

**Comment by fhwrdh** [comment]
Awesome lunch today! Thanks to everyone who came out. See you all next month!
