### ISSUE TITLE
Long Beach - February 6th, 2018

### ISSUE THREAD

**Issue by meganmcgeee** [jsla/lunch.js#112]
# Long Beach
### @ :heart: [Linden Public](https://www.yelp.com/biz/linden-public-long-beach)

Championed By: Megan McGee @meganmcgeee

**Comment by seanwestfall** [comment]
@meganmcgeee Hey Stranger, hehe. I'll have lunch with you.

Been working on that app too, I showed you a couple of weeks ago. Got it into a executable, and added more features (but there's lots of bugs), so I could install it onto your phone. 
Could use your feedback, we can discuss over lunch.

**Comment by postphotos** [comment]
Looking forward to seeing you fine folks again soon!

**Comment by uppal101** [comment]
https://www.yelp.com/biz/linden-public-long-beach 50% off voucher on linked in :)

**Comment by meganmcgeee** [comment]
Turns out that Beer Belly is closed on Tuesdays. V. sad.  Linden Public is supposed to be great though!

**Comment by davidnuon** [comment]
Linden Public is pretty good

**Comment by machikoyasuda** [comment]
@willopez lunch crew!

**Comment by meganmcgeee** [comment]
See yas soon!
