### ISSUE TITLE
Santa Monica - February 6, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#113]
### @ Plan Check
([yelp](https://www.yelp.com/biz/plan-check-kitchen-and-bar-santa-monica))
([google maps](https://www.google.com/maps/place/Plan+Check+Kitchen+%2B+Bar/@34.0135606,-118.5001526,15.66z/data=!4m8!1m2!2m1!1splan+check!3m4!1s0x80c2a4d005033287:0x3cf280ddad44fdec!8m2!3d34.0143136!4d-118.4974533))

Championed By: Michele @mnicole 

Vote for your preferred place, or suggest one in the comments!

:smile: 800 Degrees
:tada: Plan Check
:+1: Cha Cha Chicken

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
Thanks for setting this up @mnicole 

Good selection of lunch choices!

**Comment by JMSantos94** [comment]
Plan Check \o/ 🍔

**Comment by ashwell** [comment]
looks like Plan Check is the winner!

**Comment by ashwell** [comment]
@mnicole I added yelp and google maps links, I assume you meant the one in Downtown SM and not the one on Sawtelle

**Comment by mnicole** [comment]
Thanks for coming, everyone! Great to meet you all 👍

**Comment by ashwell** [comment]
Great lunch.js! Looking forward to the next one! thanks for being a champion @mnicole!
