### ISSUE TITLE
Calling All Champions - March 6th, 2018

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#116]
## Hey lunch.js Champions!

The next first Tuesday of the month is March 6th, 2018
Please create new issues when you get the chance.

## Lunch Locations
🆕 - Westwood/UCLA - #115 ( @gr2m )
Los Feliz / West Hollywood 
Culver City
Playa Vista - @aaroncraigongithub
Santa Monica - ~~@mnicole~~
Sherman Oaks
Thousand Oaks -  @fhwrdh
Burbank
DTLA
South Bay -  @rouzbeh84
Valencia / Santa Clarita
Long Beach - @meganmcgeee

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js comment here to get started!

**Comment by mnicole** [comment]
hi, sorry, i'm going to be out of the country for this one, but i'll be back to host the next SM one!

**Comment by ashwell** [comment]
Still need lunch.js tickets for Los Feliz and Long Beach (among other places)

I'm looking at you previous champions....
@laras126 @billbitt @powernerd @meganmcgeee @seanwestfall @anguspiv @enminc

We are always looking for new lunch champions, comment here or ping me on slack if you are interested. (Or take a look at [the guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md))

**Comment by billbitt** [comment]
@ashwell I'll do it!
