### ISSUE TITLE
Culver City - March 6, 2018

### ISSUE THREAD

**Issue by leggomuhgreggo** [jsla/lunch.js#117]
# Culver City
### @ sweetgreen ([menu](https://order.sweetgreen.com/culver-city-the-lab/menu) | [map](https://www.google.com/maps/place/sweetgreen/@34.0273562,-118.3875665,15z/data=!4m5!3m4!1s0x0:0x4defcea7caa6eaa0!8m2!3d34.0273562!4d-118.3875665)), located in [The Platform](https://platformla.com/) shopping development, which has parking building the use of which is free with validation from any of the Platform businesses. 

Championed By: Greg Westneat @leggomuhgreggo

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by aaroncraig10e** [comment]
Looking forward to it!

**Comment by RobAWilkinson** [comment]
I'll be there!
