### ISSUE TITLE
Thousand Oaks - March 6, 2018

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#118]
### @ [Mouthful Eatery](https://www.yelp.com/biz/mouthful-eatery-thousand-oaks)

Championed By: Franklin Henderson // @fhwrdh

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by fhwrdh** [comment]
I've closed the voting and updated the issue with a location. Thanks to everyone for voting. If you have not been before, Mouthful is awesome.

Unfortunately, I will be in another office this day and won't make it to lunch. However, @Zhuochengyu has been kind enough to pinch hit as host. Thank you @Zhuochengyu!

**Comment by zeke** [comment]
I can probably make it to this!

**Comment by fhwrdh** [comment]
Thanks to all who attended. I heard the turnout was good. See you next month.
