### ISSUE TITLE
Santa Monica - March 6th, 2018 @12:30pm

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#119]
# Santa Monica
### @ [M Street Kitchen](https://www.yelp.com/biz/m-street-kitchen-santa-monica-2)
2000 Main St
Santa Monica, CA 90405

Championed By: Ryan @ashwell (looking for another, comment below)

Voting Options:
:+1: - [800 Degrees](https://www.yelp.com/biz/800-degrees-neapolitan-pizzeria-santa-monica)
:smile: - [M Street Kitchen](https://www.yelp.com/biz/m-street-kitchen-santa-monica-2)
:tada: - [Mendocino Farms](https://www.yelp.com/biz/mendocino-farms-santa-monica)
:heart: - [Tocaya Organica](https://www.yelp.com/biz/tocaya-organica-santa-monica)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
Super bummed, I'm not going to make it today. 

I hope those of you that voted can still make it! Let me know how it goes!

**Comment by andrewferk** [comment]
I'll be biking from the promenade soon. I'll be wearing a "Stranger" shirt that is a mix of Adidas and Stranger Things.

**Comment by JMSantos94** [comment]
I intended to attend, but I am out of town today. Hope to see you all on the next lunch!

**Comment by acemail10** [comment]
I'll be there. I'll be wearing a brown polo.

**Comment by fierceblonde** [comment]
going to drop in too!

**Comment by acemail10** [comment]
We got a table outside in the very back.

**Comment by fierceblonde** [comment]
It was great meeting you, Avi and Andrew! Hope to see you guys again some time!

**Comment by ashwell** [comment]
Sounds like it was a great lunch.js still bummed I missed it!

Until next month!

**Comment by acemail10** [comment]
It was great meeting both of you too! Looking forward to the next event!
