### ISSUE TITLE
Playa Vista - September 6th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#12]
# Playa Vista
### @ TBD

Championed By: David Aktary @aktary 

At [Big Mango](http://bigmangocatering.com)

**Comment by ashwell** [comment]
@cateches @allreddy @8bitDesigner

I'm sure there are more Playa people I'm forgetting but this location needs a champion. Let me know if you want to take this on and I can add you as a collaborator to the repo.

**Comment by ashwell** [comment]
whoops, wrong username for Sam, @samlecuyer

**Comment by aktary** [comment]
I'll take it on

**Comment by ashwell** [comment]
well @aktary I just made it official!

**Comment by 8bitDesigner** [comment]
I'd love to champion an event when I'm back in LA - currently in NYC through December.

**Comment by ashwell** [comment]
Pinging @8bitDesigner's suggested playa people

@derduher @marcusmolchany @timzero

**Comment by marcusmolchany** [comment]
should be able to come!

**Comment by derduher** [comment]
yeah I'm down

**Comment by aktary** [comment]
Great!  As for locations, I'm thinking [Sol Cocina](http://www.solcocina.com)... or... suggestions?

**Comment by jarrettch** [comment]
Sol Cocina looks good. I was thinking Big Mango Cafe. But I'm down for whatever.

**Comment by arjansingh** [comment]
[BarBianca](http://www.hotelmdr.com/barbianca-marina-del-rey-restaurants.php)

**Comment by mmccall** [comment]
👍

**Comment by aktary** [comment]
Ok, all.... Last chance to vote is this weekend.  I'm going to close voting on Sunday!

**Comment by derduher** [comment]
looks like at least some of the fullscreen crew is going to have to bail. We've got an employee going away lunch. Bummer we were excited.

**Comment by aktary** [comment]
Voting is now closed.  It looks like we're going to [Big Mango Cafe](http://bigmangocatering.com) for lunch.js tomorrow.  See you all there!

**Comment by psyglyphik** [comment]
👍

**Comment by aktary** [comment]
I'm here, wearing a red/white checkered button down and kahki shorts.

**Comment by ashwell** [comment]
October lunch.js is up! https://github.com/jsla/lunch.js/issues/18

we are going to need a new champion for this lunch group if anyone is interested in stepping up let me know

**Comment by jarrettch** [comment]
November lunch issue is here: [js.la Nov. 1st](https://github.com/jsla/lunch.js/issues/25)
