### ISSUE TITLE
Los Feliz - March 6, 2018

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#121]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2)

Championed By: Bill Bittner @billbitt

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by powernerd** [comment]
I'll see you there.

**Comment by billbitt** [comment]
see you there @powernerd !

**Comment by billbitt** [comment]
@laras126 @alexfarrill @jxv @tvler hope to see you there!
