### ISSUE TITLE
Westwood/UCLA – April 3rd, 2018 @ 12:30PM

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#122]
# Westwood/UCLA
### 12:30 PM @ Ackerman Union, UCLA 2nd floor

@codyleyhan is hosting :)

**Comment by codyleyhan** [comment]
Willing to host!  Planning on Janss Steps, but may move depending on weather.

**Comment by codyleyhan** [comment]
Looks like it will be a little chilly tomorrow so will host in Ackerman Union, UCLA 2nd floor.

**Comment by codyleyhan** [comment]
Just an update, warmed up a bit so I am out on the ackerman union patio

**Comment by ashwell** [comment]
I'm going to close this to avoid confusion, feel free to set up the next one at your leisure @gr2m
