### ISSUE TITLE
Los Feliz – April 3rd, 2018 @ 12:30pm

### ISSUE THREAD

**Issue by laras126** [jsla/lunch.js#123]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2)

Championed By: Lara Schenck @laras126 and Bill Bittner @billbitt 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by billbitt** [comment]
can't wait!

**Comment by ashwell** [comment]
I'm going to close this to avoid confusion, feel free to set up the next one at your leisure @laras126 @billbitt
