### ISSUE TITLE
Calling All Champions - April 3rd, 2018

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#124]
## Hey lunch.js Champions!

The next first Tuesday of the month is April 3rd, 2018
Please create new issues when you get the chance. Sorry this is coming at a later notice that usual!

## Lunch Locations
Westwood/UCLA - #122 ( @gr2m )
Los Feliz / West Hollywood - #123 ( @laras126 )
Culver City
Playa Vista
Santa Monica - #127 ( @mnicole )
Sherman Oaks - #126 ( @anguspiv )
Thousand Oaks - #125 ( @Zhuochengyu )
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach

pinging previous champions...
@rouzbeh84 @fhwrdh @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @anguspiv @jcblw @bradstemke @davidkim310 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js [checkout the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by anguspiv** [comment]
I'll give Sherman Oaks one last try....

**Comment by ashwell** [comment]
Lunch.js day is tomorrow! Make sure your location is set and the most up to date information is reflected on the ticket.

**Comment by ashwell** [comment]
Next lunch.js day is May 1st! Let me know on #131 if you aren't going to be able to champion!
