### ISSUE TITLE
Thousand Oaks - April 3rd, 2018

### ISSUE THREAD

**Issue by Zhuochengyu** [jsla/lunch.js#125]
# Thousand Oaks
### 🌮 @ Bad Ass Taco at Thousand Oaks 

Championed By: Zhuocheng Yu // @Zhuochengyu

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
Thanks for becoming a champion @Zhuochengyu I'll add you as a collaborator so that you can edit labels. Let me know if you have any questions!

**Comment by hippee-lee** [comment]
🌮

**Comment by gnarmedia** [comment]
🌮

**Comment by Zhuochengyu** [comment]
I will see you all tomorrow at Bad Ass Taco.

**Comment by hippee-lee** [comment]
@Zhuochengyu - I forgot that I am out of town this week. Sorry, see you all next month!

**Comment by Zhuochengyu** [comment]
@hippee-lee Yeah, see you next month or in the Westlake Javascript Meet up.

**Comment by Zhuochengyu** [comment]
Thanks for coming. See you next month.
