### ISSUE TITLE
Sherman Oaks - April 3rd 2018

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#126]
# Sherman Oaks
### @ Blue Jam Cafe 15045 Ventura Blvd, Sherman Oaks, CA 91403

Championed By: Angus @anguspiv

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by anguspiv** [comment]
Soooooo, since I am the only one... gonna just cancel this then. Unless someone pops up last minute?

**Comment by ashwell** [comment]
😢
