### ISSUE TITLE
Santa Monica - April 3rd, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#127]
Santa Monica
Next lunch is Tuesday, April 3rd at 12:30 PM
@ Mendocino Farms
631 Wilshire Blvd
http://mendocinofarms.com/santa-monica

Championed By: michele @mnicole

Vote for where you'd like lunch to be!

👍  Mendocino Farms
😄 800 Degrees
❤️ Sweetfin Poke

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by acemail10** [comment]
Hi Michele, thanks for championing! Some ideas since you had asked: Mendocino Farms and 800 Degrees got some votes last month. I like Sweetfin Poke, though poke seems to be hit or miss for people.

**Comment by mnicole** [comment]
thanks! sounds good to me, i'll add those in a poll :)

**Comment by ashwell** [comment]
FYI @mnicole typically when I run out of ideas I go back through the previous lunch.js tickets and pick out a few places that didn't win out in the poll.

**Comment by mnicole** [comment]
hi everyone, looking forward to seeing you today! i'll try and get there a little early and grab a table. i'm wearing a striped dress.

**Comment by acemail10** [comment]
Awesome, thank you Michele. I'll be wearing a striped polo.

**Comment by ashwell** [comment]
It was great seeing everyone at lunch today!

**Comment by mnicole** [comment]
agreed! thanks everyone for coming!

**Comment by acemail10** [comment]
I'm a bit late to the party, but I agree, it was great to meet all of you! Thank you for the good company :).
