### ISSUE TITLE
Los Feliz - April 3rd, 2018

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#128]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2)

Championed By: @billbitt @laras126 

I vote we keep this going at Spitz because it seems to be easy to get to for most of our folks and there is always plenty of seating, but I am open to all suggestions!  Comment if you have an alternative you prefer and I will set up a vote!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by laras126** [comment]
Beat you to it! Haha - https://github.com/jsla/lunch.js/issues/123

**Comment by ashwell** [comment]
gonna go ahead and close this to avoid confusion

**Comment by billbitt** [comment]
haha nice @laras126
