### ISSUE TITLE
Playa Vista - April 3rd, 2018

### ISSUE THREAD

**Issue by leggomuhgreggo** [jsla/lunch.js#129]
# Playa Vista
### @ [Runway Mall] (https://www.google.com/maps/place/Runway+Mall/@33.9770129,-118.4173098,15z/data=!4m2!3m1!1s0x0:0x2a043ed5f2ffc2e1?sa=X&ved=0ahUKEwjdxeb7-YzaAhXN-lQKHcvgBmoQ_BIItAEwCg) Whole Foods 

Championed By: Greg Westneat @leggomuhgreggo && Aaron Craig  @aaroncraigongithub

Vote!
~[Hopdoddy Burger Bar](https://www.yelp.com/biz/hopdoddy-burger-bar-playa-vista?frvs=True&osq=Restaurants) - 👍~
**[Whole Foods ](https://www.yelp.com/biz/whole-foods-market-playa-vista?osq=Whole+Foods+Market) - 💯**
~[Sol Mexican Cocina](https://www.yelp.com/biz/sol-mexican-cocina-los-angeles-3?frvs=True&osq=Restaurants) - :smile:~
~[Urban Plates](https://www.yelp.com/biz/urban-plates-playa-vista?frvs=True&osq=Restaurants) - :tada:~
~[Panini Kabob Grill](https://www.yelp.com/biz/panini-kabob-grill-playa-vista?frvs=True&osq=Restaurants) - :confused:~
~[ROC Playa Vista](https://www.yelp.com/biz/roc-playa-vista-los-angeles?frvs=True&osq=Restaurants) - :heart:~

[Here's the yelp search for Runway restaurants](https://www.yelp.com/search?find_desc=Restaurants&find_loc=12746+W+Jefferson+Blvd,+Playa+Vista,+CA+90094&start=0&l=g:-118.41380193883833,33.97875155244723,-118.42023924047407,33.97341328533609) in case anyone would like something not listed on the ballot

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by RobAWilkinson** [comment]
It would be hopdaddy but they changed up my favorite salad recently :(

**Comment by stevedorke** [comment]
my vote is for whole foods: pick what you want from the salad/hot food bar & plenty of outdoor picnic tables

**Comment by aaroncraigongithub** [comment]
I'm down for WF -- Sol is pricey.  Hopdoddy is ALWAYS awesome but the line can be long.  Same with Urban Plates.

There is also an 800 Degrees pizza.

**Comment by mtham8** [comment]
Health is wealth, voting for Whole Foods!

**Comment by leggomuhgreggo** [comment]
Let's do **Whole Foods**

I think people are going to start showing up around **12:00**, but should be enough action if people can't make the earlier time and need to do 12:30, still.

**Comment by leggomuhgreggo** [comment]
Great lunch!

**Comment by RobAWilkinson** [comment]
🔥
