### ISSUE TITLE
Culver City - September 6th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#13]
# Culver City
### @ [New School of Cooking](http://newschoolcafe.com/)

Championed By: Jacob @jcblw

**Comment by ashwell** [comment]
The west side groups need to step it up! The [DTLA](https://github.com/jsla/lunch.js/issues/10) group is kickin' ass!

**Comment by itsjustmath** [comment]
I'd like to suggest [New School of Cooking](http://newschoolcafe.com/). It's [pretty spacious](http://newschoolcafe.com/tour-the-cafe/), and could accommodate a decent-sized group.

**Comment by jcblw** [comment]
I like that idea! @itsjustmath  I'll set that as the location for now.

**Comment by jcblw** [comment]
@kintendo @Elgrecode @GraysonNull tag anyone you know who would be interested in this event!

**Comment by markmatney** [comment]
hey y'all, I work in Westwood primarily but work from home in Palms once a week. I'd love to join!

**Comment by jcblw** [comment]
@markmatney we would love for you to come out on the 6th! LMK if you will be able to make it that day.

**Comment by markmatney** [comment]
Sounds good!

**Comment by marksanghoonkim** [comment]
hey everyone, I'm down to come out to this! 12:30 PM, Sept 6th works for me

**Comment by toiye** [comment]
I'd like to join in too, if that's ok.  I live just down the street.

**Comment by jcblw** [comment]
@toiye we would love for you to come, it was great meeting you last night

**Comment by jadware** [comment]
i'll join

**Comment by jcblw** [comment]
just pinging this thread, lunch.js is today! 🎉

looking forward to seeing everyone.

**Comment by markmatney** [comment]
I unfortunately won't make it since I had to go in to the office today, but I'll try to make it next time!
