### ISSUE TITLE
Long Beach - April 3, 2018

### ISSUE THREAD

**Issue by seanwestfall** [jsla/lunch.js#130]
# Long Beach
### @ Donburi Cafè
https://www.yelp.com/biz/donburi-caf%C3%A8-long-beach

Address:
245 Pine Ave
Ste 120
Long Beach, CA 90802

Championed By: sean @sean.westfall

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by seanwestfall** [comment]
So, me and another developer have decided to meet here: https://www.yelp.com/biz/donburi-caf%C3%A8-long-beach Donburi Cafè for lunch tomorrow at 12:30. If anyone is reading this, please join us!

**Comment by Kristopherlb** [comment]
Barring any unforeseen issues, I'll be there.  I've been wanting to try this place!

**Comment by Kristopherlb** [comment]
I’m sitting outside. I’m the guy with the bright red beard.
