### ISSUE TITLE
Calling All Champions - May 1st, 2018

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#131]
## Hey lunch.js Champions!

The next first Tuesday of the month is May 1st, 2018
Please create new issues when you get the chance.

## Lunch Locations
Westwood / UCLA
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach

pinging previous champions...
@rouzbeh84 @fhwrdh @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @anguspiv @jcblw @bradstemke @davidkim310 @laras126 @Zhuochengyu @gr2m 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js [checkout the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by gr2m** [comment]
Sorry I totally missed that one, I was on vacation and have been out today anyway. I probably won’t be able to host the Westwood one for the next few months but I’ll try to find another host :)
