### ISSUE TITLE
South Bay  – May 1st, 2018 @ 12:30PM

### ISSUE THREAD

**Issue by rouzbeh84** [jsla/lunch.js#132]
### 12:30 PM @ [The Point](http://www.thepointsb.com/) 

[*Link above + this one contain links to all places included with a description just in case*](http://www.thepointsb.com/)

Championed By: [rouzbeh84](https://github.com/rouzbeh84)
  
- **HOPDODDY BURGER BAR** - *beer/burgers using all-natural/mindfully sourced ingredients.*
- **LIL' SIMMZY'S ON THE DECK** - *pub grub and grog on the go.*
- **MENDOCINO FARMS** - *elevating the art of the sandwich.*
- **NORTH ITALIA** - *perfecting handmade pizza/pasta w/fresh flavors from the garden/farm/sea*
- **TOCAYA ORGANICA** - *Modern Organic Mexican Restaurant*
- **TRUE FOOD KITCHEN** - *A flavor-forward, nutrition based menu.*
- **UMI BY HAMASAKU** - *Sophisticated harmony of Japanese cuisine*

Same deal as always, no voting because I'm hoping that there is an option for all listed here! If not, post your suggestion and it definitely will be considered!

![](http://www.dorisrappmd.com/wp-content/uploads/2017/06/lax-los-angeles.png)

**Comment by rouzbeh84** [comment]
cc: @w1lujeng @aroduribe @johntran @MrBenJ @machikoyasuda @jacklee0223 @JackieCabinet @gschrum @dlcoffee @jadware @forrest-akin @jessbakk 🙌

thoughts? anybody wanna change it up?

**Comment by rouzbeh84** [comment]
Anybody in here? Trying to gauge outcome due to weather conditions 😃

**Comment by johntran** [comment]
@rouzbeh84 Staying indoors today :). Next month?

**Comment by johntran** [comment]
Allergic to sprinkle

**Comment by rouzbeh84** [comment]
Sounds good. Postponed then!
