### ISSUE TITLE
Thousand Oaks - May. 1st, 2018

### ISSUE THREAD

**Issue by Zhuochengyu** [jsla/lunch.js#133]
# Thousand Oaks
### 🍖  @ Mediterranean Pita Grill(https://www.yelp.com/biz/mediterranean-pita-grill-westlake-village-3)

Championed By: Zhuocheng Yu // @Zhuochengyu

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by hippee-lee** [comment]
🍖 - All my crazy April travel will be done. I'm excited to put this on my calendar!

**Comment by cdransf** [comment]
🍖

**Comment by zeke** [comment]
🍖Maybe 🤞

**Comment by ABitOfKylie** [comment]
Would like to come and meet new faces.

**Comment by ABitOfKylie** [comment]
Well, it almost happened. Will have to wait until next month. Last minute obstacles.

**Comment by Zhuochengyu** [comment]
Thanks for coming. See you next month!
