### ISSUE TITLE
Santa Monica - May. 1st, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#134]
# Santa Monica
### @ Santa Monica Place Mall 3rd Floor Food Court
395 Santa Monica Place, Santa Monica, CA 90401

Championed By: michele @mnicole

Hi! As discussed last time, let's meet at the mall food court. There are several restaurants, or you can bring your own lunch. There's seating outside.

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by acemail10** [comment]
Unfortunately I can't make it this time. Have fun!

**Comment by mnicole** [comment]
We are sitting at a table by the window near pasta bar for anyone coming!

**Comment by delrosario** [comment]
was nice meeting everyone 🙏🏾🙏🏾

**Comment by mnicole** [comment]
thanks for coming out! it was great to meet you! come to the next one too :)
