### ISSUE TITLE
Los Feliz – May 1, 2018 at 12:30 PM

### ISSUE THREAD

**Issue by laras126** [jsla/lunch.js#135]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2), 1725 Hillhurst Ave 

Championed By: Lara Schenck @laras126

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by powernerd** [comment]
See ya tomorow!

**Comment by jadware** [comment]
i'm in for this one

**Comment by mtham8** [comment]
Unfortunately, got a last minute scope meeting... ew, see ya'll next month's lunchjs!
