### ISSUE TITLE
Thousand Oaks - June 5th, 2018

### ISSUE THREAD

**Issue by Zhuochengyu** [jsla/lunch.js#138]
# Thousand Oaks
### Mouthful Eatery (https://www.yelp.com/biz/mouthful-eatery-thousand-oaks) 🍳 

Any other suggestion is welcomed.

Championed By: Zhuocheng Yu @zhuochengyu

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by gnarmedia** [comment]
🍳

**Comment by Zhuochengyu** [comment]
Nice! I will see you at Mouthful Eatery.

**Comment by Zhuochengyu** [comment]
@gnarmedia @hippee-lee I am very sorry about this. I had a meeting before lunch and totally miss today's lunch js.

**Comment by hippee-lee** [comment]
no worries. see you next time.
