### ISSUE TITLE
Santa Monica - June 5th, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#139]
# Santa Monica
### @ [Cava](https://www.yelp.com/biz/cava-santa-monica-2)
1318 2nd St

Championed By: michele @mnicole

Please vote for the place you want to go:

:smile: [Taco Libre](https://www.yelp.com/biz/taco-libre-santa-monica-santa-monica)
:tada: [Cava](https://www.yelp.com/biz/cava-santa-monica-2)
:heart: [Hi-Ho Cheeseburger](https://www.yelp.com/biz/hiho-cheeseburger-santa-monica)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by aloukissas** [comment]
Looking forward to joining my first lunchjs event!

**Comment by mnicole** [comment]
hi everyone, looking forward to seeing you today at cava! i'm wearing a black dress with a blue cardigan.

**Comment by ashwell** [comment]
Bummed I couldn't make it out today, hope it was a good lunch!

**Comment by mnicole** [comment]
Thanks everyone for coming! It was great to meet/see people again. Our biggest turnout in a while! See you next time.
