### ISSUE TITLE
October 2016 lunch.js Champion Shout Out

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#14]
## Hey `lunch.js` Champions!
The next first Tuesday of the month is `October 4th, 2016`
Please create new issues when you get the chance.

## Current Champions
Santa Monica - @etanlubeck
Culver City - @jcblw
Playa Vista - @aktary
West Hollywood - @davidguttman

## Locations with Champions Needed
SF Valley
DTLA (Downtown)

@machikoyasuda -- will you be leaving the DTLA group next month?

**Comment by machikoyasuda** [comment]
i am being traded from dtla to culver city :) what's up @jcblw! 






On Wed, Sep 7, 2016 at 7:39 AM +0900, "Ryan Bogle" <notifications@github.com> wrote:












Assigned #14 to @machikoyasuda.

**Comment by jcblw** [comment]
@machikoyasuda glad to have you join the Culver Crowd!

**Comment by aktary** [comment]
Hey guys... sorry, but I'm not going to be in town for this event (and may miss future events.)  I'm afraid Playa Vista will need another champion.

**Comment by ashwell** [comment]
@aktary if you wouldn't mind creating a new ticket for Playa Vista for October we can start a discussion for a new champion there

**Comment by aktary** [comment]
@ashwell no problem

**Comment by ashwell** [comment]
@etanlubeck, @jcblw please create your respective lunch.js October issues for Santa Monica and Culver City
