### ISSUE TITLE
Playa Vista - June 5 2018

### ISSUE THREAD

**Issue by aaroncraigongithub** [jsla/lunch.js#140]
# Playa Vista
### @ HopDoddy Playa Vista (https://goo.gl/maps/fXHqJWS6MrQ2)

Championed By: Aaron @aaroncraigongithub

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by RobAWilkinson** [comment]
🍔🍔🍔

**Comment by leggomuhgreggo** [comment]
💯

**Comment by ashwell** [comment]
Going to close this to avoid confusion, I hope lunch went well!
