### ISSUE TITLE
Burbank/Glendale - June 5, 2018

### ISSUE THREAD

**Issue by toiye** [jsla/lunch.js#141]
# Burbank/Glendale
### @ Kabab Way - Other suggestions welcome
https://goo.gl/maps/6z6yYUeMSBP2

Championed By: Tatsu @toiye

:+1: thumbs up - Even if you can't attend this time, but are interested in a Burbank lunch.js at a later date.

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by toiye** [comment]
Hey @kylehayes!  I'm at studio tech in the paula building.

**Comment by ashwell** [comment]
Going since this lunch has passed, I hope it went well!
