### ISSUE TITLE
Los Feliz - June 5th, 2018

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#142]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2)

Championed By: @billbitt @laras126 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by davidguttman** [comment]
![](https://media.giphy.com/media/11dgYWwHnEFomQ/giphy.gif)

**Comment by ashwell** [comment]
I hear it was a nice intimate lunch, I hope the next one is a party!
