### ISSUE TITLE
Calling All Champions - July 10th, 2018

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#144]
## Hey lunch.js Champions!

The next first Tuesday of the month is July 3rd, 2018 but since that is a holiday weekend (AMERICA!) we will push lunch.js back a week to **July 10th**
Please create new issues when you get the chance.

## Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach

pinging previous champions...
@rouzbeh84 @fhwrdh @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @anguspiv @jcblw @bradstemke @davidkim310 @laras126 @Zhuochengyu ~~@gr2m~~ @enminc @LearningNerd @stevedorke @jjandoc @jarrettch 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by ashwell** [comment]
forgot to mention you too @jjandoc! Let's make DTLA happen next month!

cc: @jarrettch

**Comment by ashwell** [comment]
Where my champions at!?

**Comment by gr2m** [comment]
Can you leave me out for now? I’m occupied with family, I’ll get back to you :)

**Comment by ashwell** [comment]
Hope all the lunches went well, feel free to close your old tickets when you get the chance.

Next lunch.js will be Aug 7th as outlined in #151
