### ISSUE TITLE
DTLA - July 10, 2018

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#145]
# DTLA
### @ Dankness Dojo, 832 S Olive St, Los Angeles, CA 90014

Championed By: @jjandoc

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jarrettch** [comment]
Barring any scheduling conflicts I'm there.

**Comment by haydenbetts** [comment]
RSVP!

**Comment by jjandoc** [comment]
Last minute work conflict came up and unfortunately I _can't_ make it tomorrow. Have a great time and I'll catch you all next month!

**Comment by jarrettch** [comment]
@jjandoc what's the parking like for this place? @haydenbetts I'm still down to meet up for lunch if you and anyone else is!

**Comment by haydenbetts** [comment]
@jarrettch yup I'm still down for lunch! I'm working near Pershing square and can anywhere around there.

**Comment by jarrettch** [comment]
@haydenbetts bummer, I got added to a mandatory meeting during the lunch.js time slot(to my surprise this morning) so I can't make it now unfortunately... :\
