### ISSUE TITLE
Mid-City / La Brea

### ISSUE THREAD

**Issue by stevedorke** [jsla/lunch.js#148]
# Mid-City / La Brea 
### @ [Original Farmer's Market](https://www.yelp.com/biz/original-farmers-market-los-angeles)

Championed By: Steven Lee @stevedorke

La Brea/Mid-City covers such a large area so it's hard to choose a place that has enough variety, parking, seating AND is not too far away for most; here are a few possible places, or feel free to suggest a place in the comments!

__Vote: [CLOSED]__
[Original Farmer's Market](https://www.yelp.com/biz/original-farmers-market-los-angeles) :smile:
[Sushi by H](https://www.yelp.com/biz/sushi-by-h-los-angeles) :tada:
[Gish Bac (Oaxacan)](https://www.yelp.com/biz/gish-bac-restaurant-los-angeles-2) :+1:
[Meals by Genet (Ethiopian)](https://www.yelp.com/biz/meals-by-genet-los-angeles)  :heart:

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by RobAWilkinson** [comment]
Mid city/ La brea? I'll be there! @stevedorke  FYI your link for sushi is off.

**Comment by stevedorke** [comment]
@RobAWilkinson thanks, fixed!

**Comment by RobAWilkinson** [comment]
@stevedorke I got slammed with work today and am not going to be able to make this :(

**Comment by stevedorke** [comment]
@RobAWilkinson it's actually next week on July 10th!

**Comment by stevedorke** [comment]
@RobAWilkinson & @all, anyone able to make it today?
