### ISSUE TITLE
Santa Monica - July 10th, 2018 @ 12:30pm

### ISSUE THREAD

**Issue by meganspeir** [jsla/lunch.js#149]
# Santa Monica - July 10th, 2018 @ 12:30pm
### @ Sweetfin Poké, 829 Broadway, Santa Monica, CA 90401

Championed By: Megan @meganspeir

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by mnicole** [comment]
hi @meganspeir 👋 
thanks for making this, i was delayed this month :) see you there!

**Comment by derekmiranda** [comment]
I’ll be there later as well!

**Comment by meganspeir** [comment]
I’m the lady with pink crutches 😄

**Comment by ashwell** [comment]
Great seeing everyone at lunch!

btw this was the Pho place I couldn't remember the name of, https://goo.gl/maps/VqymjPvvAsB2
