### ISSUE TITLE
Los Feliz - September 4th, 2018

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#156]
# Los Feliz 
### @ HomeState

Championed By: Robert @powernerd and Bill @billbitt 

Location options: Voting Closed. HomeState has won by a landslide 3, 0.
~~:heart: [Spitz](https://goo.gl/maps/NYPqVnU1t792l)~~
:tada: [HomeState](https://goo.gl/maps/2bKMVCqptQt)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by billbitt** [comment]
voting for HomeState just to shake things up (and because it is delicious) :)

**Comment by powernerd** [comment]
See you Tuesday at HomeState!

**Comment by billbitt** [comment]
woohoo!

**Comment by davidguttman** [comment]
See you there!
