### ISSUE TITLE
Santa Monica - September 4th, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#157]
# Santa Monica
### @ [Flower Child](https://www.yelp.com/biz/flower-child-santa-monica)

Championed By: michele @mnicole

Vote for where you'd like to go by adding an emoji:

:smile: [Benny's Tacos](https://www.yelp.com/biz/bennys-tacos-and-chicken-rotisserie-santa-monica-2) 
:heart: [Flower Child](https://www.yelp.com/biz/flower-child-santa-monica)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jimthoburn** [comment]
Thanks for championing, Michele! I’d love to join ya’ll for lunch  😉

**Comment by mnicole** [comment]
Hi everyone, I’m wearing a green dress and will be looking for a table upstairs most likely after ordering! Be there in a few.

**Comment by mnicole** [comment]
Sitting upstairs in the far back corner
