### ISSUE TITLE
SF Valley - October 4th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#16]
# SF Valley
### @ TBD

Championed By: **LOOKING FOR A CHAMPION**

**Comment by ashwell** [comment]
@wingedearth if you are interested in getting the SF Valley lunch.js group of the ground let me know! This group is still looking for a champion

**Comment by wingedearth** [comment]
Hi Ryan,

I’d love to help out, but I’ve got a lot going on right now, and am not sure I can take on the responsibility of being the point person on this. However, I’d be happy to attend.

Cheers,
Andrew
