### ISSUE TITLE
DTLA - October 2, 2018

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#160]
# DTLA
### @ Dankness Dojo, 832 S Olive St, Los Angeles, CA 90014

Championed By: @jjandoc

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
With so many offices in DTLA you'd think this would be the biggest lunch group!

Let me know if there is anything I can do to get the word out, next lunch.js day is Nov 6th!
