### ISSUE TITLE
Westwood/UCLA - October 2, 2018 @ 12:30pm 

### ISSUE THREAD

**Issue by laras126** [jsla/lunch.js#161]
# Westwood / UCLA
### @ Park near Westwood Rec Center, 1350 S Sepulveda

Bring your own lunch, or grab one at the many places nearby!  

Championed By: Lara Schenck @laras126

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by tinuola** [comment]
I'm in!
Suggestions : 
[Grilliant ](http://grilliantfood.com/)
[Fundamentals](http://www.fundamental-la.com/westla/) (Space is smallish, might work if we're a small group?)
[Maharaja Cuisine of India](http://maharajawestwood.com/) (Buffett style--quite good!)

**Comment by jimthoburn** [comment]
Hooray! I’d love to join ya’ll for lunch.  :o)

**Comment by gr2m** [comment]
I did it on the campus, Picknick style in the past, See https://github.com/jsla/lunch.js/issues/115

**Comment by tinuola** [comment]
A picnic works too.

**Comment by rawalpunit** [comment]
If y'all are leaning towards the picnic aspect..Westwood Rec center on 1350 S Sepulveda has a quite nice park are in the back of its property.....btw..do I have to RSVP somewhere for lunch? or do I just show up? I'm brand new to this group!

**Comment by laras126** [comment]
Let's picnic at 1350 S Sepulveda! @rawalpunit – you can just mention on the issue here if you can make it.

**Comment by gr2m** [comment]
Attari Sandwich Shop has great sandwiches to takeaway, it's a ~10 min walk away from the park: https://goo.gl/maps/UMixCe21tEv

**Comment by rawalpunit** [comment]
Gah! Can't make it today but I will be there for the next one

**Comment by ashwell** [comment]
Gonna go ahead and close this, hope it was a good lunch! next lunch.js day is Nov 6th
