### ISSUE TITLE
Santa Monica - October 2nd, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#162]
# Santa Monica
### @ [Hi-Ho Cheeseburger](https://www.yelp.com/biz/hiho-cheeseburger-santa-monica) 

Championed By: michele @mnicole
Vote for where you'd like to go by adding an emoji:

:smile: [Hi-Ho Cheeseburger](https://www.yelp.com/biz/hiho-cheeseburger-santa-monica) 
:heart: [Sumo Dog](https://www.yelp.com/biz/sumo-dog-santa-monica-2)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jcblw** [comment]
@mnicole planning on making this one.

@ashwell  you coming?

**Comment by jcblw** [comment]
@fierceblonde it would be nice to see you too 😁

**Comment by ashwell** [comment]
@jcblw you're back in town? I'll do my best to be there

**Comment by jcblw** [comment]
Yep! Hope you can make it.

**Comment by jcblw** [comment]
next time!
