### ISSUE TITLE
Los Feliz - October 2, 2018

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#163]
# Los Feliz
### @ HomeState

Championed By: @billbitt and @powernerd

:tada: [HomeState](https://www.yelp.com/biz/homestate-los-angeles)

If you are planning to attend subscribe to the issue to get notifications for new comments!

**Comment by powernerd** [comment]
Be aware that Spitz has two locations: Eagle Rock and Los Feliz. I'd love to someday have a meetup in Eagle Rock which is much closer to Pasadena, but this is referring to the Los Feliz location.

**Comment by billbitt** [comment]
looks like HomeState got the most votes.  See you all there!
