### ISSUE TITLE
Long Beach - October 2, 2018 

### ISSUE THREAD

**Issue by seanwestfall** [jsla/lunch.js#164]
# Long Beach
### @ Donburi Cafe
http://donburicafe.site.mobi/
https://www.yelp.com/biz/donburi-caf%C3%A8-long-beach

Though I'm open to other suggestions.

Championed By: Sean ${ @seanwestfall  }

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by davidnuon** [comment]
Donburi is 👍  See you there!

**Comment by postphotos** [comment]
Hi friends, this sounds 🔥 - see you then!

**Comment by meganmcgeee** [comment]
I'm In and bringing a few folks!! 💯
