### ISSUE TITLE
Culver City / Playa Vista - October 2nd, 2018

### ISSUE THREAD

**Issue by tekhaus** [jsla/lunch.js#165]
# Culver City / Playa Vista
### @ [Jackson Market and Deli](http://www.jacksonmarketanddeli.com/)

Championed By: Brad @tekhaus

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by tekhaus** [comment]
Ok, Jackson's it is! See everyone at 12:30.

**Comment by RobAWilkinson** [comment]
I have a meeting that ends at 1, luckily my office is 2 blocks away, I'll see you all there

**Comment by jarrettch** [comment]
I'm glad to see this one back up and running, wish I could make it but I cant. FWIW Culver and Playa joined forces a while ago just because the members asked for it. They dont have to be joined so feel free to just do only Culver or Playa next time, might make things easier as far as planning.

**Comment by rouzbeh84** [comment]
Gonna try and make it but work is super busy and it's not as close to me as i thought but i do miss the f out of their italian sandwich :(
