### ISSUE TITLE
Los Feliz - November 6, 2018 @ 12:30

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#167]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2)

Championed By: @billbitt and @powernerd

If you are planning to attend subscribe to the issue to get notifications for new comments!

**Comment by aroduribe** [comment]
@machikoyasuda do you want to come with me?

**Comment by powernerd** [comment]
Looking forward to it!

**Comment by billbitt** [comment]
@powernerd unfortunately I'm not going to be able to make it any more. Will you be able to hold up the champion duties?

**Comment by andysaman** [comment]
Yup, no problem @billbitt

**Comment by ashwell** [comment]
closing this one out, the next lunch.js is Dec 4th!
