### ISSUE TITLE
DTLA - November 6, 2018 @ 12:30

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#168]
# DTLA
### @ Dankness Dojo, 832 S Olive St, Los Angeles, CA 90014

Championed By: @jjandoc

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
@jjandoc looks like @LearningNerd wants to co-champion!

I'm going to close this out to avoid confusion!
