### ISSUE TITLE
Long Beach - November 6, 2018

### ISSUE THREAD

**Issue by postphotos** [jsla/lunch.js#171]
# Long Beach

### Location: Sura
621 Atlantic Ave
Long Beach, CA 90802

~- Donburi? 🎳 👍~ 
~- Sura? 🐔 🎉~ 
~- Something else? ❓~

_Let's vote!_

Championed By: Leo - @postphotos

**Comment by seanwestfall** [comment]
I am coming! and would prefer sura, since we did Donburi last time.

**Comment by davidnuon** [comment]
Let's do sura

**Comment by postphotos** [comment]
SURA!!

**Comment by ashwell** [comment]
@postphotos is this the place your group is heading to? https://www.yelp.com/biz/sura-korean-bbq-and-tofu-house-long-beach

Please update the main ticket comment with the address if this is in fact the correct location
