### ISSUE TITLE
Calling All Champions - December 4th, 2018

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#172]
## Hey lunch.js Champions!

The next first Tuesday of the month is **December 4th, 2018**
Please create new issues when you get the chance.

Note that lunch.js seems to run much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

## Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach

pinging previous champions...
@rouzbeh84 @fhwrdh @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @anguspiv @jcblw @davidkim310 @laras126 @Zhuochengyu @enminc @LearningNerd @stevedorke @jjandoc @jarrettch @billbitt @powernerd 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by ashwell** [comment]
Let me know if I need to add or remove anyone from the champions list!

**Comment by LearningNerd** [comment]
I'm down to help with the DTLA meetup :) anyone wanna co-host?

**Comment by ashwell** [comment]
Nice! @LearningNerd, @jjandoc has been doing the DTLA one I know he has been wanting to get more people to come out for it.

**Comment by jjandoc** [comment]
Cool! Just opened up an issue. We can discuss DTLA stuff over there.

**Comment by bradstemke** [comment]
Hey! I just moved to Seattle, so you can remove me from the list, thanks! : )

**Comment by ashwell** [comment]
no problem @bradstemke! sorry for all the unnecessary pinging

**Comment by bradstemke** [comment]
@ashwell Ha no worries at all! thanks. Unless you all need a lunch sponsor up in Seattle, ha

**Comment by powernerd** [comment]
Hey @ashwell feel free to tag me on future "Calling All Champions". Thanks!
