### ISSUE TITLE
DTLA - December 4th, 2018

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#173]
# DTLA
### @ First Draft Tap Room - 1230 S Olive St, Los Angeles, CA 90015

Championed By: @jjandoc and @LearningNerd 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jjandoc** [comment]
The last few months we've been doing this at the Dankness Dojo, which usually has ample seating, great beer, and a totally vegan friendly menu. I'm open to mixing it up this month, though, depending where in downtown interested people are at.

**Comment by jjandoc** [comment]
Dictatorially setting this location to First Draft Tap Room at Pico and Olive.

**Comment by LearningNerd** [comment]
I'm not gonna make it today :( I'm so sorry @jjandoc ! I'm still on board to help with the dtla lunch though, I can run it next month
