### ISSUE TITLE
Thousand Oaks - December 4th, 2018 @ 12:30

### ISSUE THREAD

**Issue by Zhuochengyu** [jsla/lunch.js#174]
# Thousand Oaks
### Urban Plates (https://www.yelp.com/biz/urban-plates-thousand-oaks)

Championed By: Zhuocheng Yu @zhuochengyu

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ABitOfKylie** [comment]
newcomer - planning on attending.

**Comment by gnarmedia** [comment]
I'm gonna try to make it and being some of the team with me
