### ISSUE TITLE
Los Feliz - December 4th, 2018

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#175]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2) 🍖 🥗 🥖 

Please come join us for lunch and talk about past JS.LA experiences and your ongoing JavaScript projects! Spitz is a cool place, lots of seating and quick service. However, if you prefer another spot speak up!

If you are planning to attend post a comment and let us know!

Championed By: Andy @powernerd and Bill @billbitt

**Comment by billbitt** [comment]
I’ll be there!

**Comment by hanhanhan** [comment]
I'll be there!

**Comment by hah-nan** [comment]
I will also be there!

**Comment by davidguttman** [comment]
See you soon!
