### ISSUE TITLE
Santa Monica - December 4, 2018

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#176]
### @ [Mendocino Farms](https://www.mendocinofarms.com/santa-monica/menu/)

Championed By: michele @mnicole
Vote for where you'd like to go by adding an emoji:

:heart: [Mendocino Farms](https://www.mendocinofarms.com/santa-monica/menu/)
:smile: [Flower Child](https://www.yelp.com/biz/flower-child-santa-monica) 
Or suggest a place in the comments?

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
I don't think I'm going to be able to make it tomorrow :(

**Comment by ptantono** [comment]
Have we decided on a place?

**Comment by mnicole** [comment]
yeah weirdly the voting emojis aren't showing. but i think last time i checked mendocino was winning. i'm wearing a dark blue long sleeve dress today, see you in a few hours!

**Comment by ptantono** [comment]
is this the right address? 
https://www.google.com/maps/place/631+Wilshire+Blvd,+Santa+Monica,+CA+90401/@34.0214649,-118.4958651,17z/data=!4m7!1m4!3m3!1s0x80c2a4c8e805dc9d:0x4d865b7c2fed92ac!2s631+Wilshire+Blvd,+Santa+Monica,+CA+90401!3b1!3m1!1s0x80c2a4c8e805dc9d:0x4d865b7c2fed92ac

**Comment by mnicole** [comment]
yep!

**Comment by ptantono** [comment]
I’m also wearing blue long sleeve, semi dress shirt. =]

**Comment by mnicole** [comment]
Great meeting you @ptantono ! @ashwell hope to see you next time :)

**Comment by ptantono** [comment]
It was fun. Thank you for sharing all of your ReactJS tips. Also the slack channels. Would you mind reminding me some of the slack channels that you mention for job postings? Thank you again.
