### ISSUE TITLE
Culver City - February 5th, 2019

### ISSUE THREAD

**Issue by malinatran** [jsla/lunch.js#177]
# Culver City
### @ [sweetgreen](https://order.sweetgreen.com/culver-city-the-lab/menu)
PLATFORM
8840 Washington Blvd 
Culver City, CA 90232 

Championed By: Malina Tran @malinatran x Greg Westneat @leggomuhgreggo 
Transportation: Expo Line to Culver City, free parking with validation from any PLATFORM business

**Comment by danarmulder** [comment]
Who's coming tomorrow?

**Comment by lcampbe79** [comment]
I am.

**Comment by maximbert** [comment]
I'll be joining for my first Lunch.js :) . I'm working on getting a few of my co-workers (from Archer Education) to join as well.

**Comment by leggomuhgreggo** [comment]
Lookin forward to seein all you estimable organizers of zero's and one's tomorrow. I'll keep an eye on slack in case anyone runs into any snags. CELEBRATE 🤘

**Comment by rayning0** [comment]
Like Malina and Greg, I also work at sweetgreen. See you at our restaurant today!

**Comment by aroduribe** [comment]
I'll be there!

**Comment by maximbert** [comment]
I’m here too but don’t see the group. I’m sitting outside with a black puff jacket.

**Comment by maximbert** [comment]
Just grabbed a large table right by entrance

**Comment by aroduribe** [comment]
It was great chatting with you all!
