### ISSUE TITLE
Marina Del Rey - February 5th, 2019

### ISSUE THREAD

**Issue by MrBenJ** [jsla/lunch.js#179]
# Marina Del Rey
### @ Pitfire Pizza - Marina Del Rey

Location: https://www.google.com/maps/place/Pitfire+Pizza/@33.9914281,-118.445095,16.02z/data=!4m8!1m2!2m1!1spizza+marina+del+rey!3m4!1s0x0:0x8e1d4aec8c3342ca!8m2!3d33.9946672!4d-118.4387138

Championed By: Jarrett Harris @jarrettch and Ben Junya @MrBenJ

Voting has ended - looks like Pitfire Pizza!

We'll be grabbing a table. Order at the front and come hang out!

Watch this issue in order to see where we're at. I will post a comment with our approximate location when @jarrettch and I sit down.

See you soon!

**Comment by aloukissas** [comment]
NIGHT + MARKET is just amazing.
