### ISSUE TITLE
Playa Vista - October 4th, 2016

### ISSUE THREAD

**Issue by aktary** [jsla/lunch.js#18]
# Playa Vista
### @ TBD 

Championed By: Jarrett Harris @jarrettch 

Anyone else with recs? If not I'll leave these two for the time being.

Please Chose Our Destination:
Phorage: 🎉 
Sol Cocina: ❤️

**Comment by ashwell** [comment]
Unfortunately @aktary isn't going to be able to champion this event anymore, so we will need to pass the torch. I'm still writing up a guide for champions but if you have any questions/interest please let me know!

**Comment by jarrettch** [comment]
I volunteer as tribute!

Honestly I'm very shy and quiet but I'm stepping out there and I'll do my best if chosen. Where do we want this at? I'll mention Phorage for some Pho and Banh Mi sandwiches.

http://www.asap.phoragela.com/

**Comment by ashwell** [comment]
@jarrettch awesome! I'll add you as the champion for Playa.

Basically as a champion it's up to you to create an issue each month for your lunch.js crew. For now we are being informal about selecting a location. If you want to come up with three options and let people vote that's cool. If you just want to pick a place that's well within your role as the champion.

Once I get a formal champion guide written I'll be sure to let everyone know.

The important part is updating the Issue for that month with all the proper details, so when someone lands on the issue page all the information is right at the top.

**Comment by ashwell** [comment]
@jarrettch take a look at the [West Hollywood Issue](https://github.com/jsla/lunch.js/issues/15) as an example of how to set up a vote system.

**Comment by jarrettch** [comment]
Anyone have recs for lunch? If not then I'll just list 3 places on Sunday or Monday and we can vote.

**Comment by johntran** [comment]
I'm coming to this lunch.js. Sorry for not showing up to the last one, I had a family emergency that day.

I'd be interested in Phorage or [Sol Cocina](http://www.solcocina.com/).

**Comment by johntran** [comment]
Is this happening? @jarrettch

**Comment by ashwell** [comment]
Looks like Phorage won the vote and the Ticket didn't get updated, @jarrettch please confirm and update the main issue with the location.

[I believe this is the location](https://www.google.com/maps/place/ASAP+Phorage/@33.9596271,-118.4478663,15z/data=!4m5!3m4!1s0x0:0x2862fc057eb6382c!8m2!3d33.9596271!4d-118.4478663)

**Comment by jarrettch** [comment]
Is it only you and I @johntran?

**Comment by jarrettch** [comment]
I think I'm gonna cancel this and we can try again next month? @johntran

**Comment by johntran** [comment]
@jarrettch Sounds good! :+1:

**Comment by jarrettch** [comment]
New lunch issue here: [js.la Nov. 1st](https://github.com/jsla/lunch.js/issues/25)
