### ISSUE TITLE
Beverley Hills / West Hollywood - February 5, 2019

### ISSUE THREAD

**Issue by twinfred** [jsla/lunch.js#181]
# Beverly Hills / West Hollywood
### @ TBD

Championed By: Tim Winfred @twinfred

**LOCATION OPTIONS (Voting Open):**
_Leave a comment with the corresponding reaction/emoji to vote_

:+1: [Fatburger](https://goo.gl/maps/kt7UBCEWPGo)
:smile: [Chipotle](https://goo.gl/maps/vdpznWAQ5n32)
:tada: [Lemonade](https://goo.gl/maps/5knKTUP8gHs)
:heart: [Bossa Nova](https://goo.gl/maps/HwTGhtTDamC2)
**Feel free to suggest other locations in the comments.**

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by reactiongears** [comment]
The spots above are a bit small though. I'd like to add these for more room... 
[Johnny Rockets](https://goo.gl/maps/Aeb53Wwp8R32) 🍔 
[Soup Plantation](https://goo.gl/maps/kVpPZiYBycs) 🥗 
[Corner Bakery](https://goo.gl/maps/QmDaBTMLqHD2) 🥖 
[Mandarette](https://goo.gl/maps/16NYv3SoAkH2) 🥘
