### ISSUE TITLE
Thousand Oaks - March 5, 2019

### ISSUE THREAD

**Issue by Zhuochengyu** [jsla/lunch.js#186]
# Thousand Oaks
### @ [Mouthful Eatery](https://www.yelp.com/biz/mouthful-eatery-thousand-oaks)

Championed By:  Chandler Giusti @ChandlerG

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by Zhuochengyu** [comment]
Something came up last minute. I can't attend lunch js this month.

**Comment by ipnicholson** [comment]
I’m here, anyone else coming? 🙏

**Comment by hippee-lee** [comment]
Sorry, I wasn't able to make it this month.

**Comment by ipnicholson** [comment]
I wanted to let everyone know about an upcoming event Thursday evening at Hub101, we're recruiting volunteer mentors for upcoming [high school hackathons](https://www.hackathonbythesea.com/) in Camarillo:

[805 Tech Mentor Network Mixers Flyer.pdf](https://github.com/jsla/lunch.js/files/2933245/805.Tech.Mentor.Network.Mixers.Flyer.pdf)
