### ISSUE TITLE
Culver City / Playa Vista - March 5th, 2019

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#189]
# Culver City/Playa Vista
### @ [Jackson Market and Deli](http://www.jacksonmarketanddeli.com/)

Championed By: Angus @anguspiv 

So this is SUPER last minute, and I realized I was going to be in the area today. So I am going over to Jackson Market to grab some grub and it would be great to meet some folks. 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by maximbert** [comment]
I'll be there.

**Comment by anguspiv** [comment]
I am standing by the checkout waiting for my sandwich, wearing a gray hoodie with REX on the front
