### ISSUE TITLE
Culver City - Oct. 4th, 2016

### ISSUE THREAD

**Issue by jcblw** [jsla/lunch.js#19]
# Culver City
### @ [Phorage](https://www.yelp.com/biz/phorage-los-angeles)

Championed By: Jacob Lowe @jcblw

Hey @machikoyasuda, @markmatney, @marksanghoonkim, @toiye, @jadware ! 👋 

Who has some suggestions on where we should eat! Had a great time at the first one. Hope to see everyone at the next. 🎉

**Comment by machikoyasuda** [comment]
lunch with us @gr2m :) 

i'll go anywhere 🚲 -able in the area.

**Comment by gr2m** [comment]
I’m in :) Thanks for the ping @machikoyasuda

**Comment by machikoyasuda** [comment]
i'll invite @thenounproject peeps too!

**Comment by ryanponce** [comment]
Just moved out here. I'm in.

**Comment by toiye** [comment]
I think Rutts would be amazing, but it's way on the other side of the 405 (still *technically* culver city).  Probably not bike-able though.  What about Phorage (not technically culver city) or Pho Show?  
-Tatsu

    On Tuesday, September 27, 2016 10:10 AM, Ryan Ponce <notifications@github.com> wrote:
 

 Just moved out here. I'm in.—

**Comment by jcblw** [comment]
I do like the idea of Phorage, and Rutts. Both of which are not super bikeable. Phorage is the closer of the two @machikoyasuda it's like 12min bike ride. I can bring my 🚲 that day and we can start a gang.

@gr2m @ryanponce what do y'all think?

**Comment by gr2m** [comment]
I don’t have a bike yet, but I’ll figure out a way to get there, no matter where we end up going

**Comment by machikoyasuda** [comment]
@jcblw lunch.js + bike.js sounds fun to me!!!!!!!

**Comment by ryanponce** [comment]
It's about a 7 minutes bike ride for me. I work at the Platform. Does anyone else?

**Comment by jcblw** [comment]
awesome Phorage it is! super stoked I love that place. @ryanponce you can join our bike gang. I'll teach you the hand shake at lunch. I work in the Helms area so close.

**Comment by marksanghoonkim** [comment]
Hey all! Won't be able to make it this time. Just starting working at my new job and getting used to the work. I'll try to make November's lunch.js!

**Comment by jcblw** [comment]
@marksanghoonkim congrats on the new job 🎉

**Comment by marksanghoonkim** [comment]
@jcblw Thanks!! 😄

**Comment by machikoyasuda** [comment]
@jdorfman come eat with us!!

**Comment by jdorfman** [comment]
Will be there

**Comment by RobAWilkinson** [comment]
I'll be there!

**Comment by jcblw** [comment]
@machikoyasuda @ryanponce bike.js meetup here at 12 to ride to lunch.js?

[<img width="291" alt="screen shot 2016-10-03 at 3 10 03 pm" src="https://cloud.githubusercontent.com/assets/578259/19055969/7f762f16-897b-11e6-9032-022fa7c51cc9.png">](https://www.google.com/maps/@34.0296812,-118.3754018,15z)

**Comment by gr2m** [comment]
okay I don’t have a bike but I’ll be at [Phorage](https://goo.gl/maps/xoTUYNNwQY12) shortly around noon :)

**Comment by ryanponce** [comment]
@jcblw @machikoyasuda I wasn't able to bring my bike today but I'll be there.

**Comment by ryanponce** [comment]
Spoke too soon. Things blew up today. Have fun!

**Comment by jcblw** [comment]
@gr2m @machikoyasuda @toiye @RobAWilkinson @jdorfman great time seeing everyone. Loved talking about open source, and side projects. Hope to see y'all at the next one 💯

**Comment by gr2m** [comment]
It was super nice to meet you all!

@machikoyasuda can you post the picture here or on twitterz?

**Comment by machikoyasuda** [comment]
https://twitter.com/machikoyasuda/status/783450411634077701 @gr2m
