### ISSUE TITLE
Santa Monica - April 2nd 2019

### ISSUE THREAD

**Issue by AlahmadiQ8** [jsla/lunch.js#191]
# Santa Monica

### @ [800 degrees](https://800degrees.com/stores/california/santa-monica/santa-monica/)

Championed By: Mohammad Mohammad - Github: AlahmadiQ8

Hello everyone. I recently moved back to the area and would love to champion 
this upcoming month's lunch for Santa Monica area

### Options

I borrowed these options from last years :D. 

- Flower Child :+1:
- N.Y. & C. Pizza :smile:
- Mendocino Farms :tada:
- 800 Degrees :confused:
- Sweetfin Poke :heart:
- Johnny Rockets :-1:

**Comment by tgreenhalgh** [comment]
I feel weird reacting with 😕 or 👎 
Excited to me everyone, though 😄

**Comment by AlahmadiQ8** [comment]
@tgreenhalgh haha i feel you. 

Looking forward to meet :)

**Comment by tgreenhalgh** [comment]
Looks like two people going to lunch today? Is it still on?

**Comment by mnicole** [comment]
yep! i plan on being there

**Comment by mnicole** [comment]
I don’t see anyone but I’m sitting in the middle kinda near the cashier in the inner section

**Comment by mnicole** [comment]
@tgreenhalgh @AlahmadiQ8 hope to see you next time!

**Comment by AlahmadiQ8** [comment]
@mnicole 
@tgreenhalgh 

I sincerely apologize. I have injured my back two days ago and has to stay home. 

I should have responded earlier. I recently left my last company and github notifications were still routed to my work email, which no longer exists. I just updated my email notifications. 

Again I am very sorry and I hope to see you on the next lunch.
