### ISSUE TITLE
Culver City - April 2nd, 2019

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#192]
### @ [Cava - Culver City](https://www.yelp.com/biz/cava-culver-city)
9343 Culver Blvd,
Culver City, CA 90232

Championed By: Angus Perkerson @anguspiv 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jarrettch** [comment]
I'm free next Tuesday, I think I can make this. Did you not like Jackson Market or did you just randomly use the thumbs down emoji? lol

**Comment by anguspiv** [comment]
Oh, I love Jackson Market, just randomly selected the emojis

**Comment by kapilchokhawala** [comment]
👎🏼

**Comment by anguspiv** [comment]
Guess I am the tie breaker... Cava it is!

**Comment by anguspiv** [comment]
See you guys there at Cava!

**Comment by anguspiv** [comment]
Hey, we are sitting at the large table right inside the door
