### ISSUE TITLE
Los Feliz - April 2, 2019 @ 12:30pm

### ISSUE THREAD

**Issue by laras126** [jsla/lunch.js#193]
# Los Feliz
### @ Alcove

Championed By: Lara @laras126 

I (Lara) am moving back to the east coast April 20 – let's have a last Los Feliz lunch before I go!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by davidguttman** [comment]
I'll be there! I vote for Alcove since it's been so nice out

**Comment by shockey** [comment]
I'll be there!

**Comment by powernerd** [comment]
Awww yeah! Looking forward to it. Alcove works for me.

**Comment by ashwell** [comment]
I hope lunch went well! We'll miss you out here in the west @laras126! 

@powernerd are you good to champion the next lunch? see #195
