### ISSUE TITLE
Thousand Oaks - April 2nd, 2019

### ISSUE THREAD

**Issue by Zhuochengyu** [jsla/lunch.js#194]
### @ [Mouthful Eatery](https://www.yelp.com/biz/mouthful-eatery-thousand-oaks)

Championed By: Zhuocheng Yu @Zhuochengyu 

Didn't see anyone jumping on this so I thought I would though it up quickly. Please Vote below or suggest in the comments a place to go.

**Comment by ChandlerG** [comment]
I'll be there! Sorry for missing the last one :-<

**Comment by ashwell** [comment]
I hope lunch went well! Next lunch will be May 7th see #195
