### ISSUE TITLE
DTLA - May 7th, 2019

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#197]
# DTLA
### @ Modern Times Dankness Dojo, 832 S Olive St

Championed By: Jon Jandoc @jjandoc, Ryan Ponce @ryanponce 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by andyburke** [comment]
Interested, will try to be there work permitting.

**Comment by jjandoc** [comment]
Dankness Dojo is closed for the day! We are moving down the street to Kaffe Baren

**Comment by andyburke** [comment]
Unfortunately schedule didn't work out for me today.  Will keep an eye for the next DTLA lunch.js!

**Comment by uptownhr** [comment]
@jjandoc when's the next one?

**Comment by jjandoc** [comment]
@uptownhr, they're always on the first Tuesday of every month. Hope to see you at the next one!
