### ISSUE TITLE
Valencia / Santa Clarita - May 7th, 2019

### ISSUE THREAD

**Issue by enminc** [jsla/lunch.js#198]
# Valencia / Santa Clarita
### @ _First to join can choose location_

NOTE: If you are even moderately close to the Santa Clarita Valley hit me up and lets see if we can make it work.

Championed By: Adam Smith @enminc

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by ashwell** [comment]
@enminc you already created https://github.com/jsla/lunch.js/issues/196


closing as duplicate
