### ISSUE TITLE
Santa Monica - May 7, 2019

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#199]
# Santa Monica
### @ Santa Monica mall food court

Championed By: michele @mnicole 

*Santa Monica lunch has been a little lonely lately.. comment if you'd come if I make it in other parts of Santa Monica, or if you have any suggestions for location, and I'll update!*

Vote for where you'd like to go by adding an emoji:

❤️ Santa Monica mall food court
😄 Mendocino Farms

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by tgreenhalgh** [comment]
whereever it is, I'll be there this time!

**Comment by tgreenhalgh** [comment]
@mnicole where in the food court will I find you?

**Comment by mnicole** [comment]
i will update once i get there... it's hard to know where there will be free tables. or feel free to post where you are if you get there first!

**Comment by tgreenhalgh** [comment]
Going to be a couple minutes late, but on my way!

**Comment by mnicole** [comment]
It’s pretty nice outside so I’m sitting at the far end of the food court by the ocean view. I’m at a table by the big tree.

**Comment by tgreenhalgh** [comment]
I grabbed a table by the window next to Sensible

**Comment by tgreenhalgh** [comment]
Cool, be there in a couple minutes
