### ISSUE TITLE
Santa Monica - August 2nd, 2016

### ISSUE THREAD

**Issue by davidguttman** [jsla/lunch.js#2]

**Comment by etanlubeck** [comment]
I'm in.

**Comment by machikoyasuda** [comment]
@gr2m might be fun :)

**Comment by machikoyasuda** [comment]
@christinejavier

**Comment by etanlubeck** [comment]
@ashwell you in?

**Comment by gr2m** [comment]
@machikoyasuda would love, thanks for asking, but I’ll be at CascadiaJS :) Next time

**Comment by machikoyasuda** [comment]
@gr2m i forgot! next time :) !!

**Comment by ashwell** [comment]
let's do this!

**Comment by etanlubeck** [comment]
Stout on Santa Monica & Ocean work for everybody?

**Comment by christinejavier** [comment]
Stout works for me! What time will this happen?

**Comment by ashwell** [comment]
totally forgot I have a dentist appointment, I'm not going to make it this month :(

**Comment by etanlubeck** [comment]
Does  Noon work?

**Comment by arjansingh** [comment]
I'm down, are we finalized on "Stout" at noon?

**Comment by etanlubeck** [comment]
@arjansingh yah. I'm headed there now. See you all in a few.

**Comment by christinejavier** [comment]
Hey all, I'm heading over now too. Should be there in a min. Feel free to text when you're there 661-547-4355

**Comment by arjansingh** [comment]
@etanlubeck @christinejavier Yeah sorry I totally bailed when I didn't see a confirmation. Apologies. I'll make next month's for sure. 😄
