### ISSUE TITLE
Santa Monica  - October 4th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#20]
# Santa Monica
### @ [The Curious Palate](https://www.google.com/maps/place/THE+Curious+PALATE/@34.0142224,-118.4934222,15z/data=!4m2!3m1!1s0x0:0xb2d0bf1e3ad83356?sa=X&ved=0ahUKEwje8e_JjLDPAhXB3YMKHTvWANEQ_BIIfjAK)

Championed By: Nate Lubeck @etanlubeck 

😆  [Umami Burger](https://www.google.com/maps/place/Umami+Burger/@34.0166907,-118.4921301,15z/data=!4m2!3m1!1s0x0:0xa95d1a73c8907b53?sa=X&ved=0ahUKEwjv9vz8i7DPAhVM54MKHTsJCqIQ_BIIfzAK)
:heart: [True Food Kitchen](https://www.google.com/maps/place/True+Food+Kitchen/@34.0129657,-118.4944567,15z/data=!4m2!3m1!1s0x0:0xf975f906b7130933?sa=X&ved=0ahUKEwjzm5ikjLDPAhUH0oMKHUhhBroQ_BIIfDAL)
:tada: [The Curious Palate](https://www.google.com/maps/place/THE+Curious+PALATE/@34.0142224,-118.4934222,15z/data=!4m2!3m1!1s0x0:0xb2d0bf1e3ad83356?sa=X&ved=0ahUKEwje8e_JjLDPAhXB3YMKHTvWANEQ_BIIfjAK)

**Comment by mattymess** [comment]
I'm into this idea for sure! Thanks for championing @etanlubeck 👍 

Here's a couple location options...

1. [Umami Burger](https://www.google.com/maps/place/Umami+Burger/@34.0166907,-118.4921301,15z/data=!4m2!3m1!1s0x0:0xa95d1a73c8907b53?sa=X&ved=0ahUKEwjv9vz8i7DPAhVM54MKHTsJCqIQ_BIIfzAK)
1. [True Food Kitchen](https://www.google.com/maps/place/True+Food+Kitchen/@34.0129657,-118.4944567,15z/data=!4m2!3m1!1s0x0:0xf975f906b7130933?sa=X&ved=0ahUKEwjzm5ikjLDPAhUH0oMKHUhhBroQ_BIIfDAL)
1. [The Curious Palate](https://www.google.com/maps/place/THE+Curious+PALATE/@34.0142224,-118.4934222,15z/data=!4m2!3m1!1s0x0:0xb2d0bf1e3ad83356?sa=X&ved=0ahUKEwje8e_JjLDPAhXB3YMKHTvWANEQ_BIIfjAK)

**Comment by anguspiv** [comment]
I'm down, definately a fan of Umami, since its a short walk from the office

**Comment by OlenDavis** [comment]
Forgive the anecdotal data, but Umami may also be the least busy (at least it was during lunch last Friday); True Food tends to be _packed_ at lunchtime (with a party of just two people, I've generally had to wait between 5 and 20 minutes everytime I've gone there, sometimes as late as 2pm).

**Comment by mattymess** [comment]
Yeah, I agree with you that True Food can be kinda packed at lunch time. If anyone else has location ideas, feel free to call it out and I can add to my original comment. We should probably lock down the options at some point though

**Comment by etanlubeck** [comment]
@OlenDavis even at the new location for Umami?

**Comment by etanlubeck** [comment]
I can always call ahead if we have a good headcount. Last month, there was 3 of us at Misfit.

**Comment by etanlubeck** [comment]
😄

**Comment by etanlubeck** [comment]
@gr2m @machikoyasuda

**Comment by gr2m** [comment]
we’ll join [Culver City](https://github.com/jsla/lunch.js/issues/19#issuecomment-250035764) this time :) Thanks for the ping

**Comment by anguspiv** [comment]
Soooo, did we make a desicion on this?

**Comment by etanlubeck** [comment]
Based on the voting... it's The Curious Palate

**Comment by OlenDavis** [comment]
So I'm in, but as a newbie, how should I find you guys?

**Comment by etanlubeck** [comment]
look for a tall dude wearing a github shirt

**Comment by OlenDavis** [comment]
Check. I'll be in a totally nondescript dark grey shirt and brown pants.
(Of all the days _not_ to wear my Steve Buscemi face shirt...)

**Comment by ashwell** [comment]
I've been fighting off a cold the last two days so I have to bow out yet again.

I swear one of these days I'm going to make it.

**Comment by mattymess** [comment]
CEO of our parent company just decided to fly down from SF today. Sadly, I can't get out of here 😢 Hopefully I can make it next month.

**Comment by wykhuh** [comment]
I'll be there.

**Comment by anguspiv** [comment]
Hey Everyone, 
So I opened up a new issue #24 for the November Lunch.js, Start voting on where to go, or suggest new places to try!
