### ISSUE TITLE
Los Feliz - May 7th, 2019

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#200]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2) 🍖 🥗 🥖

Please come join us for lunch and talk about past JS.LA experiences and your ongoing JavaScript projects! Spitz is a cool place, lots of seating and quick service. However, if you prefer another spot speak up!

If you are planning to attend post a comment and let us know!

Championed By: Andy @powernerd and Jon @hah-nan

**Comment by hah-nan** [comment]
Needs champion???

**Comment by hah-nan** [comment]
Ill be there! May 7

**Comment by hah-nan** [comment]
definitely Spitz

**Comment by davidguttman** [comment]
see you soon!
