### ISSUE TITLE
Playa Vista - May 7th, 2019

### ISSUE THREAD

**Issue by maximbert** [jsla/lunch.js#202]
# Playa Vista: May 7th, 2019
### @ Location: Sweetgreen (4718 Admiralty Way, Marina Del Rey)

Championed By: Max @maximbert

Voting options were (voting is now closed):

- :smile: The Tripel (Gastropub - great beers/burgers) - Playa Del Rey
- :tada: Tocaya Organica ("modern Mexican" - great outdoor space) - Playa Vista
- :heart: sweetgreen (make your salad) - Marina Del Rey

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by malinatran** [comment]
seems like the popular choice is the tripel, but @leggomuhgreggo and I would be happy to sponsor everyone's lunch if hosting at sweetgreen MDR :D

**Comment by anguspiv** [comment]
@malinatran Oh snap, you may have changed my vote...

**Comment by maximbert** [comment]
The votes are in and Sweetgreen seems to be the favorite place! Looking forward to meet you all. 

@malinatran can you confirm if this will be sponsored? That would be awesome. And if so, that means we shouldn't order online in advance right? My only concern about Sweetgreen is that this specific location gets very busy, so I'll show up early to have a (hopefully) large table.

**Comment by malinatran** [comment]
Confirming that sweetgreen is sponosoring this meetup! If you know what you'd like, please list your name and order so @leggomuhgreggo and I can order online in advance which will save on waiting time :)

**Comment by skaterdav85** [comment]
The Shroomami is amazing!

**Comment by jarrettch** [comment]
@malinatran @leggomuhgreggo thanks for sponsoring! You're awesome!

**Comment by leggomuhgreggo** [comment]
![Screenshot_20190507-121852](https://user-images.githubusercontent.com/2213636/57327043-c3a75300-70c2-11e9-91d1-2fdc4b437827.png)

**Comment by anguspiv** [comment]
Running a bit late, but we'll see you guys soon

**Comment by maximbert** [comment]
Thanks everyone for coming! And thanks to Sweetgreens for sponsoring. 

![image](https://user-images.githubusercontent.com/454312/57336353-7040ff00-70da-11e9-8e70-0de6f9b8903f.png)
