### ISSUE TITLE
Culver City - June 4th, 2019 🥗

### ISSUE THREAD

**Issue by malinatran** [jsla/lunch.js#204]
# Culver City
### @ [sweetgreen](https://order.sweetgreen.com/culver-city-the-lab/menu)
PLATFORM
8840 Washington Blvd 
Culver City, CA 90232 

Championed By: Malina Tran @malinatran x Greg Westneat @leggomuhgreggo 
Transportation: Expo Line to Culver City, free parking with validation from any PLATFORM business

- Let's meet outside of sg on Washington Blvd
- We can get our food downstairs and dine upstairs in our HQ (4th floor)
- Feel free to comment if you're joining us so we have a head count ❤️

**Comment by skaterdav85** [comment]
Coming! 💚🥗

**Comment by anguspiv** [comment]
I'm in

**Comment by rayning0** [comment]
I've met David (@skaterdav85) before. See you all there!

**Comment by skaterdav85** [comment]
@rayning0 been awhile! see you there!

**Comment by casconed** [comment]
I'll be there!

**Comment by NickMiller11** [comment]
Sounds like fun, I'm in!

**Comment by dgray0229** [comment]
I'm there!

**Comment by hmlauth** [comment]
I'll be there! :)

**Comment by jflopezr11** [comment]
Count me in!

**Comment by jordeguevara** [comment]
+1!

**Comment by simonxcode** [comment]
Going.

**Comment by hermano360** [comment]
going!

**Comment by jesstovar** [comment]
Planning on attending

**Comment by OmarC95** [comment]
Is this open to anyone? And what exactly does this event entail?

**Comment by hmlauth** [comment]
I'll be there!

**Comment by rayning0** [comment]
> Is this open to anyone? And what exactly does this event entail?

Sure. It's for networking, meeting us at sweetgreen, and knowing you in the LA JavaScript community. Nothing beyond that.

**Comment by johntran** [comment]
I'll come to the next one hosted at sweetgreen! I'm super interested in meeting everyone in Culver. I have jury duty that day :(

**Comment by jentoobento** [comment]
I’m coming!

**Comment by acco** [comment]
In!

**Comment by malinatran** [comment]
Thanks everyone! We're going to cap the number of attendees given capacity, but hope to host another one in Culver City soon :) looking forward to meeting everyone.

**Comment by mardb** [comment]
Wait! Let me in!!! One more!

**Comment by OmarC95** [comment]
Hello! I commented earlier on this thread and noticed that there will be a cap on attendees? My question is how do we know if we made the cut?

**Comment by malinatran** [comment]
If @rayning0 or I gave you the 🎉emoji, you're good. We unfortunately have restaurant / office space constraints but we'll host in the future, and would love to have you join us.

**Comment by OmarC95** [comment]
@malinatran Ahhhh okay. I'll be sure to drop by the next time around!

**Comment by malinatran** [comment]
@mardb @OmarC95 we should be able to accommodate if you're able to make it today! :D

**Comment by leggomuhgreggo** [comment]
Updated the issue description with ordering instructions, and the QR code to get the salads hooked up. Here's the [menu link](Culver City Food Lab) for convenience.

**Comment by hermano360** [comment]
Running about 15 min late. Meeting went over

**Comment by hmlauth** [comment]
Parking! Be in when I can find a spot!

**Comment by malinatran** [comment]
Feel free to ping us when you're here via this thread, and we can meet up with you! @hermano360

**Comment by jordeguevara** [comment]
I’m at the elevator, I believe I need a badge to go up

**Comment by hermano360** [comment]
Ok, just walked into restaurant

**Comment by jordeguevara** [comment]
It was great meeting everyone! Thanks to all the sg folks for hosting😊

**Comment by rayning0** [comment]
Sorry I couldn't talk to everyone. Next time, let's try a time before or after 12-1 pm, to avoid the lunch rush. I really enjoyed meeting everyone!

**Comment by anguspiv** [comment]
Next Lunch.js event! https://github.com/jsla/lunch.js/issues/210
