### ISSUE TITLE
Los Feliz - June 4th, 2019

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#205]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2) 🍖 🥗 🥖

Please come join us for lunch and talk about past JS.LA experiences and your ongoing JavaScript projects! Spitz is a cool place, lots of seating and quick service. However, if you prefer another spot speak up!

If you are planning to attend post a comment and let us know!

Championed By: Andy @powernerd and Jon @hah-nan

**Comment by davidguttman** [comment]
I'll be there! (sorry for the late notice)
