### ISSUE TITLE
Hermosa Beach - July 2, 2019

### ISSUE THREAD

**Issue by etnlbck** [jsla/lunch.js#208]
# Hermosa Beach
### @ TBD

Championed By: Nate Lubeck @etnlbck

Alrighty! Vote for where you'd like to consume and converse.

[The Grindz at 1601](https://www.yelp.com/biz/the-grindz-at-1601-hermosa-beach-2) $ :smile:
[Greenbelt](https://www.yelp.com/biz/greenbelt-hermosa-beach) $$ :tada:
[GumTree](https://www.yelp.com/biz/gum-tree-hermosa-beach) $$ :heart:

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by plava** [comment]
Grindz 💵

**Comment by etnlbck** [comment]
thnx @ashwell

**Comment by etnlbck** [comment]
seeing as we're the only two. we'll table this for next month.
