### ISSUE TITLE
November 2016 lunch.js Champion Shout Out

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#21]
## Hey `lunch.js` Champions!
The next first Tuesday of the month is `November 1st, 2016`
Please create new issues when you get the chance.

## Current Champions
Santa Monica - @anguspiv 
Culver City - @machikoyasuda
Playa Vista - @jarrettch 
West Hollywood - @davidguttman
DTLA (Downtown) - @LearningNerd 
SF Valley - @etanlubeck

## Locations with Champions Needed
NONE! :tada:

**Comment by anguspiv** [comment]
@etanlubeck asked me to champion the Santa Monica location? So I opened an issue for that...

**Comment by ashwell** [comment]
thanks @anguspiv! happy to have you on board, if you have any questions feel free to hit me on slack

**Comment by ashwell** [comment]
I forgot to mention! If you wouldn't mind going to last month's issue for your group and making a comment with a link to next month's issue, that will send a notification to everyone that participated in last month's group.

**Comment by jcblw** [comment]
Actually I will not be in the Culver area on the day to day anymore. pinging @machikoyasuda she made the last one amazing. So I think she will probably be taking over that group.

**Comment by ashwell** [comment]
@davidguttman do you need someone to take over the West Hollywood group?

**Comment by ashwell** [comment]
@davidguttman I went ahead and created the West Hollywood ticket for November.

Closing since all existing neighborhoods have tickets now.
