### ISSUE TITLE
Culver City / Playa Vista - July 2nd, 2019 @ 12:00pm

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#210]
# Culver City / Playa Vista - July 2nd, 2019 @ 12:00 PM
### @ [The Triple](https://www.yelp.com/biz/the-tripel-playa-del-rey?osq=Triple)
333 Culver Blvd, Playa Del Rey, CA 90293

Championed By: Angus Perkerson @anguspiv 

Hey Guys, 
I thought I might open this up a little early and put some different options out there for next months Lunch.js! (Me and @maximbert were talking about The Triple in Playa at one point)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by leggomuhgreggo** [comment]
Tender Greens? Are you trying to break my heart @anguspiv? 

💚 💚 💚

**Comment by anguspiv** [comment]
😢 @leggomuhgreggo sorry... I was just trying to change it up a bit....

**Comment by anguspiv** [comment]
Seems lIke triple is the winner, so lets plan to lunch there... maybe a long lunch...

**Comment by jarrettch** [comment]
I'm in!

**Comment by mattrussell36** [comment]
I'd like to come too!

**Comment by anguspiv** [comment]
Come one come all! @mattrussell36

**Comment by jarrettch** [comment]
Turns out I can't make it today. 👎 Sorry! :(

**Comment by kreig303** [comment]
fr1st

**Comment by anguspiv** [comment]
Hey we're sitting up front-end. See you soon!

**Comment by mattrussell36** [comment]
Nice to meet you guys. See at the next one. 👍
