### ISSUE TITLE
Calling all Champions - August 6th, 2019

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#213]
## Hey lunch.js Champions!
The next first Tuesday of the month is **August 6th, 2019**
Please create new issues when you get the chance.

Note that lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

## Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach

pinging previous champions...
@rouzbeh84 @fhwrdh @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @anguspiv @jcblw @davidkim310 @Zhuochengyu @enminc @LearningNerd @stevedorke @jjandoc @jarrettch @billbitt @powernerd @etnlbck 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by claireskim** [comment]
Hello,

Does each location host a lunch.js? Or does one out of the list of neighborhoods get picked?

Warmly,
Claire

**Comment by ashwell** [comment]
Hey Claire ( @claireskim ), this ticket is a reminder to the champions to make tickets for their individual locations. All of the locations listed are places that have had a lunch.js event in the past but some haven't happened recently. Lunch.js happens on the first Tuesday of the month around 12:30pm **in multiple locations around LA.** Hopefully one is near you!

The most active locations are, Culver City / Playa Vista, Santa Monica, DTLA, and Los Feliz. If you are interested in starting a new location or reviving one of the others listed feel free to read the [Champions guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) for more information on being a champion. If you are looking to attend one of the locations keep any eye on the [issues page](https://github.com/jsla/lunch.js/issues) for when the specific lunch locations get set up.

You can look at the [closed tickets](https://github.com/jsla/lunch.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) to see lunch.js events that have happened in previous months.

**Comment by ashwell** [comment]
js.la is tomorrow night, get those lunch issues up so we can promote at the event!

**Comment by mnicole** [comment]
unfortunately i cannot make this next lunch as i'm moving, but i'll be back to making the santa monica one next month!

**Comment by ashwell** [comment]
Lunch.js is tomorrow, be sure to close voting and update your tickets!

**Comment by ashwell** [comment]
Next lunch is in TWO WEEKS sorry for the late notice!

https://github.com/jsla/lunch.js/issues/218
