### ISSUE TITLE
Culver City / Playa Vista - August 6th, 2019 @ 12:30pm

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#214]
### @ [Jackson Market](https://www.yelp.com/biz/jackson-market-culver-city)

Championed By: Angus @anguspiv 

If you are planning to attend subscribe to the issue to get notifications for new comments. Parking is along the street in the neighborhood!

**Comment by maximbert** [comment]
Tocaya Organica (in Playa Vista) is pretty good - it's "Modern Mexican", i.e. vegan/vegetarian twist on Mexican food (but they also have meat/cheese options).

**Comment by mattrussell36** [comment]
Food at [Rasselbock](https://www.rasselbockla.com/) in Mar Vistal looked really tasty. Good beer selection too

**Comment by syd107** [comment]
Right down the street from my house






Sydney Krantz
__________

photo maker + creative
www.skrantz.com
973-851-9895
@seeeyudddd

**Comment by anguspiv** [comment]
Hmm, a lot of these are in the Mar Vista area, rather than the Culver Playa area (Which works great for me since I live in Mar Vista)

I am going to through a couple Culver Options in and start voting. But maybe we should start a Mar Vista group it seems?

**Comment by syd107** [comment]
Culver and MV are so close, don’t think it’s worth it. Plus would like to explore more!






Sydney Krantz
__________

Photographer + Creative
www.skrantz.com
@seeeyudddd

**Comment by jflopezr11** [comment]
Culver- Count me in!

**Comment by anguspiv** [comment]
Rasselback it is! Looking forward to seeing Everyone!

**Comment by syd107** [comment]
No idea what you guys look like, text me when you’re there! 973-851-9895






Sydney Krantz
__________

photo maker + creative
www.skrantz.com
973-851-9895
@seeeyudddd

**Comment by sazhang** [comment]
Hey all, Rasselbock opens Monday to Thursday 4pm-11pm (on their website) / 5:00 pm - 12:00 am (on Yelp) 👀

**Comment by anguspiv** [comment]
Good Catch @sazhang! Well, then its Jackson Market then since its second place. My bad!

**Comment by jarrettch** [comment]
Originally the Culver City and Playa Vista groups were separate. The Playa group was smaller and everyone agreed to join with Culver City at that time, which was always held at Phorage. There's no mandate that they be combined(or that Culver be at Phorage either, of course) so if there is interest in splitting them in the future that's fine.

Also, wish I could make it today but I can't. 😭

**Comment by anguspiv** [comment]
@ashwell @maximbert @dmcneary @acco @jeremiahkonrad @jafong @leggomuhgreggo @mattrussell36 @syd107 @jflopezr11 

Wanted to make sure you guys saw the change in location! Rasselback will not be open for lunch, so we will be going to Jackson Market

**Comment by acco** [comment]
Can't make it any more :( Next time!

**Comment by syd107** [comment]
Sorry guys i have to work! Next time






Sydney Krantz
__________

Photographer + Creative
www.skrantz.com
@seeeyudddd

**Comment by leggomuhgreggo** [comment]
Regrets! Work issue came up which will prevent my attendance 🤕 

Have fun!

**Comment by anguspiv** [comment]
Hey everyone, I'm in a yellow baseball cap, and blue Node shirt. I'm sitting in the back at one of the tables by the pizza oven

**Comment by jeremiahkonrad** [comment]
Nice meeting some of you! Thanks for putting this together and pushing it
over the line Angus! Excited for the next one 👍

**Comment by anguspiv** [comment]
Thanks for coming everyone, hope to see you at the next one!
