### ISSUE TITLE
DTLA - August 6th, 2019 @ 12:30 PM

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#215]
# DTLA
### @ The Stocking Frame, 911 S Hill St, Los Angeles, CA 90015

Championed By: Jon Jandoc @jjandoc

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by sessary** [comment]
Planning on it!

**Comment by jjandoc** [comment]
Looking for the laptop with JS.LA stickers!
