### ISSUE TITLE
Thousand Oaks - August 6th, 2019 @ 12:30pm

### ISSUE THREAD

**Issue by hippee-lee** [jsla/lunch.js#217]
# Thousand Oaks
### @ Urban Plates

350 W Hillcrest Dr
Thousand Oaks, CA  91360
https://urbanplates.com/menu/thousand-oaks/

Championed By: Matt Hippely @hippee-lee

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by Zhuochengyu** [comment]
Hello @hippee-lee, thank you for making this issue. Sorry I have been busy and couldn't keep up with lunch js. I will try my best to be there next week.

**Comment by hippee-lee** [comment]
Hey no worries @Zhuochengyu - I know how it gets. Hope to see you there.

**Comment by Zhuochengyu** [comment]
@hippee-lee Something came up last minute. I probably can’t make it this time.

**Comment by ABitOfKylie** [comment]
Not going to be able to make it. Hope to make it the next time.
