### ISSUE TITLE
SFV - November 1, 2016 @ 12:30pm

### ISSUE THREAD

**Issue by etanlubeck** [jsla/lunch.js#22]
# SF Valley
### @ [Public School 818](https://www.yelp.com/biz/public-school-818-sherman-oaks), 15300 Ventura Blvd, Sherman Oaks, CA 91403

Championed By: Jean-Pierre Barthelemy @jeanpierreb 

:tada: This is the maiden voyage of lunch.js in the SFV. :tada:

I'm curious where people are geographically working in SFV? 
(Otherwise, I'll pick all places in South Valley).

**Comment by etanlubeck** [comment]
I live on the Encino/Sherman Oaks border and propose [Public School 818](https://www.yelp.com/biz/public-school-818-sherman-oaks)

**Comment by jeanpierreb** [comment]
+1 for Public School 818

**Comment by ashwell** [comment]
@jeanpierreb I sent you and invite to join the repo's collaborators list. This will give you the ability to edit the issue with updated location information.

**Comment by sheelah** [comment]
I'm in Sherman Oaks & should also be able to make it.  Public School 818 looks good 👍

**Comment by machikoyasuda** [comment]
@wingedearth hi andrew - you should go & bring your coworkers 🍴 !

**Comment by wingedearth** [comment]
What? Where? I see Nov. 1 at 12:30pm in the subject.

**Comment by wingedearth** [comment]
For a lunch? How about Sagebrush Cantina on Calabasas Ave?

**Comment by jeanpierreb** [comment]
@wingedearth would you be able to make it to PS818 or do you just prefer Sagebrush?

**Comment by etanlubeck** [comment]
@jeanpierreb @wingedearth what's central for everybody? Calabasas is on the far west end. But feel free to open an issue for that neighborhood, if there are more people interested.

**Comment by jeanpierreb** [comment]
We should probably stick to PS818 then.

**Comment by jeanpierreb** [comment]
@etanlubeck @wingedearth @sheelah I'm going to set the location to PS818. Any objections?

**Comment by wingedearth** [comment]
I just looked up PS818 and discovered that it's a gastropub and not an 
actual public school. Hence, I can now see why it would be an 
appropriate location for a lunch.

That being said, I can possibly make it, though Sherman Oaks is quite a 
bit further away from my office in Calabasas, so I would have to wait 
and see how busy the work week is around that time.

Andrew

**Comment by etanlubeck** [comment]
No objections here.

**Comment by wingedearth** [comment]
Is there information/details on this event posted anywhere?

**Comment by etanlubeck** [comment]
@wingedearth for this neighborhood, it's at the top of the thread.  Globally: [lunch.js](https://github.com/jsla/lunch.js)

**Comment by ashwell** [comment]
@wingedearth you're going to have to go to the actual GitHub issue where these comments are showing up, https://github.com/jsla/lunch.js/issues/22

**Comment by machikoyasuda** [comment]
@smeads 
@cdransf
pinging ventura-county/valley-adjacent code friends :) wanna go to lunch in SFV??

**Comment by jeanpierreb** [comment]
Looking forward to lunch!

**Comment by etanlubeck** [comment]
👍

**Comment by remarks** [comment]
👌🏻

**Comment by SeanCox** [comment]
looking forward to meeting you guys!

**Comment by toddzebert** [comment]
I'm in Encino and am a big JS fan... unfortunately Tuesday's at 1 I have a recurring can't miss meeting.

**Comment by etanlubeck** [comment]
@toddzebert bummer. We've got other events that you might be interested in. We had our last js.la meetup of the year this past Thursday night. But the next js.la sponsored event is [NodeSchoolLA](https://nodeschool.io/los-angeles/) this coming Saturday.

**Comment by toddzebert** [comment]
Yeah, I always miss the evening events because Thursday nights don't work for me. 
Saturday I'm going to the Hackaday Conference!

**Comment by etanlubeck** [comment]
Chilling out front on the bench.

**Comment by etanlubeck** [comment]
https://www.slideshare.net/mobile/reed2001/culture-1798664

**Comment by doitlikepruett** [comment]
Great to meet today everyone!

**Comment by jeanpierreb** [comment]
@doitlikepruett @etanlubeck @SeanCox @sheelah
Thank you for an amazing maiden voyage of lunch.js in the SFV!
It was awesome meeting you guys.

Stay in touch and I hope to see all of you at this Saturday's [Node School](https://nodeschool.io/los-angeles/) Meetup
