### ISSUE TITLE
Thousand Oaks - September 3rd, 2019 @ 12:00pm

### ISSUE THREAD

**Issue by hippee-lee** [jsla/lunch.js#220]
# Thousand Oaks
### @ Urban Plates

350 W Hillcrest Dr
Thousand Oaks, CA  91360
https://urbanplates.com/menu/thousand-oaks/

Championed By: Matt Hippely @hippee-lee

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by mrj0** [comment]
Sounds good! I haven't been to a lunch yet but would like to join

**Comment by hippee-lee** [comment]
Sorry for not making the lunch today. I had a medical emergency come up with my daughter and was unable to make it.
