### ISSUE TITLE
Culver City - September 3rd, 2019

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#222]
# Culver City
### @ [Jackson Market](https://yelp.to/qTKq/m1ZwpS13yZ)

Championed By: Angus Perkerson @anguspiv 

Hey guys, sorry for being late for getting this up. Hope people can make and we can pick a new place next time.

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by leggomuhgreggo** [comment]
Lookn forward to this!

**Comment by ultamatt** [comment]
Is it too late to jump in on this?

**Comment by normangilmore** [comment]
Looks like 4 so far...I'll be there.

**Comment by ultamatt** [comment]
Where’s everyone at?

**Comment by leggomuhgreggo** [comment]
@ultamatt Angus and I are here ordering. I'm in jeans and a blue shirt, currently in front of the registers

**Comment by normangilmore** [comment]
Angus, Nicole, Greg, Josh, Daniel, Matt - I appreciated the lively conversation, very nice to meet you all.
