### ISSUE TITLE
Culver City / Palms -- October 1st

### ISSUE THREAD

**Issue by higgins** [jsla/lunch.js#225]
# Culver City / Palms -- October 1st
Hello @jsla! Just moved to the area from the bay and would love to meet y'all.

### @ [Madre Oaxacan Restaurant](https://www.yelp.com/biz/madre-oaxacan-restaurant-and-mezcaleria-los-angeles-6)

Championed By: @casconed

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by casconed** [comment]
🌮

**Comment by anguspiv** [comment]
Edit the emoticons, to track voting. But thanks for getting this going @higgins!

**Comment by higgins** [comment]
Oh geez, I won't be able to make Oct 1st as I need to be out of town. Is anyone else interested in hosting? Still looking forward to meeting y'all at the next event! 🙇

**Comment by casconed** [comment]
I'm down to host especially if we can keep it at Madre

**Comment by higgins** [comment]
excellent! ty @casconed, will see y'all next time

**Comment by anguspiv** [comment]
Hey Everyone, 
Looking forward to seeing you all!

**Comment by casconed** [comment]
Heading over - i've got a beard and a plaid shirt on. I'll try and grab us some table space. See you all there!

**Comment by leggomuhgreggo** [comment]
Work issues cropped up today -- team's on my back -- gutted that I will have to miss -- have a wonderful meal, noble JSers!

**Comment by casconed** [comment]
Small crew today but fun was had nonetheless. Also - fantastic food. Thanks to everyone who came out!
