### ISSUE TITLE
Santa Monica - October 1st, 2019

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#227]
# Santa Monica
### @ [Cava](https://www.yelp.com/biz/cava-santa-monica-2)

Championed By: michele @mnicole 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by amytsao** [comment]
This is great!

**Comment by jcblw** [comment]
Great to see you back at it @mnicole! I going to try to catch this one.

**Comment by jcblw** [comment]
@machikoyasuda @ws @zaach @alyviam @motdotla  Let's go to this.

![bitmoji](https://render.bitstrips.com/v2/cpanel/19849c74-8acd-48f2-82be-93dcfb53950e-a56b94ee-1eb8-4a24-bbab-91513559d340-v1.png?transparent=1&palette=1&width=246)

**Comment by mnicole** [comment]
awesome!! feel free to suggest another place to meet!

**Comment by ylemberg** [comment]
Ooh love Cava. I'll be there! 🥗

**Comment by motdotla** [comment]
I'll be there

**Comment by mnicole** [comment]
Looking forward to seeing everyone in a few hours! I’m wearing a grey shirt and black pants today. I’ll grab my food first and then find a table.

**Comment by jcblw** [comment]
https://github.com/jsla/lunch.js/issues/230 new issue is here
