### ISSUE TITLE
Calling All Champions - November 5th, 2019

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#229]
## Hey lunch.js Champions!
The next first Tuesday of the month is **November 5th, 2019**
Please create new issues when you get the chance.

Note that lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

## Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach

pinging previous champions...
@rouzbeh84 @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @jcblw @davidkim310 @Zhuochengyu @enminc @LearningNerd @stevedorke @jjandoc @jarrettch @billbitt @powernerd @etnlbck @StevenKitzes @higgins @casconed @hippee-lee  @hah-nan

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by fhwrdh** [comment]
Hi @anguspiv, I've moved out of the area and won't be able to help with lunch.js anymore. Would you mind removing me from the previous champs list? Thanks much.

**Comment by anguspiv** [comment]
No Problem @fhwrdh, thanks for helping out while you were around!

**Comment by anguspiv** [comment]
Hey everyone, wanted to follow up with all the champions and make sure everyone can host their Lunch.js next month. Let me know if you can't host it, and I can help you find someone to maybe champion in your stead! Thanks for you help everyone.

**Comment by anguspiv** [comment]
Hey Folks, 
JS.LA is this week! If anyone was thinking about championing a Lunch.js. It would be great to get it up on the issues before we promote it during JS.LA. Let me know if I can help any way or if you have any questions. 

Thanks for all your help!
--Angus

**Comment by anguspiv** [comment]
Hope Everyone had a great lunch!

Special thanks to all the Champions for helping out and organizing their lunches!

Look out for the next Lunch.js shortly!

--Angus
