### ISSUE TITLE
Downtown - November 1st, 2016

### ISSUE THREAD

**Issue by LearningNerd** [jsla/lunch.js#23]
# DTLA
### @ Cole's, 118 E 6th St, Los Angeles, CA 90014

Championed By: Liz Krane @LearningNerd

See you all there! :)

**Comment by ashwell** [comment]
Just so you know @LearningNerd the emoji you have listed are not valid "github reaction" emojis so you'd have to count up all the comments. If you use the ones listed in the issue template then it makes it pretty obvious where the current poll stands. I'll leave it up to you, it's a shame the github reaction emojis are so limiting.

**Comment by jdorfman** [comment]
🌽  or [Coles](https://www.yelp.com/biz/coles-los-angeles-2)

**Comment by LearningNerd** [comment]
I would love to go to Cole's again so I second that! (and added to the list) 🍔

**Comment by matikin9** [comment]
I'm going to be gone that week 😢 , but I hope to make it to the December lunch.

**Comment by kpearson** [comment]
I'm in. I vote Wurstküche or Cole'st

**Comment by tdreitz** [comment]
:hamburger:

**Comment by LearningNerd** [comment]
OK, Cole's it is! Making it official. :) See you all there!

**Comment by jdorfman** [comment]
So excited

**Comment by rouzbeh84** [comment]
Wish I could make it! Have fun!

**Comment by jjcody** [comment]
🍝

**Comment by LearningNerd** [comment]
See you all tomorrow at Cole's at 12:30! :)

**Comment by plantprojects** [comment]
:thumbsup:

**Comment by jdorfman** [comment]
so 🇭🇺

**Comment by ashwell** [comment]
hey DTLA! You're slacking on the new lunch issue! https://github.com/jsla/lunch.js/issues/33

**Comment by jdorfman** [comment]
@ashwell see https://github.com/jsla/lunch.js/issues/33#issuecomment-278104464
