### ISSUE TITLE
Los Feliz - November 5, 2019 at 12:30 PM

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#232]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2) 🍖 🥗 🥖

Championed By: Andy @powernerd and Jon @hah-nan

Please come join us for lunch and talk about past JS.LA experiences and your ongoing JavaScript projects! Spitz is a cool place, lots of seating and quick service. However, if you prefer another spot speak up!

If you are planning to attend post a comment and let us know!

**Comment by powernerd** [comment]
@anguspiv Can you add @hah-nan to the collabs list? He has been Los Feliz co-champion several times in the past.

**Comment by anguspiv** [comment]
Done! Thanks for letting me know @powernerd

**Comment by mimshwright** [comment]
Do we need to RSVP for Lunch.Js?

**Comment by jjandoc** [comment]
I'll be out of town. Catch you all next month.

**Comment by ashwell** [comment]
@mimshwright lunch.js doesn't use an explicit RSVP system. A comment on this ticket is all the RSVP you need

**Comment by davidguttman** [comment]
See you there!

**Comment by Minasokoni** [comment]
I'm down
