### ISSUE TITLE
Westwood/UCLA - November 5th, 2019

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#235]
# UCLA

### 12:30 PM @ Picnic on [Janss Steps Lawn](https://goo.gl/maps/zQWQWGSAueB2)

![image](https://user-images.githubusercontent.com/39992/35835960-8e707cda-0a92-11e8-9641-a85e342b7d4b.png)

Championed By: Gregor @gr2m 

Look out for the [GitHub Student Pack Webpack](https://user-images.githubusercontent.com/39992/35835869-147364b0-0a92-11e8-918b-5af05cb091e6.png)

Bring your own food, there are plenty of food courts around, for example at Ackerman Union or North Campus Student Center. See you there 👋 

I'm excited to meet you all and to learn about your current projects!

If you are planning to attend please comment below (with a short intro, if you like)

**Comment by gr2m** [comment]
So hey I'm Gregor, your host for this lunch.js! I currently cowork from the beautiful UCLA campus with my friend @jimthoburn. I'm working for GitHub on @Octokit! Happy to help out with all your GitHub API/Automation questions!

**Comment by jimthoburn** [comment]
Hooray! 🎉

I’ll be there too, with cookies to share 🍪 @leighphan @scottgruber @markmatney @tinuola

**Comment by DSlatkin** [comment]
Hey all! Excited to be there myself. 😁🙌

**Comment by gr2m** [comment]
If you like, stay before / after the lunch and cowork with @jimthoburn and I on the beautiful UCLA campus! Send me an email to coordinate: lunch.js@martynus.net

**Comment by markmatney** [comment]
📅🏫🥪💻😃

**Comment by gr2m** [comment]
When looking up the stairs, we are in the right side, half in shade on a big blanket

**Comment by gr2m** [comment]
We had @markmatney, @DSlatkin, @jimthoburn, @gr2m and Felicia attending :)

**Comment by gr2m** [comment]
Next lunch is on Dec 3rd!
https://github.com/jsla/lunch.js/issues/238
