### ISSUE TITLE
Woodland Hills - November 5th, 2019

### ISSUE THREAD

**Issue by StevenKitzes** [jsla/lunch.js#236]
# Woodland Hills
### @ The Westfield Topanga food court

6600 Topanga Canyon Blvd Unit FC09, Canoga Park, CA 91303
https://goo.gl/maps/wdGc59jp2iUAJjaS7

Our tradition the last few LunchJSes has been to head to the food court at the Westfield Topanga north complex.  This provides enough options that everyone can find something they like!

I will be the fellow in the outlandishly fuchsia business shirt standing around the Chipotle at 12:15pm.  We can gather to meet, then split up to get whatever food we like, then regroup at a table (my fuchsia shirt will be the happy beacon for all milestones of this project).

If you are planning to attend subscribe to the issue to get notifications for new comments.

Championed By: Steven Kitzes @StevenKitzes

**Comment by anguspiv** [comment]
I'm in!

**Comment by anguspiv** [comment]
I feel horrible about this, but due to a last minute work trip. I am not gonna be able to make it. (They picked the one week!) 

That said, I am getting a few of my co-workers to go still!

**Comment by StevenKitzes** [comment]
No worries at all, Angus!  I've been there.  Hope to see you next time!

**Comment by StevenKitzes** [comment]
Got here a little late but we're here! Find my fucsia shirt!

**Comment by StevenKitzes** [comment]
Great success, with one new face appearing and good times being had all around.  Thanks for joining us!
