### ISSUE TITLE
Westwood/UCLA - December 3rd, 2019

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#238]
# UCLA

### 12:30 PM @ Picnic ~~on [Janss Steps Lawn](https://goo.gl/maps/zQWQWGSAueB2)~~ in Terrace Food Court in the Ackerman building (level 1)

Championed By: Gregor @gr2m 

Look out for the [GitHub Student Pack Webpack](https://user-images.githubusercontent.com/39992/35835869-147364b0-0a92-11e8-918b-5af05cb091e6.png)

Bring your own food, there are plenty of food courts around, for example at Ackerman Union or North Campus Student Center. See you there 👋 

I'm excited to meet you all and to learn about your current projects!

If you are planning to attend please comment below (with a short intro, if you like)

**Comment by gr2m** [comment]
Weather is not looking very favorable for an outside picnic, so we'll meet at the Terrace Food Court in the Ackerman building (level 1)

https://goo.gl/maps/7YDvLw1HTrG3PpPP8

Look for the yellow back pack :)

**Comment by scottgruber** [comment]
See you there.

**Comment by jimthoburn** [comment]
I’ll be there too, with something baked to share 🍪 @leighphan @markmatney @tinuola

**Comment by gr2m** [comment]
@cacheflow is planning on coming, too

**Comment by markmatney** [comment]
I cannot make it this time unfortunately. Next time!

**Comment by gr2m** [comment]
We are outside in the terrace. When you get out, look for the yellow back back to your left
