### ISSUE TITLE
Woodland Hills - December 3rd, 2019 - BYOL!!

### ISSUE THREAD

**Issue by StevenKitzes** [jsla/lunch.js#239]
# Woodland Hills
### @ Warner Center Park

If you are planning to attend, please subscribe to this issue for notifications of new comments.

In anticipation of gentler weather, the usual suspects thought it'd be nice to have an outdoor LunchJS in the West Valley!  Warner Center Park has some tables and benches that make for a Prime Picnic Place (TM).  Grab lunch on your way, or bring something from home, or just come on down to hang out!

As usual, you'll know me by my loud fuchsia shirt.

Here is a precise link to the GPS location of our Prime Picnic Place (TM):
https://goo.gl/maps/3JyrfpGTyv66NBME8

### If the weather takes a turn for the worse, a backup plan will be posted a few days before.

Championed By: Steven Kitzes @StevenKitzes

**Comment by anguspiv** [comment]
For reals this time.... I will be there

**Comment by StevenKitzes** [comment]
Looks like the original plan might get rained out, so I'll post up the back-up plan tomorrow.
@anguspiv it'll be awesome to have you!

**Comment by StevenKitzes** [comment]
Rain prediction was reversed!  BYOL plan at the park is back on!  Planning to meet at the picnic tables near the north side of the park.  I'll wear my traditional Tuesday loud fuchsia shirt.

**Comment by anguspiv** [comment]
Looking forward to seeing everyone!

**Comment by StevenKitzes** [comment]
A wonderful lunch it was!  Thanks to everyone who joined in!!
