### ISSUE TITLE
Santa Monica - November 1st, 2016

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#24]
# Santa Monica
### @ [**Tender Greens**](https://www.google.com/maps/place/201+Arizona+Ave,+Santa+Monica,+CA+90401/@34.0165011,-118.5007253,17z/data=!3m1!4b1!4m5!3m4!1s0x80c2a4c57bc119b9:0x996201e2b674329e!8m2!3d34.0165011!4d-118.4985366)

201 Arizona Avenue. Santa Monica, CA 90401

-----

Championed By: Angus Perkerson @anguspiv

Vote on our location by adding a comment. :) And feel free to suggest another place to eat.

**Umami Burger Santa Monica** :hamburger: (emoji name: hamburger) 
525 Broadway
Santa Monica, CA 90401

**The Curious Palate** :bread: (emoji name: bread) 
395 Santa Monica Place (3rd Floor, near the Arc Light Theater)

**Tender Greens** :leaves: (emoji name: leaves) 
201 Arizona Avenue. Santa Monica, CA 90401

**Comment by ashwell** [comment]
Thanks for picking up the SM lunch group @anguspiv! I sent you an invite to become a collaborator so you can edit the issue, and add updated location information.

**Comment by OlenDavis** [comment]
Ooh, Sweet Greens is also great if Tender Greens is an option!

**Comment by ashwell** [comment]
I always love me some 🍃

**Comment by OlenDavis** [comment]
![woodman](https://cloud.githubusercontent.com/assets/4421318/19696265/44b5fa1a-9a9b-11e6-8bb5-842a20374442.png) 🍃 🍃 🍃 🍃 🍃 🍃 🍃 🍃 🍃 🍃 🍃 🍃 🍃

**Comment by williamsjj** [comment]
Umami. 👍

**Comment by ctsuei** [comment]
🍃

**Comment by lagrz** [comment]
:leaves: +1

**Comment by jcblw** [comment]
🍃 , lets set that as the location seems like it has the most votes and this is tomorrow.

**Comment by anguspiv** [comment]
Beat me to it @jcblw

**Comment by jcblw** [comment]
🤓👍

**Comment by ashwell** [comment]
Great hangout out today!

**Comment by jcblw** [comment]
dito great seeing all of you!

**Comment by anguspiv** [comment]
Hey everyone next Lunch.js is ready for voting
https://github.com/jsla/lunch.js/issues/29
