### ISSUE TITLE
Santa Monica - Dec 3, 2019

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#240]
# Santa Monica
### @ [Gallery Food Hall](https://galleryfoodhall.com/) [[directions](https://www.google.com/maps/place/1315+3rd+Street+Promenade,+Santa+Monica,+CA+90401/@34.016784,-118.4968282,17z/data=!4m2!3m1!1s0x80c2a4cf99964625:0xf3c63a371c2bb4e0)]

Let's go to Gallery food hall again unless anyone has any suggestions. But that seemed to work as there are a lot of options and seating. I'll try to get there early and scope out a place to sit and update the ticket with where (probably upstairs, and outside depending on the weather).

Championed By: Michele @mnicole

If you are planning to attend react, comment, or subscribe to the this ticket.

**Comment by jcblw** [comment]
🙌 yep I like the last one here.  I think we need to wear colorful hat or something so no one misses out!

**Comment by mnicole** [comment]
hi, hoping to see you at lunch js today! i'm wearing a light purple dress today and a grey sweater. i'll hang out by the entrance for a bit, but if you arrive late, i'll prob be getting tacos again and then finding a table upstairs.
