### ISSUE TITLE
Los Feliz - Dec 3, 2019

### ISSUE THREAD

**Issue by andysaman** [jsla/lunch.js#241]
# Los Feliz
### @ [Spitz](https://www.yelp.com/biz/spitz-los-feliz-los-angeles-2) 🍖 🥗 🥖

Championed By: Andy @powernerd and Jon @hah-nan

Please come join us for lunch and talk about past JS.LA experiences and your ongoing JavaScript projects! Spitz is a cool place, lots of seating and quick service. However, if you prefer another spot speak up!

If you are planning to attend post a comment and let us know!

**Comment by hah-nan** [comment]
Ill b there!

**Comment by jjandoc** [comment]
I'll be there.

**Comment by blackflame007** [comment]
How long do these last for usually?

**Comment by jjandoc** [comment]
@blackflame007 usually an hour or less.

**Comment by catmclough** [comment]
I will be there!

**Comment by hqtsky** [comment]
will be there maybe late depending on if my guest is coming along

**Comment by hqtsky** [comment]
did not mean to show up and not converse with the bigger group! But i just realize that I can host the next one at our onsite restaurant at secondhome.io :)

**Comment by andysaman** [comment]
That was a great lunch, thanks for coming everyone! See some of you again on Saturday at JS.SOIREE https://js.la/
 🎉
