### ISSUE TITLE
DTLA - January 7th, 2020 

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#243]
# DTLA
### @ The Stocking Frame
Championed By: Angus @anguspiv 

[The Stocking Frame](https://www.yelp.com/biz/the-stocking-frame-los-angeles)

If you are planning to attend subscribe to the issue to get notifications for new comments.

Hey Everyone,
To help DTLA to get back up and running I'll go ahead and champion this one, but I'll be looking for someone to help champion Downtown. If you're interested at all or just curious about how lunch.js works, well stop on by and talk to me about it! Or Just talk to me about anything!

Looking forward to meeting everyone!
--Angus

**Comment by jjandoc** [comment]
Yay! I think I'll be at this one for some moral support.

**Comment by ryanponce** [comment]
I can make it to this one too. I recently moved to the Arts District so it's a little bit of a trek. Do you think it would be too much to have a separate one here in the Arts District?

**Comment by anguspiv** [comment]
Hey Everyone, I'm here in a black shirt with yellow logo... But of course wearing a hoodie
