### ISSUE TITLE
Los Feliz / Hollywood January 7th, 2019

### ISSUE THREAD

**Issue by hqtsky** [jsla/lunch.js#244]
# Loz Felix / Hollywood
### @ St. Andrew's Place Restaurant at Secondhome.io/hollywood

Championed By: Hq Tran @hqtsky

St. Andrew's Place Restaurant at [Secondhome.io/hollywood](https://Secondhome.io/hollywood)
1370 N. St. Andrew's Place
Los Angeles, CA 90028

**Comment by hqtsky** [comment]
not quite the word's most user friendly editing interface :)

**Comment by Minasokoni** [comment]
ill be there

**Comment by thommeredith** [comment]
Count me in!

**Comment by jangelon** [comment]
See you there, it's a cool space!

**Comment by hqtsky** [comment]
How do i add the 'lunch.js' label to this issue? Do i need repo access?

**Comment by anguspiv** [comment]
> How do I add the 'lunch.js' label to this issue? Do I need repo access?

Hey @hqtsky. Yes, you do need write permissions, so I just gave them to you! You should see an invite in your email now. 

Thanks for the help!

**Comment by temojin** [comment]
Thank you Angus! I will label responsibly :)

**Comment by hqtsky** [comment]
For anyone coming tomorrow, this location is a restaurant inside a new coworking space. I was told that it is open to the public but just in case when you walk to the front desk. Let them know you are meeting "hung tran (with narrate)" at St. Andrew's Restaurant. I will hang loose in that area for attendees.

**Comment by davidguttman** [comment]
just arrived!
