### ISSUE TITLE
Burbank - Jan 7th, 2020

### ISSUE THREAD

**Issue by andysaman** [jsla/lunch.js#247]
# Burbank
### @ [Guisados Burbank](https://www.yelp.com/biz/guisados-burbank-2)

A new location just added!

Jon and Andy have hosted the Lunch.JS in the Los Feliz area for some time now, and we're moving over to Burbank! We hope to see some friendly new faces. Let's get together in a new setting to chat about our JavaScript projects and career advancement in software engineering!

Championed By: Andy @powernerd and Jon @hah-nan

If you are planning to attend subscribe to the issue to get notifications for new comments. And don't forget to vote for the next location.

**Comment by hah-nan** [comment]
Where should we go

**Comment by andysaman** [comment]
Will tally the votes by the end of the day. Right now, Quisados has 4 votes, Simmzy's has two votes.

**Comment by andysaman** [comment]
Guisados
**Address:** 312 N San Fernando Blvd, Burbank, CA 91502

**Comment by toiye** [comment]
https://wattenberger.com/blog/react-hooks

**Comment by powernerd** [comment]
Thanks all, it was a great lunch! Hope to see you again next month.
