### ISSUE TITLE
Westwood/UCLA - January 7th, 2019

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#248]
# UCLA

### 12:30 PM @ Picnic at [Court of Sciences](https://goo.gl/maps/bxyB5bdSmfQABq777)

Championed By: Gregor @gr2m 

Look out for the [GitHub Student Pack Webpack](https://user-images.githubusercontent.com/39992/35835869-147364b0-0a92-11e8-918b-5af05cb091e6.png)

Bring your own food, there are plenty of food courts around. See you there 👋 

I'm excited to meet you all and to learn about your current projects!

**Comment by jimthoburn** [comment]
I’ll be there too, with something baked to share 🍪🧁 @leighphan @scottgruber @markmatney @tinuola

**Comment by tinuola** [comment]
I have a lunch meeting today. I'll see you at the next lunch.js.
Enjoy!

@gr2m @jimthoburn

**Comment by gr2m** [comment]
I scored a table for us, exactly here: https://goo.gl/maps/wDVLgnreBDufL1H96. Look for [the yellow GitHub Student Pack Webpack](https://user-images.githubusercontent.com/39992/35835869-147364b0-0a92-11e8-918b-5af05cb091e6.png) See y'all soon!

**Comment by markmatney** [comment]
o noes, just saw this, next time!
