### ISSUE TITLE
Burbank - February 4th, 2020

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#249]
# Burbank
### @  [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)

Championed By: Andy @powernerd  and Jon @hah-nan

Let's get together to chat about our JavaScript projects and career advancement in software engineering!

Possible Locations:
🚀 Option 1 - [Guisados Burbank](https://www.yelp.com/biz/guisados-burbank-2)
👀 Option 2 - [Pizza Pazza Burbank](https://www.yelp.com/biz/pizza-pazza-wood-fired-pizza-burbank-2)
🎉 Option 3 - [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)
(vote by clicking an emoji on this issue)

Past Lunch Issues:
https://github.com/jsla/lunch.js/issues/247 @ [Guisados Burbank](https://www.yelp.com/biz/guisados-burbank-2)

If you are planning to attend subscribe to the issue to get notifications for new comments.
Also, join us on Slack: https://js.la/slack #lunchjs

**Comment by plantprojects** [comment]
I vote for Guidados

**Comment by anguspiv** [comment]
Just sliding in here... but if someone ends up eating their super spicy taco... I request before and after pictures.

**Comment by powernerd** [comment]
> Just sliding in here... but if someone ends up eating their super spicy taco... I request before and after pictures.

Poor @hah-nan was eating one and suffering in silence through a good portion of the lunch. What a trooper

**Comment by hah-nan** [comment]
lol it was as spicy as I was warned but I did not listen

**Comment by toiye** [comment]
I'm in.  Down with wherever.

**Comment by powernerd** [comment]
@plantprojects 
> I vote for Guidados
Please use the 🚀 above. Voting now open

**Comment by lemazza** [comment]
So is it officially storybook?

**Comment by powernerd** [comment]
See you at  [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)

**Comment by powernerd** [comment]
Pretty great turnout today (10), thanks to all who came! Be sure to catch the next one here: https://github.com/jsla/lunch.js/issues/253
