### ISSUE TITLE
Playa Vista - November 1st, 2016

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#25]
# Playa Vista
#### 12150 Millennium Dr #101, Los Angeles, CA 90094

Championed By: Jarrett Harris @jarrettch

**Comment by derduher** [comment]
Here's a couple: chicken or the egg, ROC kitchen, SOL

**Comment by MalcolmGC** [comment]
Not sure how to vote. ROC sounds good.

**Comment by jarrettch** [comment]
Chicken or the Egg won 3 votes to 1, so we will be there. I'll try to get there a little before 12:30. Will be wearing a blue Nativescript/Angular t-shirt.
