### ISSUE TITLE
February 2020 - Calling all Champions!

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#250]
## Hey lunch.js Champions!
The next first Tuesday of the month is **February 4th, 2020**
Please create new issues when you get the chance.

Note that lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

## Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach

pinging previous champions...
@rouzbeh84 @leggomuhgreggo @mnicole @meganmcgeee @aaroncraigongithub @jcblw @davidkim310 @Zhuochengyu @enminc @LearningNerd @stevedorke @jjandoc @jarrettch @billbitt @powernerd @etnlbck @StevenKitzes @higgins @casconed @hippee-lee  @hah-nan

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by anguspiv** [comment]
Sorry guys, little late on this one! But lets get those issues open!

**Comment by anguspiv** [comment]
Hey everyone, I just wanted to call out that JS.LA is next week and hopefully, I will get to chat with y'all there. 

If you have a chance, let's get some more Lunch.js events up beforehand so new people can see them when we promote it next week!

Thanks, Everyone!

**Comment by MrAlexWeber** [comment]
Better late than never, I've created https://github.com/jsla/lunch.js/issues/252 for Westwood.

**Comment by anguspiv** [comment]
Thanks again for all your help guys! Go Lunch.js!
