### ISSUE TITLE
Westwood - February 4, 2020

### ISSUE THREAD

**Issue by MrAlexWeber** [jsla/lunch.js#252]
# Westwood
### Vote for a location!

I suggest either [TLT Food](https://www.yelp.com/biz/tlt-food-los-angeles) or [Cava](https://www.yelp.com/biz/cava-los-angeles-5)
Vote with emoji reactions:
* Use 👍 for TLT
* Use ❤️  for Cava
* If it's a tie, the default will be TLT.

Championed By: Alex Weber @MrAlexWeber
~~I'll be wearing a grey trucker cap that says "Hackers Gonna Hack" on it, and probably a black shirt.~~
Edit: I've got a schedule conflict this month, but the meetup will still happen.

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by MrAlexWeber** [comment]
Just realized I've got a schedule conflict. I won't be able to host this event, but will try again next month.

**Comment by anguspiv** [comment]
Hey @MrAlexWeber you can still Champion the event if you want, even if you can't make it. All you need to do really at this point is just manage the issue and voting.

**Comment by MrAlexWeber** [comment]
Alright, sounds good. I'll remotely champion this event 😄

**Comment by gr2m** [comment]
@jimthoburn and I will be there :)

**Comment by shiningjustice** [comment]
I'm here! In a white jacket. Not sure who is here from Js.la

**Comment by quasarwei** [comment]
We're sitting at the end of the long yellow table

**Comment by shiningjustice** [comment]
We moved to the green table in the front by the window!

**Comment by gr2m** [comment]
sorry Jim had to go somewhere else for lunch and I totally lost the count of time. Would you like to meet for a coffee at [Profeta](https://goo.gl/maps/GXvWk3ooLq5DPcHYA)? I could be there in 15min
