### ISSUE TITLE
Burbank - March 3rd 2020 (Super Tuesday Edition)

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#253]
# Burbank
### @ [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)

Championed By: Andy @powernerd  and Jon @hah-nan

Let's get together to chat about our JavaScript projects and career advancement in software engineering!

Possible Locations:
🚀 Option 1 - [Pizza Pazza](https://www.yelp.com/biz/pizza-pazza-wood-fired-pizza-burbank-2)
👀 Option 2 - [Guisados Burbank](https://www.yelp.com/biz/guisados-burbank-2)
🎉 Option 3 - [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)

Past Lunch Issues:
https://github.com/jsla/lunch.js/issues/247 @ [Guisados Burbank](https://www.yelp.com/biz/guisados-burbank-2)
https://github.com/jsla/lunch.js/issues/249 @ [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)

If you are planning to attend subscribe to the issue to get notifications for new comments.
Also, join us on Slack: https://js.la/slack #lunchjs

**Comment by StevenKitzes** [comment]
I work too far to join, but love Burbank and recommend Story Tavern on San Fernando. I also love Barney's (though they're slow and a bit loud). Tony's Darts Away is nearby and has *excellent* vegan and non-vegan offerings, especially gourmet sausages

**Comment by toiye** [comment]
I'm.  I'll suggest Pizza Pazza as a location.

**Comment by powernerd** [comment]
We have three choices on locations and voting is open! Please vote by using the corresponding emoji on the original post above.

**Comment by powernerd** [comment]
Location set to [Story Tavern Burbank](https://www.yelp.com/biz/story-tavern-burbank)!

cc: @Arshavin86 @LonelyTree @plantprojects @toiye @BMyung @hah-nan

**Comment by powernerd** [comment]
Thanks to all who came to lunch! See you again soon.
