### ISSUE TITLE
NELA - March 3rd, 2020

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#255]
# Northeast Los Angeles (Highland Park, Glassell Park, Cypress Park, Eagle Rock, Atwater, etc)
### @ [The York](https://www.yelp.com/biz/the-york-los-angeles), 5018 York Blvd

Championed By: Jon Jandoc, @jjandoc 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by lemazza** [comment]
Some location ideas: Highland Cafe, Zweet, Cacao

**Comment by feemcgill** [comment]
Interested!

**Comment by jjandoc** [comment]
Setting the location to The York as it's central-ishly located and has a patio if people are feeling outdoorsy.

**Comment by jjandoc** [comment]
Headed up! I'll be the guy in an Elizabeth Warren hoodie and a laptop with an "I Voted" sticker
