### ISSUE TITLE
Burbank - (Cancelled)

### ISSUE THREAD

**Issue by powernerd** [jsla/lunch.js#259]
# Burbank - Cancelled

This lunch has been cancelled due to the COVID-19 outbreak in Los Angeles. For anyone who wants to join the online version of Lunch JS, here is the link: https://github.com/jsla/lunch.js/issues/263

**Comment by powernerd** [comment]
@hah-nan Can you organize this one? I will be transitioning to another project and will likely not be in the area.

**Comment by hah-nan** [comment]
@powernerd hello everyone yes I will be there to champion the lunch please vote on lunch spot

**Comment by MrNanosh** [comment]
Guisados! that place is delish.

**Comment by powernerd** [comment]
This lunch has been cancelled due to the COVID-19 outbreak in Los Angeles. For anyone who wants to join the online version of Lunch JS, here is the link: https://github.com/jsla/lunch.js/issues/263
