### ISSUE TITLE
Woodland Hills - April 7, 2020

### ISSUE THREAD

**Issue by StevenKitzes** [jsla/lunch.js#262]
# Update
### Regarding the COVID-19 pandemic

The js.la organizers have deemed the threat of COVID-19 infection to be a serious threat to our health and safety.  They have left the continuation of LunchJS events up to the discretion of the individual lunch champions.  I am personally unwilling to risk this kind of illness to anyone via a js.la event.  I’m therefore very sad to report that this coming April’s LunchJS in Woodland Hills is hereby cancelled.  I'm playing with the possibility of an online substitute this month, such as a Google Hangout or other alternative, because I love meeting and chatting with you all.  Stay tuned for further updates, and thank you for your understanding.  Please be safe out there, and take care of yourselves!

# 

Woodland Hills
Next lunch is Tuesday, April 7, 2020 at 12:15 PM
~@ Vote for location in the comments!!~

~We've done the park several times in a row.  Let's try something new!  Vote for one of these in the comments:~

~1. [Urban Plates](https://www.yelp.com/biz/urban-plates-woodland-hills)~
~2. [Downtown Philly Cheese Steaks](https://www.yelp.com/biz/downtown-philly-cheese-steaks-woodland-hills-2)~
~3. [Westfield Topanga Mall Food Court](https://www.westfield.com/topanga/stores/all-stores/fooddrink)~

Championed By: Steven Kitzes @StevenKitzes 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by matthewdlw** [comment]
Urban Plates for me, nice place, lots of healthy options, usually lots of seating and if there's not enough seating I could use the exercise.  :D
