### ISSUE TITLE
Online - April 7, 2020

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#263]
# Online
### @ [Zoom](https://rexhomes.zoom.us/j/559744404?pwd=eXA5UEJnV0ZSVWQ1V1hHTzJnUEtnQT09)

Championed By: Jon Jandoc @jjandoc

I'm betting that things are still going to be shut down at this point. So instead, grab a lunch and turn on your web cam. Let's hang out. It'll probably be chaos but let's give it a shot anyways.

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by lemazza** [comment]
cool idea! Looking forward to watching your talk on 3/26

**Comment by uptownhr** [comment]
will be there

**Comment by anguspiv** [comment]
@jjandoc do you have the zoom link for this yet?

**Comment by jjandoc** [comment]
Does anyone here have a paid Zoom account? I only have a basic one with a 40-minute limit.

**Comment by MrNanosh** [comment]
unfortunately, I do not

**Comment by anguspiv** [comment]
I've Gotcha, my work has zoom. Let me get an invite going.... give me a few minutes, and I'll reply with the link

**Comment by MrNanosh** [comment]
yaay

**Comment by anguspiv** [comment]
Sadly, I have a 1:30pm Meeting.... but I think you guys can continue on without me. Heads up though this is my work provided Zoom... just so people are aware for whatever reason they should be.

Angus Perkerson is inviting you to a scheduled Zoom meeting.

Topic: Lunch.js Virtual Lunch
Time: Apr 7, 2020 12:30 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://rexhomes.zoom.us/j/559744404?pwd=eXA5UEJnV0ZSVWQ1V1hHTzJnUEtnQT09

Meeting ID: 559 744 404
Password: 037327

One tap mobile
+16699006833,,559744404# US (San Jose)
+13462487799,,559744404# US (Houston)

Dial by your location
        +1 669 900 6833 US (San Jose)
        +1 346 248 7799 US (Houston)
        +1 253 215 8782 US
        +1 301 715 8592 US
        +1 312 626 6799 US (Chicago)
        +1 646 558 8656 US (New York)
        877 853 5247 US Toll-free
        888 788 0099 US Toll-free
Meeting ID: 559 744 404
Find your local number: https://rexhomes.zoom.us/u/ackqTozxNs

Join by SIP
559744404@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
221.122.88.195 (China)
115.114.131.7 (India Mumbai)
115.114.115.7 (India Hyderabad)
213.19.144.110 (EMEA)
103.122.166.55 (Australia)
209.9.211.110 (Hong Kong)
64.211.144.160 (Brazil)
69.174.57.160 (Canada)
207.226.132.110 (Japan)
Meeting ID: 559 744 404
Password: 037327

**Comment by MrNanosh** [comment]
Thanks Angus!

**Comment by azmartone** [comment]
```
const isTrianglePossible = (a, b, c) => {
    const longest = Math.max( a, b, c )
    const sides = a + b + c - longest
    return longest < sides
}
```

**Comment by uptownhr** [comment]
Nice! I didn't know about Math.max. Learning something new :)
