### ISSUE TITLE
Virtual / On-Line - May 5th, 2020

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#264]
# Virtual / On-Line
### @ Virtual / On-Line Zoom

Championed By: @anguspiv 

Hey Everyone,
Since @jjandoc online lunch.js went so well WE'RE GONNA DO IT AGAIN!!!!!

The day of, I will add a link to the video conference that everyone can use.
If we got a large group, I will split the groups into smaller meetings for people to chat in, (and figure that out on the fly)

Looking forward to seeing everyone!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by anguspiv** [comment]
Hey everyone, I'll post a zoom link here, a little closer to 12:00pm. Looking forward to chatting with you guys!

**Comment by MrNanosh** [comment]
Oh cool, Almost forgot.

**Comment by anguspiv** [comment]
Angus Perkerson is inviting you to a scheduled Zoom meeting.

Topic: Lunch.JS
Time: May 5, 2020 12:15 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://rexhomes.zoom.us/j/97651572981?pwd=ZENmN0JxRGgwdk5JcW9MZ2pCN2l0Zz09

Meeting ID: 976 5157 2981
Password: 011990
One tap mobile
+16699006833,,97651572981# US (San Jose)
+13462487799,,97651572981# US (Houston)

Dial by your location
        +1 669 900 6833 US (San Jose)
        +1 346 248 7799 US (Houston)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 646 558 8656 US (New York)
        888 788 0099 US Toll-free
        877 853 5247 US Toll-free
Meeting ID: 976 5157 2981
Find your local number: https://rexhomes.zoom.us/u/acFfG9hISg

Join by SIP
97651572981@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
213.19.144.110 (EMEA)
103.122.166.55 (Australia)
69.174.57.160 (Canada)
Meeting ID: 976 5157 2981
Password: 011990
