### ISSUE TITLE
Virtual Lunch.js - June 2nd, 2020

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#265]
# Virtual / On-Line
### @ Virtual / On-Line Zoom

Championed By: @anguspiv 

Hey Everyone,
Even though we can't meetup in person, we can still chat and share a meal over the power of video conferencing! That said this is an opportunity to check in and chat with your fellow Javascripters, and share knowledge with each other. All are welcome and encouraged to attend, if anything just to listen in the background.

The day of, I will add a link to the video conference that everyone can use.
If we got a large group, I will split the groups into smaller meetings for people to chat in, (and figure that out on the fly)

Looking forward to seeing everyone!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by MrNanosh** [comment]
see you guys in a few!

**Comment by anguspiv** [comment]
Hey Everyone, for this addition we are going to use talkworld again by the fabulous @davidguttman 
You can use the following link:
[https://talkworld.js.la/]()

**PLEASE make sure you are using headphones to prevent echo**

**Comment by MrNanosh** [comment]
The link appears to bring me back to this page for some reason.

**Comment by StevenKitzes** [comment]
> The link appears to bring me back to this page for some reason.

The URL is good.  Try pasting it into your browser.

**Comment by anguspiv** [comment]
> The link appears to bring me back to this page for some reason.

Sorry about that, just updated the link... apparently my markdown fu is bad

**Comment by MrNanosh** [comment]
yea @StevenKitzes  I did resort to that.
