### ISSUE TITLE
Lunch.JS Online - August 4th, 2020 @ 12:30pm

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#267]
Virtual / On-Line
Next lunch is Tuesday, August 4th, 2020 at 12:30 PM
@ Virtual / On-Line
Championed By: @anguspiv

Hey Everyone,
Even though we can't meet up in person, we can still chat and share a meal over the power of video conferencing! That said this is an opportunity to check-in and chat with your fellow JavaScripters, and share knowledge with each other. All are welcome and encouraged to attend if anything just to listen in the background.
Looking forward to seeing everyone!

You will be able to talk and join us at [http://ramb.ly/lunch.js]()

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by StevenKitzes** [comment]
I'll be there.  Rambly is always a good time!  :D  Throwing up a Tweet for it today.

**Comment by MrNanosh** [comment]
I totally forgot last time. I'll add it to my calendar this time

**Comment by leggomuhgreggo** [comment]
I'm in!

**Comment by anguspiv** [comment]
Looking forward to next week to chat with y'all!

**Comment by StevenKitzes** [comment]
Scheduling a Twitter reminder for tomorrow morning!  Get them lunchers lunchin'!

**Comment by anguspiv** [comment]
Thanks everyone for joining, it was great talking to you all! 
Hey and feel free to go ahead and mark the next Lunch.js in your calendars, or reply here:
https://github.com/jsla/lunch.js/issues/268

You guys are awesome!
