### ISSUE TITLE
West Hollywood - November 1st, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#27]
# West Hollywood
### @ [The Carving Board](https://www.yelp.com/biz/the-carving-board-los-angeles)

Championed By: David Guttman @davidguttman

RSVP in comments!

**Comment by ashwell** [comment]
@davidguttman I know you have been crazy busy, does @mrsmuneton want to take over as champion?

**Comment by Rrrapture** [comment]
May I suggest a few? 

These two are on the weho/hollywood border:

1. The Carving Board
7300 Sunset Blvd
Hollywood
Los Angeles, CA 90046
(323) 845-4550

https://www.yelp.com/biz/the-carving-board-los-angeles

2. Bossa Nova on Sunset
7181 W Sunset Blvd
Hollywood
Los Angeles, CA 90046
(323) 436-7999

https://www.yelp.com/biz/bossa-nova-brazilian-cuisine-los-angeles-4

3. In Hollywood:
Luv2Eat Thai Bistro
6660 W Sunset Blvd
Unit P
Hollywood
Los Angeles, CA 90028
(323) 498-5835

https://www.yelp.com/biz/luv2eat-thai-bistro-los-angeles

**Comment by temojin** [comment]
When is this? I will try to attend

**Comment by Rrrapture** [comment]
@temojin it's above in the issue name/subtitle:

Next lunch is Tuesday, November 1st, 2016 at 12:30 PM

**Comment by davidguttman** [comment]
@Rrrapture Carving Board looks awesome, great suggestion!

cc: @maytaldahan @krainboltgreene

**Comment by temojin** [comment]
very cool! I will be there!

**Comment by Rrrapture** [comment]
great! Looking forward to it.

**Comment by lmordell** [comment]
I'll be there, looking forward to meeting you all!

**Comment by lsfisher** [comment]
I'll be there, looking forward to meeting you all!

**Comment by temojin** [comment]
sadly I will not be able to attend this one due to a work related conf call.

**Comment by lmordell** [comment]
Sorry for the late notice, won't be able to make it today :(

**Comment by Rrrapture** [comment]
Hey all, anyone else here yet? I'm wearing a blue tunic. - Rachelle

**Comment by davidguttman** [comment]
Great lunch! Hope to see everyone next time!
