### ISSUE TITLE
Lunch.js - December 1st, 2020 @ 12:30pm

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#271]
# [Ramb.ly/lunch.js](http://ramb.ly/lunch.js)
### Next lunch is Tuesday, December 1st, 2020 at 12:30 PM

Championed By: Angus Perkerson @anguspiv 

Hey Everyone,
Even though JS.LA talks are done for the year, Lunch.JS still keeps going strong through the holidays. So feel free to come and join us!

Even though we can't meet up in person, we can still chat and share a meal through the power of the internet! 
This is an opportunity for you to check-in and chat with your fellow JavaScripters, and share your knowledge with each other. All are welcome and encouraged to attend; from Juniors to Seniors!
Looking forward to chatting with everyone!

You will be able to talk and join us at [http://ramb.ly/lunch.js](http://ramb.ly/lunch.js)

And please remember to use headphones to help prevent feedback and echo!

**Comment by StevenKitzes** [comment]
Always a great time!  I'll be there!

**Comment by hqtsky** [comment]
add me as tenative pls

**Comment by anguspiv** [comment]
Just wanted to remind everyone that we all soon gather together around to eat and share everything we’ve learned this year, and what we’re thankful for. Me, I am very grateful for React Hooks, and Optional Chaining! Yes I’m talking about the last Lunch.js of the Year this December 1st. So please join us at ramp.ly/lunch.js at 12:30pm that day and share what you’re thankful for!
(What is something else going on this week?)

**Comment by anguspiv** [comment]
> add me as tenative pls

@hqtsky its very informal, so no need to reserver a spot. But looking forward to seeing you there, and thanks for the reply!

**Comment by hqtsky** [comment]
Great, yes I'd like to join you!

**Comment by anguspiv** [comment]
Good morning everyone looking forward to chatting with y'all today! 12:30 PM PST @ ramb.ly/lunch.js
