### ISSUE TITLE
Virtual / Ramb.ly - Tuesday, January 5th, 2021 at 12:30 PM

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#272]
Ramb.ly/lunch.js
Next lunch is Tuesday, January 5th, 2021 at 12:30 PM
Championed By: Angus Perkerson @anguspiv

Hey Everyone,
Well, it's a New Year, and time for another Virtual Lunch.js! 

Even though we can't meet up in person, we can still chat and share a meal through the power of the internet!
This is an opportunity for you to check-in and chat with your fellow JavaScripters, and share your knowledge with each other. All are welcome and encouraged to attend; from Juniors to Seniors!
Looking forward to chatting with everyone!

You will be able to talk and join us at http://ramb.ly/lunch.js

And please remember to use headphones to help prevent feedback and echo!

**Comment by samriddhi** [comment]
Are these recorded? Or someplace we can see what was talked about?

**Comment by anguspiv** [comment]
@samriddhi no, we don't record the Lunch.JS events. The event is more casual conversations with people in the community, similar to our slack but live!

**Comment by anguspiv** [comment]
Thanks everyone for showing up, there was a really great turnout, and I am hoping to see you at the next one in February!
