### ISSUE TITLE
Virtual / Ramb.ly - Tuesday, February 2nd, 2021 at 12:30 PM

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#273]
# Ramb.ly/lunch.js
# Next lunch is Tuesday, February 2nd, 2021 at 12:30 PM
### Championed By: Angus Perkerson @anguspiv

Hey Everyone,
Well, it's a New Year, and time for another Virtual Lunch.js!

Even though we can't meet up in person, we can still chat and share a meal through the power of the internet!
This is an opportunity for you to check-in and chat with your fellow JavaScripters, and share your knowledge with each other. All are welcome and encouraged to attend; from Juniors to Seniors!
Looking forward to chatting with everyone!

You will be able to talk and join us at http://ramb.ly/lunch.js

And please remember to use headphones to help prevent feedback and echo!
Championed By: Angus Perkerson @anguspiv

Hey Everyone,
It's time for another Virtual Lunch.js!

Even though we can't meet up in person, we can still chat and share a meal through the power of the internet!
This is an opportunity for you to check-in and talk with your fellow JavaScripters, and share your knowledge with each other. All are welcome and encouraged to attend; from Juniors to Seniors!
Looking forward to chatting with everyone!

You will be able to talk and join us at http://ramb.ly/lunch.js

And please remember to use headphones to help prevent feedback and echo!

**Comment by mattrussell36** [comment]
Hey @anguspiv  Just wondering what the date of this will be? I think it needs to be updated in the title and issue text

**Comment by anguspiv** [comment]
@mattrussell36 Whoops Sorry about that, it's this upcoming Tuesday, February 2nd! I updated the issue with the correct date... that's what I get for copying and pasting...
