### ISSUE TITLE
Culver City x Playa Vista collab - February 7th, 2017

### ISSUE THREAD

**Issue by machikoyasuda** [jsla/lunch.js#28]
# Culver City
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @machikoyasuda

The private room in the back of [Phorage](http://phoragela.com/) is our fallback default. But if anyone else has suggestions, let me know in the comments:

**Comment by machikoyasuda** [comment]
hi @gr2m @jimthoburn @jdorfman @leighphan @RobAWilkinson @jadware @toiye - lunch.js is back 🍲

**Comment by jdorfman** [comment]
Down

**Comment by jadware** [comment]
works for me

**Comment by gr2m** [comment]
I’m in!

**Comment by toiye** [comment]
Of course.

**Comment by jimthoburn** [comment]
Hooray!  : )

**Comment by RobAWilkinson** [comment]
Down like Charlie Brown, there's a new poke spot next door owned by the same people too FYI.

**Comment by remarks** [comment]
I'll be there!

**Comment by machikoyasuda** [comment]
@jarrettch eat with us :)

**Comment by jdorfman** [comment]
@machikoyasuda lunch.js got a shoutout at https://www.meetup.com/SoCal-Node-JS/events/234615164/

**Comment by jarrettch** [comment]
@machikoyasuda just updated the Playa Vista issue to the Culver City location. That poke is calling me, hopefully i can just bring it over haha. See you all then!

**Comment by 8bitDesigner** [comment]
Yaay! Totes in.

**Comment by derduher** [comment]
✋  I'm in.

**Comment by toiye** [comment]
Count me in.

**Comment by timzero** [comment]
🍜 I'm in

**Comment by Basscord** [comment]
👍 count me in.

**Comment by machikoyasuda** [comment]
lunch js in 30 min :)

**Comment by 8bitDesigner** [comment]
Just got here, we're in the middle of the long table

**Comment by machikoyasuda** [comment]
super fun! see y'all in March.

**Comment by gr2m** [comment]
oh no we didn’t take a picture! It was super nice, see you next time :)
