### ISSUE TITLE
Calling All Champions - We're Back for July 6th 2021

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#285]
## Hey lunch.js Champions!
The next first Tuesday of the month is **July 6th, 2021**
Please create new issues when you get the chance.

Note that lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

## Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County

pinging previous champions...
@powernerd @StevenKitzes @gr2m @davidguttman @jarrettch @jcblw

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by gr2m** [comment]
There were two folks asking about Orange County recently, maybe we could add it?

**Comment by anguspiv** [comment]
Hmm, I updated to clarify that these are previous lunch locations, but I also added Orange County. I should probably re-think this issue template to better suggest new locations, and on going locations.

**Comment by powernerd** [comment]
Looking for an eastsider co-champion... July will work for me, but there is some uncertainty with offices opening back up. 

May need to champion another town once a year changes take effect, maybe not.

**Comment by anguspiv** [comment]
Thank you everyone for your help with going back to in-person Lunch.js events! @jjandoc @powernerd @StevenKitzes @JakeDluhy. 

Let's keep the momentum going with next month!
