### ISSUE TITLE
Santa Monica - February 7th, 2017

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#29]
# Santa Monica
### @ [Plan Check, Santa Monica](http://www.plancheck.com/locations_and_menus/santa_monica)
1401 Ocean Ave. Santa Monica, CA 90401
[Yelp Review](https://www.yelp.com/biz/plan-check-kitchen-bar-santa-monica)

Championed By: Angus Perkerson @anguspiv

**Comment by anguspiv** [comment]
So I won't be able to make it tomorrow, due to injury, does someone wanna take over as champion last minute? @jcblw? I just need to call to make a reservation in the morning.

**Comment by jcblw** [comment]
@anguspiv do we need reservations? If so I can call.

**Comment by anguspiv** [comment]
Reservations aren't needed. I just thought with 6+ people it would be good to reserve a spot.

**Comment by etanlubeck** [comment]
It's that time again.
https://github.com/jsla/lunch.js/issues/38
