### ISSUE TITLE
DTLA - July 6th, 2021

### ISSUE THREAD

**Issue by JakeDluhy** [jsla/lunch.js#290]
# DTLA
### @ Grand Central Market

Championed By: Jake Dluhy @JakeDluhy

I'm tall (6' 2") and look like my linkedin photo: https://www.linkedin.com/in/jakedluhy/. I'll be hanging out at the Hill Street entrance until 12:35pm. Feel free to email me at jake.dluhy@producepay.com (or slack me on the js.la slack) if you're having trouble finding us!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by JakeDluhy** [comment]
Cancelling unless someone let's me know they're planning to come!

**Comment by kevinashworth** [comment]
I’m planning on it! Nearby.

**Comment by JakeDluhy** [comment]
Awesome! I'm running late but will be there in a few

**Comment by kevinashworth** [comment]
It's 12:37. Don't see you! Walking over to get Tomas tacos
