### ISSUE TITLE
Woodland Hills - July 6, 2021

### ISSUE THREAD

**Issue by StevenKitzes** [jsla/lunch.js#291]
# Woodland Hills

### @ The Stand, Warner Center

5780 Canoga Ave, Woodland Hills, CA 91367

This location has 4 restaurants to choose from, kinda food court style!  Let's all grab a bite and chill under some umbrellas to chat JS.  Parking requires you take a ticket but the restaurants all validate.  You can find me by my purple shirt and audacious sunglasses.

Championed By: Steven Kitzes

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by MrNanosh** [comment]
Sorry, Steven, I was going to try to make it but it seems like I have a meeting conflict this time😣. Let's meetup sometime this month!
