### ISSUE TITLE
Calling all Champions - August 3rd, 2021

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#293]
## Hey lunch.js Champions!
The next first Tuesday of the month is **August 3rd, 2021**
Please create new issues when you get the chance.

Note that lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

## Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County
Woodland Hills

pinging previous champions...
@powernerd @StevenKitzes @gr2m @davidguttman @jarrettch @jcblw @jakedluhy @jjandoc 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood lunch.js [check out the champion guide](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md) and comment here to get started!

**Comment by gr2m** [comment]
I wonder if it would make sense to change the process a bit:

Instead of asking who wants to champion a lunchjs event at each location every month, I'd start out by defaulting the hosts for last months event to this months event and ask them to opt-out if they no longer want to be champion.

We could keep track of who currently is a champion for each location, we could also keep track of alumni. 

What do you think?

**Comment by anguspiv** [comment]
Sorry @gr2m I was heading out for a long camping trip, but I am back now. 
I think we would need a consensus from the current Champions, for this kind of change. That said I think as long as we set up the opt-out to be very easy to do. I.e. respond to this monthly post saying `opt-out` in the reply. I think that would be a great optimization.

**Comment by anguspiv** [comment]
Thanks everyone for your help this month! Hopefully, we can keep the ball rolling next month!
