### ISSUE TITLE
Mar Vista - August 3, 2021

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#295]
# Mar Vista
### @ Atmosphere Cafe

Championed By: Angus Perkerson @anguspiv 

Lookiing Forward to chatting with Everyone!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by MrNanosh** [comment]
on my way, will be 10 min late due to traffic

**Comment by anguspiv** [comment]
Running late too :( be there shortly
