### ISSUE TITLE
Calling All Champions! September 7th, 2021

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#296]
Hey lunch.js Champions!
The next first Tuesday of the month is August 3rd, 2021
Please create new issues when you get the chance.

Note that lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County
Woodland Hills

pinging previous champions...
@powernerd @StevenKitzes @gr2m @davidguttman @jarrettch @jcblw @JakeDluhy @jjandoc

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood lunch.js check out the champion guide and comment here to get started!

**Comment by swatana3** [comment]
Hi,

I can champion for Redondo beach.

**Comment by ultamatt** [comment]
I'll champ North Hollywood if I get 3+ folks who say they'll come. I'll open an issue.

**Comment by anguspiv** [comment]
Thanks Everyone for helping out and Championing an event near you! I couldn't do this without y'all!

So lets keep the momentum going and start getting October events going, so we can all enjoy a nice Pumpkin Spice everything together!
