### ISSUE TITLE
North Hollywood - September 7 2021 12pm till 1:30pm 

### ISSUE THREAD

**Issue by ultamatt** [jsla/lunch.js#298]
# North Hollywood 
### @ TBD

Championed By: Matt Moeller (@ultamatt) 

If you can COME please react with 👍 

Vote for where we go! 
😄  = [EL TEJANO (Outdoor Seating, Mexican) ](https://www.eltejanotexmex.com/)
🎉 = [PITFIRE PIZZA (Outdoor Seating, Pizza/Italian)](http://www.pitfirepizza.com/) 
❤️ = [BREWS BROTHERS (Indoor/Outdoor Seating, Brew Pub)](https://www.brewsbrotherscraftbeer.com/)
😕 = [NONE OF THESE OPTIONS (Please suggest something else)](https://youtu.be/6_b7RDuLwcI?t=12) 

If you are planning to attend subscribe to the issue to get notifications for new comments.

Please Note: _LunchJS at this location will be cancelled with 3 or less participants._

**Comment by mattdeco** [comment]
Unfortunately I'll be out of town for this one but I am eager to attend future North Hollywood / East SFV lunches!

**Comment by ultamatt** [comment]
Nobody is planning on showing up, so I'm cancelling.
