### ISSUE TITLE
DTLA - August 2nd, 2016

### ISSUE THREAD

**Issue by davidguttman** [jsla/lunch.js#3]

**Comment by machikoyasuda** [comment]
@cacheflow

**Comment by machikoyasuda** [comment]
@kpearson

**Comment by plantprojects** [comment]
How about [Tender Greens](http://www.tendergreens.com/locations/365/downtown-la)?

**Comment by kpearson** [comment]
I'm in.

**Comment by plantprojects** [comment]
How about 12:30?

**Comment by eirinikos** [comment]
12:30 works!

**Comment by iwilliams** [comment]
12:30 is good.

**Comment by plantprojects** [comment]
Ok, let's do 12:30. I'll post it to the chat to see if we can reach more devs to join us.

**Comment by kpearson** [comment]
12:30 sounds good to me.

**Comment by kpearson** [comment]
I'm "kit" on slack.

**Comment by cacheflow** [comment]
Huh? I'm confused. Where and when? In DTLA or Santa Monica? Is this today?

**Comment by davidguttman** [comment]
@cacheflow: lunch.js is every month on the first Tuesday. This month it is today (8/2). 

Lunches are organized by neighborhood on separate issues. This issue is for DTLA.
