### ISSUE TITLE
February 2017 - Calling all champions!

### ISSUE THREAD

**Issue by etanlubeck** [jsla/lunch.js#30]
## Hey `lunch.js` Champions!

The next first Tuesday of the month is `February 7th, 2017`
Please create new issues when you get the chance.
## Current Champions

Santa Monica - @anguspiv 
Culver City - @machikoyasuda
West Hollywood - @Rrrapture
Playa Vista - @jarrettch

## Locations with Champions Needed
If you see a neighborhood not listed, it would be awesome if you would champion it.

DTLA (Downtown) 
SF Valley

**Comment by ashwell** [comment]
Looks like everything is set for lunch.js tomorrow, going to go ahead and close this.
