### ISSUE TITLE
West Hollywood - February 7, 2017 at 12:30

### ISSUE THREAD

**Issue by Rrrapture** [jsla/lunch.js#31]
West Hollywood

Next lunch is Tuesday, February 7, 2017  at 12:30 PM

@ Location TBD

Championed By: Rachelle @rrrapture

Vote on the location!
:smile: [Luv2Eat Thai Bistro](https://www.yelp.com/biz/luv2eat-thai-bistro-los-angeles)
:tada: [Wirtshaus](https://www.yelp.com/biz/wirtshaus-los-angeles)

voting closed: lunch will be at  [Luv2Eat Thai Bistro](https://www.yelp.com/biz/luv2eat-thai-bistro-los-angeles)

**Comment by Rrrapture** [comment]
Haha this is what happens when I try to edit github issues on my phone through slack's web browser.

**Comment by davidguttman** [comment]
I'll be there!

@temojin, @lmordell, @lsfisher, @maytaldahan, krainboltgreene: lunch.js next Tuesday?

**Comment by Rrrapture** [comment]
1. Luv2Eat Thai Bistro
https://www.yelp.com/biz/luv2eat-thai-bistro-los-angeles

2. Wirtshaus
https://www.yelp.com/biz/wirtshaus-los-angeles

3. Open to suggestions! Comment below with yelp link or name & address & site link

**Comment by andyburke** [comment]
in (unless work interferes)

**Comment by Rrrapture** [comment]
Ok folks we have 2 votes for  😄 Luv2Eat Thai Bistro; @davidguttman @ashwell could one of you make me a collaborator so I can update the labels for this issue to `voting closed` &  `location decided`? Thanks!

**Comment by ashwell** [comment]
@Rrrapture you should be a collaborator already, I sent you an invite but it doesn't look like you have accepted it yet. Let me know if still have problems after accepting it

**Comment by Rrrapture** [comment]
@ashwell you're the best, I missed the email. Thanks!
