### ISSUE TITLE
South Bay - February 1 2022

### ISSUE THREAD

**Issue by acdoyle630** [jsla/lunch.js#312]
### @ TBD
Championed By: Adam Doyle @acdoyle630

Hey everyone!  Looking to see if people are interested in doing a South Bay lunch.js.  Throwing out Brews Hall since I just went to an event there, but definitely open to suggestions.

I'm also new to the area, so if anyone's attended or championed a South Bay spot that worked well I'm happy to stick with what works.  Feel free to add more suggestions below!

* [Brews hall](https://www.yelp.com/biz/the-brews-hall-hermosa-beach-hermosa-beach-2?osq=brews+hall)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by etnlbck** [comment]
I'll be there. Brews Hall in hermosa or torrance?

**Comment by etnlbck** [comment]
@acdoyle630 we on for tomorrow?

**Comment by eunicode** [comment]
I'm super bummed I can't make it, but I really want to meet other developers so hoping there will be future lunches! Is dinner.js also a possibility lol?

**Comment by anguspiv** [comment]
> I'm super bummed I can't make it, but I really want to meet other developers so hoping there will be future lunches! Is dinner.js also a possibility lol?

Hmmmm, not the worst idea...

**Comment by acdoyle630** [comment]
I'm still down for tomorrow.  Sounds like Brews Hall is the spot.  I'll try and get there and grab a table around 12:15. I'll post in the slack thread too for extra visibility.  Hope to see yall there!
