### ISSUE TITLE
Santa Monica - March 1st, 2022

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#316]
# Santa Monica
### @ [Sonny McLean's](https://www.yelp.com/biz/sonny-mcleans-santa-monica-3)

Championed By: Angus Perkerson @anguspiv

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jcblw** [comment]
sounds fun! I'll try to make it.

**Comment by anguspiv** [comment]
Running about 10 minutes late...:(
