### ISSUE TITLE
Playa Vista x Culver City Collab - February 7th, 2017

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#32]
# Playa Vista
### @ [Phorage](http://phoragela.com/) 3300 Overland Avenue, Los Angeles, CA 90034

Championed By: Jarrett @jarrettch

There was only a few of us last time, and it was mentioned that we should partner up with the [Culver City group](https://github.com/jsla/lunch.js/issues/28) next lunch.js. They'll be having lunch @ [Phorage](http://phoragela.com/) which is at 3300 Overland Avenue, Los Angeles, CA 90034.

~~We also have a Phorage close by in Playa Vista so that's an option. Open to suggestions/discussion.~~

**Comment by jarrettch** [comment]
@derduher @MalcolmGC new issue for Feb!

**Comment by jarrettch** [comment]
We'll be at the Culver City lunch.js if anyone is interested. Updated the issue.

**Comment by machikoyasuda** [comment]
We missed you @jarrettch! Come pho with us in March :)
