### ISSUE TITLE
Santa Monica - June 7th 2022

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#326]
# Santa Monica
### @ [Sonny McLeans](https://www.yelp.com/biz/sonny-mcleans-santa-monica-3) 

Championed By: Angus Perkerson @anguspiv 

Hey Folks!
Normally we have been going to [Sonny McLeans](https://www.yelp.com/biz/sonny-mcleans-santa-monica-3) in Santa Monica, since it has pretty good food, and also a nice outdoor backyard. But I am always open to change and trying new things! If anyone has an idea or location that they want to try let me know! 
Heck maybe we could bring lunch and meet in a nice park or coffee shop? The world is our oyster!

Just leave a comment below! All suggestions are welcomed

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jcblw** [comment]
Would love to join this!

**Comment by drewsn0w** [comment]
Would love to join. Let me know if you guys find a new spot.

**Comment by anguspiv** [comment]
Hmmm, so no one's really suggested a new place, so I was going to default to Sonny's if that's cool with everyone? Otherwise last call for any new place to try as a group?

**Comment by anguspiv** [comment]
Lets just do Sonny's then

**Comment by jcblw** [comment]
Yeah Im down for Sonny's!

**Comment by anguspiv** [comment]
Hey Everyone, we are sitting in the back outdoor patio
