### ISSUE TITLE
NoHo - July 5, 2022

### ISSUE THREAD

**Issue by mikeyamato** [jsla/lunch.js#328]
# North Hollywood
### @ Pitfire Pizza, 5211 Lankershim Blvd, North Hollywood, CA 91601

We'll plan to meet outside in the patio.

Championed By: Mike Yamato @mikeyamato

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by anguspiv** [comment]
Won't be able to attend myself this time but wanted to comment 🔥 !!!!
