### ISSUE TITLE
DTLA (Downtown) - February 7th, 2017

### ISSUE THREAD

**Issue by matikin9** [jsla/lunch.js#33]
# DTLA
### @ TBD

Championed By: Nina Kin @matikin9

Vote:
:tada: for [The Little Easy](https://www.yelp.com/biz/the-little-easy-los-angeles-2)
:heart: for [Orleans & York](https://www.yelp.com/biz/orleans-and-york-deli-los-angeles-3)
:+1: for [Little Jewel of New Orleans](https://www.yelp.com/biz/little-jewel-of-new-orleans-los-angeles-2)
Or throw out suggestions below~~

**Comment by matikin9** [comment]
We can table this try again next month...

**Comment by jdorfman** [comment]
@matikin9 can we do it on different days than Culver City? That way if people want to go to both they can.

**Comment by eirinikos** [comment]
Whoa - hadn't heard of [Orleans & York](https://www.yelp.com/biz/orleans-and-york-deli-los-angeles-3) before. Also, sorry for being so late to the game. 😢

**Comment by matikin9** [comment]
@eirinikos no worries, can you make it to Mar 7? :D

**Comment by ashwell** [comment]
@jdorfman as of now we have been promoting lunch.js as being the first Tuesday of the month.

There have been rumblings of allowing people to set up other dates, but for now, we'd like to keep things consistent.

I'm open to suggestions about how to handle multiple days for this, but until I can write up a more formal explanation of the "champion process" I would worry about confusing people.

**Comment by ashwell** [comment]
also, FYI to everyone watching this, the ticket for March is open, #37
