### ISSUE TITLE
North Hollywood - July 12, 2022

### ISSUE THREAD

**Issue by mikeyamato** [jsla/lunch.js#333]
# North Hollywood
### @ [Pitfire Pizza](https://www.pitfirepizza.com/north-hollywood)

Championed By: Mike Yamato @mikeyamato

Order your food/drink at the bar. I'll try and grab an outdoor table. Look for an Asian fellow (me) with a trucker type of hat.

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by zeckdude** [comment]
I'm so there! Let's get nerdy!

**Comment by ultamatt** [comment]
One in Noho! Sweet. I'm gonna do this one!
