### ISSUE TITLE
Santa Monica - August 2nd 2022

### ISSUE THREAD

**Issue by jcblw** [jsla/lunch.js#335]
# Santa Monica
### @ Vote Now!

Championed By: Jacob Lowe @jcblw 

Let me know if you have any suggestions for Food places, open to anywhere in the Santa Monica area. Looking for something somewhat healthy with outdoor dining! Please leave a comment with your suggestion and react with hearts to the ones you like.

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jcblw** [comment]
@anguspiv @drewsn0w @funbunch @sarahzdev @ghost @mnicole @mikewrather @khoerling @namadaza @zaach @alyviam @T-Wesst

Let me know y'all thoughts! Created this list of people I think are somewhat close and might be interested, I can remove y'all from the next ping.

**Comment by khoerling** [comment]
Yo, Jacob!  Anything for y'all and JS.la;  I'm in,

-
Keith
CTO  //  dimension software

**Comment by anguspiv** [comment]
I'll see you there! @jcblw I'm good with Berra Donna!

**Comment by alyviam** [comment]
I'm in!

**Comment by yowainwright** [comment]
In 👋

**Comment by drewsn0w** [comment]
Have we decided on Bardonna @ 12:30pm?

**Comment by namadaza** [comment]
I'll be there at 12:30!

**Comment by alyviam** [comment]
Yep! Bardonna @ 12:30

**Comment by jcblw** [comment]
@drewsn0w yep! 

See y'all there today. I'll be wearing a teal shirt today in case we have not met before. I also will be showing up a bit early to ensure we get the community table :D

**Comment by jcblw** [comment]
Great seeing y'all today.

**Comment by yowainwright** [comment]
@jcblw yeah, I loved the dialogs! So great to chat about code things in a non-office setting again!!! 🥹🌞

**Comment by roygarxia** [comment]
Wow this is so cool!
I missed today but I'll subscribe to the issue.

**Comment by drewsn0w** [comment]
Sounds good to me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
