### ISSUE TITLE
Calling All Champions - September 6th, 2022

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#338]
Hey Everyone,

The next first Tuesday of the month is September 6th, 2022
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Santa Monica
Glendale / Atwater Village
North Hollywood

pinging previous champions...
@jcblw @mikeyamato @jjandoc 
 
If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by jcblw** [comment]
Can't this month I'll be in Italy. Happy to hand over the keys. @yowainwright @khoerling @alyviam

**Comment by anguspiv** [comment]
> Can't this month I'll be in Italy. Happy to hand over the keys. @yowainwright @khoerling @alyviam

Hey guys,
wanted to check in and see if any of you could champion this month's Santa Monica location? 
All you really need to do is pick a lunch spot, and create the github issue. Then just show up!
