### ISSUE TITLE
Culver City - September 6th, 2022

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#339]
# Culver City
### @ [Jackson Market](https://www.yelp.com/biz/jackson-market-culver-city?osq=Lunch)

Championed By: Angus Perkerson @anguspiv

Hey Everyone, 
I am going to help start a new group in Culver City! Hopefully I get to meet some new faces, and have more great conversations!
I am going to put up a few location suggestions and feel free to react to the issue with your vote for where you'd like to meet. Looking forward to seeing y'all there! Also feel free to through your own suggestions! Hope to see you there!

👍 [Jackson Market](https://www.yelp.com/biz/jackson-market-culver-city?osq=Lunch)
😄 [CAVA](https://www.yelp.com/biz/cava-culver-city?osq=Lunch)
🎉 [Metro Cafe](https://www.yelp.com/biz/metro-cafe-culver-city)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by funbunch** [comment]
Hope to make this one!

**Comment by roygarxia** [comment]
Wow! I'm in Culver City.
Will be there.

**Comment by powernerd** [comment]
Would love to be there but I have a conflicting meeting I can't miss.

**Comment by anguspiv** [comment]
Hey everyone,
Just updated the location to [Jackson Market](https://www.yelp.com/biz/jackson-market-culver-city?osq=Lunch)

So see you there!

**Comment by anguspiv** [comment]
If anyone is still coming I am in the back patio at the long table
