### ISSUE TITLE
Culver City x Playa Vista - March 7, 2017

### ISSUE THREAD

**Issue by machikoyasuda** [jsla/lunch.js#34]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @jarrettch & @machikoyasuda

The private room in the back of [Phorage](http://phoragela.com/) is our fallback default. But if anyone else has suggestions, let me know in the comments:

**Comment by jarrettch** [comment]
💯

**Comment by ryanponce** [comment]
🍜

**Comment by adamcee** [comment]
Hi all, just found out about this, looking forward to joining for lunch and js :_)

**Comment by machikoyasuda** [comment]
@leighphan @gr2m @jimthoburn lunch invites are out 💌  🍴

**Comment by Basscord** [comment]
Count me in! 👍

**Comment by jimthoburn** [comment]
Woo-hoo!   : )

**Comment by gr2m** [comment]
Yay I’ll try to come!

**Comment by machikoyasuda** [comment]
@Leighphan

**Comment by machikoyasuda** [comment]
@shanaweitzen come eat lunch with me!!!

**Comment by machikoyasuda** [comment]
@arthirad tomorrow! pho :D

**Comment by machikoyasuda** [comment]
thanks for coming yall!

in order from left to right: @jimthoburn @joseph-yp-kim @arthirad @jarrettch / @machikoyasuda @cielzee @gr2m @basscord 

see you next time! 

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/3673236/23685243/e4d3ddee-0357-11e7-8acc-bef0010d4514.jpg)
