### ISSUE TITLE
Calling All Champions - Oct 4th, 2022

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#341]
Hey Everyone,

The next first Tuesday of the month is Oct 4th, 2022
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County
Woodland Hills

pinging previous champions...
@jcblw @jjandoc @yowainwright @etnlbck

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by etnlbck** [comment]
Can you add me as a champion for South Bay

**Comment by yowainwright** [comment]
Can I be added as a champion of Santa Monica? 
~Unless someone else would like to champion it!

**Comment by anguspiv** [comment]
So I am not sure what y'all mean by adding you as a champion?
If you are referring to the Readme displaying your name. All you need to do is create the Location Issue yourself and make sure it follows the template. 

There are a some scripts that @gr2m was kind enough to add to automate that for us!

**Comment by etnlbck** [comment]
Might just need to be added as a collaborator so we can update labels.

**Comment by anguspiv** [comment]
Okay, that makes sense, apparently you HAVE to be a collaborator to add labels... which I guess makes sense
