### ISSUE TITLE
Santa Monica - Oct 4, 2022

### ISSUE THREAD

**Issue by yowainwright** [jsla/lunch.js#344]
# Santa Monica

### @ TBD

Championed By: Jeff Wainwright @yowainwright

Feel free to add another location! 
Excited to see you!!!

:+1: [Blueys](https://blueyskitchen.com/)
:smile: [Cha Cha Chicken](https://chachachicken.com/)
:tada: [R+D](https://rd-kitchen.com/locations/santamonica/)
:heart: [Benny's Taco](https://bennystacos.com/bennys-tacos-santa-monica/)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by donovangomez** [comment]
Are newbies allowed to join in? 👀

**Comment by anguspiv** [comment]
Oh Course! We love meeting new folks! Come on by!

**Comment by donovangomez** [comment]
Awesome thanks I'll see you guys at whichever place wins.

**Comment by yowainwright** [comment]
👍 My vote is blueys!

**Comment by yowainwright** [comment]
See you tomorrow at 12:30pm at Blueys!
https://blueyskitchen.com/

I'll bring a few teammates!

**Comment by donovangomez** [comment]
Sick see you guys there!

**Comment by powernerd** [comment]
Hoping to come by as well

**Comment by aloukissas** [comment]
Blueys! Right across the street from our office - so easy!
