### ISSUE TITLE
Culver City - Nov. 1st, 2022

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#346]
# Culver City
### @ [Jackson Market](https://www.yelp.com/biz/jackson-market-culver-city)

Championed By: Angus Perkerson @anguspiv 

Hey Everyone, 
Let's try Culver City again... when its not right after a Holiday and not during an extreme heat warning. Sadly I can't make it this time, since I will be flying out of town, but I can still manage the issue for now. 

To get started let's vote on a couple places to meet at for lunch! Feel Free to suggest other places too!
Just react to the issue with the matching emoji, or comment below with your suggestion!

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by anguspiv** [comment]
@funbunch I forgot to tag you in this, issue but hope to see you there!

**Comment by funbunch** [comment]
Nov something right? Not October?

**Comment by anguspiv** [comment]
Doh! Thank you for calling that out... this is what you get for copying and pasting.

**Comment by funbunch** [comment]
I should be able to make this one!

**Comment by anguspiv** [comment]
I am setting the location to Jackson Market for now! Great sandwhich/salad place with an amazing back patio to eat on

**Comment by funbunch** [comment]
This is today right?

**Comment by anguspiv** [comment]
> This is today right?

Yep, I'm about to head over shortly @funbunch. See you there!
