### ISSUE TITLE
Calling All Champions - March 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#35]
## Hey `lunch.js` Champions! ##

The next first Tuesday of the month is `March 7th, 2017`
Please create new issues when you get the chance.
## Current Champions ##

Santa Monica - @anguspiv ( #38 )
Culver City / Playa Vista - @machikoyasuda / @jarrettch ( #34 )
West Hollywood - @Rrrapture
DTLA (Downtown) - @matikin9 ( #37 )
SF Valley - @remarks ( #36 )

## Locations with Champions Needed
If you see a neighborhood not listed, it would be awesome if you would champion it!

**Comment by anguspiv** [comment]
I hate to do this again, but I have the joy of jury duty that week, so I can't champion this time around. Would anyone like to take charge? If not I can handle the SM, just can't be there.

**Comment by ashwell** [comment]
@jcblw are you going to go to Culver or SM?

**Comment by ashwell** [comment]
@Rrrapture are you able to champion the West Hollywood lunch.js again?
