### ISSUE TITLE
Santa Monica - Dec 6th, 2022 

### ISSUE THREAD

**Issue by yowainwright** [jsla/lunch.js#351]
# Santa Monica
### @ TBD

Feel free to add food suggestions or else I put some options up shortly!

1. [Tacos Por Favor](https://www.tacosporfavor.us/) 🌮 
2. [Tiato Kitchen + Garden](https://tiato.com/) 🥙
3. [A Cut Above](https://www.acabutchershop.com/) 🥪 
4. Other recommendations 🤷‍♂️

Championed By: Jeff Wainwright @yowainwright 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by jcblw** [comment]
No going to make it, but I love tacos por favor haha.

**Comment by anguspiv** [comment]
🌮 
I'm down to meet!

**Comment by yowainwright** [comment]
Tacos Por Favor it is!

- https://www.tacosporfavor.us/location/santa-monica/
- https://goo.gl/maps/YquXL23RCbcVEdK5A (map)

Let me know if any other information is needed!
