### ISSUE TITLE
Santa Monica - January 3, 2023

### ISSUE THREAD

**Issue by yowainwright** [jsla/lunch.js#355]
# Santa Monica
### @ TBD

Feel free to add food suggestions or else I put some options up shortly!

1. [Tiato Kitchen + Garden](https://tiato.com/) 🥙
2. [A Cut Above](https://www.acabutchershop.com/) 🥪 
3. Other recommendations 🤷‍♂️

Championed By: Jeff Wainwright @yowainwright 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by donovangomez** [comment]
Hope I can make this one. I had covid last month 😭. Happy holidays everyone!

**Comment by yowainwright** [comment]
## A Cut Above!

The lunch will be at [A Cut Above](https://www.acabutchershop.com/).
Please let me know if you're coming with an emoji, comment or JS.LA slack message before Tuesday, Jan 3rd at 9am.

---

[📍location](https://goo.gl/maps/QbxpECDv5icyL6Z17) | [👩‍💻 website](https://www.acabutchershop.com/)

**Comment by donovangomez** [comment]
I'll be there. The site says they're closed January 3rd though 
![image](https://user-images.githubusercontent.com/29687217/210308701-bfe8822a-d212-4a00-801c-365459653573.png)

**Comment by anguspiv** [comment]
Good catch @donovangomez! @yowainwright should we go to tiato then, or whereever you pick?

**Comment by yowainwright** [comment]
Yes! [Blueys](https://blueyskitchen.com/) it is!

---

[📍 location](https://goo.gl/maps/mxxtwN2dTKr2MvDQ6)  | [👩‍💻 website](https://blueyskitchen.com/)

---

> @donovangomez thanks so much for catching this! 🙏

**Comment by yowainwright** [comment]
Yes! [Blueys](https://blueyskitchen.com/) it is!

---

[📍 location]()  | [👩‍💻 website](https://blueyskitchen.com/)

@donovangomez thanks so much for catching this! 🙏
