### ISSUE TITLE
SF Valley - March 7, 2017

### ISSUE THREAD

**Issue by remarks** [jsla/lunch.js#36]
# SF Valley
### @ [Hamptons 818](https://www.yelp.com/biz/hamptons-818-sherman-oaks), 14917 Ventura Blvd, Sherman Oaks, CA 91403

Championed By: Mark Pinero @remarks

Would love to start this up again in the Valley!

**Comment by machikoyasuda** [comment]
First Issue 🎊

**Comment by ashwell** [comment]
Hey @remarks! Thanks for picking up the SF Valley group, I'll send you a collaborator invite so you can add and remove labels as well as edit the main ticket comment when the poll is closed.

Let me know if you have any questions!

**Comment by machikoyasuda** [comment]
@wingedearth sfvalley lunch.js is happening 💮  bring your coworkers :)

**Comment by remarks** [comment]
@machikoyasuda @ashwell thanks!

@jeanpierreb @sheelah @etanlubeck @SeanCox @doitlikepruett:
since you all went to the previous one, would you like to have lunch 😁?

**Comment by sheelah** [comment]
@remarks Sure - I'm in.  I'd vote for Hamptons 818.

**Comment by SeanCox** [comment]
@remarks Thanks for reminding me, I'm in!

**Comment by remarks** [comment]
Hamptons 818 it is :) See you guys there!

**Comment by remarks** [comment]
It was nice meeting you @SeanCox @sheelah! Hopefully more of us next time 😁
