### ISSUE TITLE
Santa Monica - February 7, 2023

### ISSUE THREAD

**Issue by yowainwright** [jsla/lunch.js#360]
# Santa Monica
### @ TBD

Feel free to add food suggestions or else I put some options up shortly!

1. [A Cut Above](https://www.acabutchershop.com/) 🥪 
2. [Tacos Por Favor](https://www.tacosporfavor.us/location/santa-monica/) 🌮

Championed By: Jeff Wainwright @yowainwright 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by roygarxia** [comment]
Tacos Por Favor!

**Comment by jcblw** [comment]
I'm down! Taco Por Favor is my vote too.

**Comment by yowainwright** [comment]
See people at [Tacos Por Favor](https://www.tacosporfavor.us/location/santa-monica/) today!

- [Map](https://goo.gl/maps/98BdnJb3d3zFHiHYA)
