### ISSUE TITLE
Join Slack links are broken (heroku site down)

### ISSUE THREAD

**Issue by xta** [jsla/lunch.js#361]
Hi js.la, I followed the link in [CONTRIBUTING](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md#so-its-time-to-meet-for-lunch). join here ( https://js.la/slack ) points to a broken heroku app (https://join-jsla-slack.herokuapp.com/). 

On the js.la homepage (https://js.la/), the Join Slack button also points to the same broken heroku page (https://join-jsla-slack.herokuapp.com/)

**Comment by anguspiv** [comment]
Hey @xta!

Thanks for letting us know. I am looking into this currently, but not sure on an update yet. In the meantime I sent an invite to your email on your profile to allow you to join!

**Comment by anguspiv** [comment]
I just tested this, and was fixed recently!
