### ISSUE TITLE
Mar Vista - February 7, 2023

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#362]
# Mar Vista
### @ [Mitsuwa Marketplace](https://goo.gl/maps/Gb53NBkGDrS8LQXY9)

Mitsuwa has a great food court with different Japanese cuisines. But I'm also open for alternative suggestions closeby!

Championed By: @gr2m - I'll be the one with a yellow GitHub Backpack

🌈 Everybody is welcome. js.la is the umbrella organization but you don't need to be an engineer or do any JavaScript to come. Just come and say hi 👋🏼 

If you are planning to attend comment below! I'm looking forward to meet y'all!

**Comment by anguspiv** [comment]
Oh I am 100% in... mostly cause that is walking distance for me

**Comment by sophiaorlando** [comment]
I'm in! I was a Software Engineer for awhile so talking code and development over some food?? Sounds good to me!

**Comment by roygarxia** [comment]
this is also super close to my place so will go!

**Comment by aloukissas** [comment]
Right by my house! I'll probably make it!

**Comment by mejincodes** [comment]
I'll probably make it, too, if my work day permits!

**Comment by anguspiv** [comment]
I'm gonna see if I can get there early to snag maybe one of the bigger tables for us

**Comment by aloukissas** [comment]
I'm at Alana's before this if anyone's around early. If not, see you all at 12:30!

**Comment by gr2m** [comment]
We are here ![image](https://user-images.githubusercontent.com/39992/217357727-624791a4-4387-4cdf-bef8-db00d683cb1e.jpeg)

**Comment by roygarxia** [comment]
Was great meeting y'all.
Very friendly group!

**Comment by gr2m** [comment]
Thank you all for coming!

**Comment by gr2m** [comment]
:wave: let's do it again: https://github.com/jsla/lunch.js/issues/365

Y'all are from here, so I figured you should suggest where we should meet! Please post your suggestion in the thread, and we can vote when we get close?
