### ISSUE TITLE
Mar Vista - March 7, 2023

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#365]
# Mar Vista
### @ [Mitsuwa food court](https://goo.gl/maps/AdpiLLF5tLvS9X4c7)

Mitsuwa has a great food court with different Japanese cuisines. But I'm also open for alternative suggestions closeby!

Championed By: @gr2m - I'll be the one with a yellow GitHub Backpack

🌈 Everybody is welcome. js.la is the umbrella organization but you don't need to be an engineer or do any JavaScript to come. Just come and say hi 👋🏼 

If you are planning to attend comment below! I'm looking forward to meet y'all!

**Comment by diztinct-glenn** [comment]
New to the area and looking forward to my first lunch.js! 👋

**Comment by wlaurance** [comment]
👋 I'm down for lunch at Mitsuwa. Be've meaning to checkout the food court (and meet some new folks!) This one correct? https://goo.gl/maps/AdpiLLF5tLvS9X4c7 @gr2m

**Comment by gr2m** [comment]
Yes, that's the one!

**Comment by namadaza** [comment]
Ah I love the Mitsuwa food court, I'll be there!

**Comment by aloukissas** [comment]
Although I love Mitsuwa, it's good to know that there aren't many (any?) vegetarian options there :/

**Comment by xnd0** [comment]
I will also be attending! Looking forward to it

**Comment by roygarxia** [comment]
Looking forward to chatting with everyone again!

**Comment by roygarxia** [comment]
I'm here a bit earlier today since I had to run some errands nearby.
I'll be sitting in the same spot as last time (wearing a green sweatshirt).

**Comment by gr2m** [comment]
Thank you for coming y'all!!

![image](https://user-images.githubusercontent.com/39992/223557946-19b85f79-71c5-4934-8c4d-bc07e6da3135.jpeg)

**Comment by diztinct-glenn** [comment]
Pleasure meeting you guys! Thanks for organizing this.
