### ISSUE TITLE
Santa Monica - March 7th

### ISSUE THREAD

**Issue by jcblw** [jsla/lunch.js#366]
# Santa Monica
### @ [Thyme Cafe and Market](https://goo.gl/maps/hFBVH8BMg6iCnYY17)

Championed By: Jacob Lowe @jcblw 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by yowainwright** [comment]
See you there!

**Comment by eunicode** [comment]
Hey, I've arrived. Is anyone else here?

**Comment by eunicode** [comment]
Alright, I've finished my lunch so I'll be leaving.

**Comment by yowainwright** [comment]
@eunicode I'm so sorry! 😞 I didn't check my phone until I was leaving. 😥

**Comment by jcblw** [comment]
@eunicode omg, so sorry, we were at the place in the back near the parking. I hope you enjoyed the lunch.

**Comment by jcblw** [comment]
@eunicode are you in the js.la/slack ? Would love to chat.

**Comment by eunicode** [comment]
Thanks everyone for following up! I did enjoy my lunch, they have good salads. Next time I'll leave a comment beforehand if I plan on attending!
