### ISSUE TITLE
Palms - April 4, 2023

### ISSUE THREAD

**Issue by higgins** [jsla/lunch.js#369]
# Palms
### @ Palms

Championed By: Justin Higgins @higgins

Looks like Spring has sprung! 🌱

How about we all grab some food and eat at the park tables of [Woodbine Park in Palms](https://goo.gl/maps/SqQoa9hoTap4WyyH8)?

Lots of great eateries for take out in the neighborhood. Here are some I recommend:
- [Lokal](https://goo.gl/maps/VpQNQ8tuXuM5dGG39) 
- [The Vegan Joint](https://goo.gl/maps/VFGeZFyykg2GUpSB7) 
- [Good Day Thai](https://goo.gl/maps/pX97oRXbds1c8yhq9)
- [Simpang](https://goo.gl/maps/EJsHpwAXL9utrEum6)
- [Madre](https://goo.gl/maps/wvyh5oGFXMiLEyZy9)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by higgins** [comment]
hey @tvishwanadha @sjanpanah y'all should join!

**Comment by anguspiv** [comment]
You're not too far away, I'll tag along this month

**Comment by eunicode** [comment]
A picnic sounds lovely. Is the lunch still happening? If so, I'll be there!

**Comment by higgins** [comment]
> A picnic sounds lovely. Is the lunch still happening? If so, I'll be there!

Yep, i'll be out there at 12:30pm with my dog!

**Comment by eunicode** [comment]
Nice!

**Comment by quinnvaughn** [comment]
Getting food from madre right now. Be there soon.

**Comment by higgins** [comment]
![image](https://user-images.githubusercontent.com/876147/229899457-613834fd-3158-4f76-95ff-199221b7977e.jpeg) at one of the tables with this one 🐶

**Comment by higgins** [comment]
Great meeting you all today! As much as she loved it, I think wild pup Leche stays at home next time.

Looking forward to more events in the future 👋

**Comment by diztinct-glenn** [comment]
Don't break my heart! Loved meeting Leche and you all. Looking forward to the next one 😄

**Comment by eunicode** [comment]
I also loved seeing Leche, I volunteer to play with her while everyone talks haha. Thanks for hosting, and it was nice meeting everyone!
