### ISSUE TITLE
DTLA - March 7th, 2017

### ISSUE THREAD

**Issue by matikin9** [jsla/lunch.js#37]
# DTLA
### @ Orleans & York

Championed By: Nina Kin @matikin9

Vote:
:tada: for [The Little Easy](https://www.yelp.com/biz/the-little-easy-los-angeles-2)
:heart: for [Orleans & York](https://www.yelp.com/biz/orleans-and-york-deli-los-angeles-3)
:+1: for [Little Jewel of New Orleans](https://www.yelp.com/biz/little-jewel-of-new-orleans-los-angeles-2)
Or throw out suggestions below~~

**Comment by matikin9** [comment]
@eirinikos!

**Comment by jdorfman** [comment]
@matikin9 `s/February/March/g`

**Comment by eirinikos** [comment]
@matikin9 Voting for **Little Jewel of New Orleans**! It's busing/driving distance for me, though, would anyone want to meet beforehand to bus/rideshare/bikeshare? I'm coming from Wilshire & Hope. 🚌  🚗  🚲

**Comment by eirinikos** [comment]
Tagging @plantprojects 🎈

**Comment by eirinikos** [comment]
Do we still want to do lunch on Tuesday? To be honest, Little Easy would be easiest for me to get to from my office. (I'm dialing down my lunch ambitions for this month. 😜 )

**Comment by matikin9** [comment]
@eirinikos could you make it to orleans & york?  it's not that much further!  i could rideshare down with you :D

**Comment by LearningNerd** [comment]
I should be able to make it tomorrow to Orelans & York! See you guys there! :)

**Comment by jdorfman** [comment]
See you all there.

**Comment by eirinikos** [comment]
@matikin9 thanks for the thought! Orleans & York is actually walkable for me, but I'm going to have to sit tomorrow out. I will keep an eye on what's happening next month, though! <3

**Comment by jdorfman** [comment]
Something came up last minute, I might be late or absent. =/

**Comment by eirinikos** [comment]
p.s. Don't forget to vote today (if you haven't already)! 🇺🇸

**Comment by LearningNerd** [comment]
Aw man I'm sorry, I won't be able to make it today either! :( Sorry Nina. I do want to catch up later though! Have we ever tried coffee.js? hehe

**Comment by eirinikos** [comment]
@LearningNerd I love the idea of coffee.js! So much easier... Nina, what do you think? ☕️ 

Sorry for kinda hijacking this thread, but since it's Election Day today and we are in DT, I wanted to share info about this event in case anyone is interested...
http://www.scpr.org/events/2017/03/07/2256/election-central-candidates-forum-and-election-wat/

**Comment by matikin9** [comment]
lol, oh well, we tried!  I would be totally up for a coffee.js... also there's been a weekly Wednesday lunch in grand park for civic tech/data folks, which you guys are welcome to join.

**Comment by matikin9** [comment]
and yes, vote!!  i mailed in my ballot last week ;D

**Comment by eirinikos** [comment]
@matikin9 Wednesday civic tech/data lunches sound great! 🌮 
Is there a forum/Slack for these lunches? I've put them on my calendar.

**Comment by matikin9** [comment]
@eirinikos hehhh, nope.  i think there was an email with a calendar invite but i never got that one.  people just find out about it and show up when they can :D

**Comment by lhyman** [comment]
There was an original calendar invite. I'm happy to add you both. @matikin9 I just added you. @eirinikos send me your email?

**Comment by eirinikos** [comment]
✌️ @lhyman I can be reached at eirinikos@gmail.com. Thanks!
