### ISSUE TITLE
Calling All Champions - May 2 2023

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#370]
Hey Everyone,

The next first Tuesday of the month is May 2 2023
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County
Woodland Hills

pinging previous champions...
@gr2m @davidguttman @jcblw @jjandoc @yowainwright @higgins

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by gr2m** [comment]
would anyone be interested in a `lunch.js` in the Baldwin Hills / Crenshaw / Leimert Park area? If anyone knows folks form the area who might be interested, please send the my way

**Comment by yowainwright** [comment]
@gr2m not May for me—but I'd make the effort for June!

**Comment by anguspiv** [comment]
Thanks again everyone for hosting, and all your hard work. I really appreciate it!.
I've created the champions call for the next event #374 

Go ahead and create your local Lunch.js event when you have a moment.

You guys rock,
Angus
