### ISSUE TITLE
Santa Monica - May 2, 2023

### ISSUE THREAD

**Issue by yowainwright** [jsla/lunch.js#371]
# Santa Monica
### @ TBD

Feel free to add food suggestions!

1. ~~[A Cut Above](https://www.acabutchershop.com/)~~
2. ~~[Tacos Por Favor](https://www.tacosporfavor.us/location/santa-monica/)~~ 🌮
3. [Pono Burger](http://ponoburger.com/) 🍔 ✅ 

Championed By: Jeff Wainwright @yowainwright 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by novasm55** [comment]
A Cut Above looks delicious for a carnivore like me!

Should I just follow this issue as a comment thread for updates?

**Comment by yowainwright** [comment]
👋 @novasm55 yup!

**Comment by jcblw** [comment]
I'll be making it to this—no preference for the location.

**Comment by etnlbck** [comment]
I'm gonna join you all

**Comment by donovangomez** [comment]
@yowainwright @novasm55 It looks like A Cut Above is closed first Tuesdays of the month.  It won the vote earlier this year and it was closed lol 😭
![image](https://user-images.githubusercontent.com/29687217/234403724-7bb6765c-0a38-48c6-b5ab-58cce38a9c23.png)

**Comment by yowainwright** [comment]
@donovangomez it's literally like they're avoiding Lunch.js, haha! 
Thanks for pointing this out a 2nd time. 🙏

**Comment by wlaurance** [comment]
Will try to make this one 🤞

**Comment by anguspiv** [comment]
I am down for either location. Hope to see y'all there!

**Comment by jcblw** [comment]
Ill throw my vote behind 🍔

**Comment by sparklingwaterlemon** [comment]
Hi everyone. Just wanted to say hello and let you know that I'll be joining as well. Pono sounds great!

**Comment by ivonamojsovska** [comment]
Hi everyone, I am Ivona, and it's my first time joining a js lunch meeting. See you tomorrow, cheers

**Comment by johannafeick** [comment]
See you tomorrow!

**Comment by rrdennis** [comment]
Hey all, another first timer checking in. Looking forward to it :)

**Comment by funbunch** [comment]
Going to head up there and join this one today. :)

**Comment by eunicode** [comment]
Looking forward to seeing everyone!

**Comment by yowainwright** [comment]
See everyone at [Pono Burger](http://ponoburger.com/) 🍔 around 12:30

**Comment by yowainwright** [comment]
Thanks everyone for coming! 🙏 
That was a great turn out! 🎉

**Comment by yowainwright** [comment]
Happy Birthday @donovangomez !!! 🥇 🎉

**Comment by donovangomez** [comment]
Thanks @yowainwright appreciate it! It was cool this ended up being pretty big.
Good meeting everyone.

**Comment by sparklingwaterlemon** [comment]
Thank you @yowainwright for championing the lunch today. It was my first time at Pono Burger and the food (and company) were great!

There was a lot of interesting talk going on at both ends of the table and I wish there was two of me.
It was nice meeting everybody, and I hope to see ya'll again!
