### ISSUE TITLE
Palms - May 2nd, 2023

### ISSUE THREAD

**Issue by higgins** [jsla/lunch.js#372]
Next lunch is Tuesday, May 2nd, 2023 at 12:30 PM
@ Palms

Championed By: Justin Higgins @higgins

Last meetup at the park was pretty nice, why don't we do it again?! I also like the picnic format for its flexibility.

Grab some food and eat at the park tables of [Woodbine Park in Palms](https://goo.gl/maps/SqQoa9hoTap4WyyH8)?

Bring your food or grab something form lots of great eateries for take out in the neighborhood. Here are some I recommend:

[Lokal](https://goo.gl/maps/VpQNQ8tuXuM5dGG39)
    [The Vegan Joint](https://goo.gl/maps/VFGeZFyykg2GUpSB7)
    [Good Day Thai](https://goo.gl/maps/pX97oRXbds1c8yhq9)
    [Simpang](https://goo.gl/maps/EJsHpwAXL9utrEum6)
    [Madre](https://goo.gl/maps/wvyh5oGFXMiLEyZy9)
    [Koji Taco Truck](https://www.google.com/maps/place/3434+Overland+Ave,+Los+Angeles,+CA+90034/@34.0255484,-118.4139807,17z/data=!3m1!4b1!4m6!3m5!1s0x80c2ba34b6febbff:0x27ba072e691f91c6!8m2!3d34.0255484!4d-118.411792!16s%2Fg%2F11bw424vr9)

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by roygarxia** [comment]
can join this!

**Comment by higgins** [comment]
Heads up, if its raining tomorrow, I suggest we eat at Simpang

**Comment by higgins** [comment]
Weather is looking great! Will see you all at Woodbine park ✌️

**Comment by roygarxia** [comment]
hey Justin, got slammed with stuff at work.
i don't think i'll be able to make it this time :(

**Comment by higgins** [comment]
@roygarxia all good, catch you at another one!

**Comment by higgins** [comment]
Hanging out at the sunniest bench! ☀️

![image](https://user-images.githubusercontent.com/876147/235766311-2c678ee0-c537-4517-ad79-35e8210c5632.jpeg)
