### ISSUE TITLE
Calling All Champions - July 11th, 2023

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#377]
Hey Everyone,

The next first Tuesday of the month is July 4th 2023... so lets do it the next week July 11th, 2023!
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County
Woodland Hills
Baldwin Hills / Crenshaw / Leimert Park

pinging previous champions...
@gr2m @davidguttman @jcblw @jjandoc @yowainwright @higgins

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by gr2m** [comment]
Come join me!

* https://github.com/jsla/lunch.js/issues/378

**Comment by anguspiv** [comment]
Hey Everyone,

Really sorry for the late notice, been super busy couple of months... and the heat does not help. But next lunch.js is next week, so hopefully we can get some events going and still have a good time! 
The champions call for next week is #380 and hopefully we can still have a good time!

Thanks again for all your guys help!
