### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - July 11th, 2023

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#378]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [Ackee Bamboo](https://goo.gl/maps/SGpMQLbRLS1H9T7Q6)

Championed By: Gregor Martynus @gr2m

I'm open to alternative locations! I love [Swift LA](https://goo.gl/maps/Twxdo54o5v346wrv7) but it's closed on Tuesdays 🤷🏼 

If you are planning to attend please leave a comment!

**Comment by jarrettch** [comment]
Some meeting times have changed at work. Gonna try to make this. Been a while. Grew up in Baldwin Hills so def my stomping grounds!

**Comment by gr2m** [comment]
Hope you can make it! @jarrettch

**Comment by gr2m** [comment]
btw [Ackee Bamboo](https://goo.gl/maps/SGpMQLbRLS1H9T7Q6) is just a suggestion, happy to meet somewhere else closeby. I love [Swift Cafe](https://www.swift-la.com/location/swift-cafe/) but they are closed on Tuesdays, unfortunately.

**Comment by chandlercraig** [comment]
@maxgurewitz and I will see you there!

**Comment by jarrettch** [comment]
when I initially replied I didn't realize it fell on my daughter's birthday. 😅

spending the day with her. have fun!

**Comment by gr2m** [comment]
@jarrettch that is a great reason not to come, family first, always! Hope to see you next time!

**Comment by gr2m** [comment]
Hey Baldwin Hills is back, hope to see y'all there: #394
