### ISSUE TITLE
Santa Monica - March 7th, 2017

### ISSUE THREAD

**Issue by etanlubeck** [jsla/lunch.js#38]
# Santa Monica

Next lunch is __Tuesday, March 7th, 2017__ at __12:30 PM__
 @ [Vito's Pizza](https://www.yelp.com/biz/vitos-pizza-santa-monica)

Championed By: Nate Lubeck @etanlubeck

Alrighty, I'm going to try something different this time around. Shout out to @anguspiv for championing the previous Santa Monica Lunch.js

Where does everyone work? I'll be basing the poll on where in Santa Monica we are located.

[Daily Grill](https://www.yelp.com/biz/daily-grill-santa-monica-2) $$ :tada:
[Vito's Pizza](https://www.yelp.com/biz/vitos-pizza-santa-monica) $$ :heart:

**Comment by jcblw** [comment]
Me @pzenger @nhuynh3 @csreyes, and @LmtDNE are by the 26th street bergamot station.

**Comment by ashwell** [comment]
My team is on 6th & Broadway

I'm down to go someplace more "inland" for a change

**Comment by mnicole** [comment]
My team is interested in coming, and we're at 7th between SM and Arizona. Also down to go east.

**Comment by JMSantos94** [comment]
/\ Part of her team. o/

**Comment by etanlubeck** [comment]
Alrighty! I added a couple of places that are "inland". Feel free to make another addition if you don't like the two I've selected. Otherwise, voting is open! WooHoo!

**Comment by jcblw** [comment]
lol @etanlubeck  we cant vote for vitos since its not an available reaction.

**Comment by JMSantos94** [comment]
Vito's +1

**Comment by dancingshell** [comment]
🍕 !

**Comment by etanlubeck** [comment]
Out front

**Comment by ashwell** [comment]
Good seeing everyone at :pizza: lunch today!

**Comment by etanlubeck** [comment]
Let's pick a place to eat https://github.com/jsla/lunch.js/issues/41
