### ISSUE TITLE
Calling All Champions - September 5th, 2023

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#382]
Hey Everyone,

The next first Tuesday of the month is September 5th, 2023
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Westwood / UCLA
Mid-City / La Brea
Los Feliz / Hollywood
Culver City
Playa Vista
Santa Monica
Sherman Oaks
Thousand Oaks
Burbank
DTLA
South Bay
Valencia / Santa Clarita
Long Beach
Hermosa Beach
Orange County
Woodland Hills

pinging previous champions...
@gr2m @jcblw @jjandoc @yowainwright @higgins

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by gr2m** [comment]
I'm hosting in Baldwin Hills / Crenshaw / Leimert Park: #383

**Comment by donovangomez** [comment]
Opened up Santa Monica! #384

**Comment by anguspiv** [comment]
Hey everyone,

Thanks again for your help! I had a great time catching up with the Santa Monica Folks! 

The next event is for October 3rd, 2023 #385! Looking forward to seeing you then!

The sooner you have an event setup, the more likely people will have time to plan to attend, so please create them as soon as you can!

See y'all then!
