### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - September 5th, 2023

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#383]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [Ackee Bamboo](https://goo.gl/maps/SGpMQLbRLS1H9T7Q6)

Championed By: Gregor Martynus @gr2m

I'm open to alternative locations! Ackee Bamboo has great, freshly made Jamaican food!

If you are planning to attend please leave a comment!

**Comment by RohithSurya** [comment]
@gr2m See ya there
I've never tried Jamaican food.. I am excited 
![SoExcited~GIF](https://github.com/jsla/lunch.js/assets/29703054/245c4c2d-376e-4b3b-97f8-b0bd628cdd4a)

**Comment by jarrettch** [comment]
No birthdays this time. I should be good lol

**Comment by francisfuzz** [comment]
👋 ✨

**Comment by RohithSurya** [comment]
Hey guys.. Got an emergency.. See you guys next time

**Comment by gr2m** [comment]
there is construction right in front of the restaurant, the sidewalk is being redone. But the restaurant is open, I'll try to be there around 12.20 in case folks come early. See you then! 

Hope to see you next time @RohithSurya!

**Comment by gr2m** [comment]
danm I forgot to take a picture! We had @jarrettch and @francisfuzz with two of his cousins! Thank you for coming out ❤️

**Comment by francisfuzz** [comment]
Thanks friends! 👋 ✨

**Comment by gr2m** [comment]
Next lunch.js: Octoberd 3rd: #386

**Comment by gr2m** [comment]
Hey Baldwin Hills is back, hope to see y'all there: #394
