### ISSUE TITLE
Santa Monica  - September 5, 2023 

### ISSUE THREAD

**Issue by donovangomez** [jsla/lunch.js#384]
#  Santa Monica
### @  [ Thyme Market](https://thymecafeandmarket.com/)

Championed By:  Donovan Gomez  @donovangomez

As per @yowainwright 's tradition we can decide by vote.  I'm also indecisive lol. We'll have a location on 9/1. Open to more suggestions!

~~- [Tacos Por Favor](https://www.tacosporfavor.us/location/santa-monica/) - 🌮~~
~~- [ Tartine ](https://tartinebakery.com/los-angeles/santa-monica) - 🥖~~

~~- [ Thyme Market](https://thymecafeandmarket.com/) - 🥗~~
~~- [Hurry Curry](https://www.hurrycurryoftokyo.com/menu), [CrimsonLA](https://www.crimsonla.com/ocean-park-menus/), [Society Kitchen](https://www.societykitchenla.com/) (There's a lot of places here, I figured anyone can get what they want and I can just grab a table outsite.) - 😕~~

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by yowainwright** [comment]
I'll be there if I can make it @donovangomez!!!

**Comment by donovangomez** [comment]
Let's do Thyme Market. Have a good weekend everyone!

**Comment by StevenKitzes** [comment]
I’m planning to attend 💪

**Comment by anguspiv** [comment]
See you guys soon!

**Comment by StevenKitzes** [comment]
I’m here, got a table outside in back

**Comment by donovangomez** [comment]
![image](https://github.com/jsla/lunch.js/assets/29687217/a5cb7454-53ef-4b13-a741-f7392fbc988c)

**Comment by donovangomez** [comment]
Good seeing everyone!
