### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - October 3rd, 2023

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#386]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [Ackee Bamboo](https://goo.gl/maps/SGpMQLbRLS1H9T7Q6)

Championed By: Gregor Martynus @gr2m

I'm open to alternative locations! Ackee Bamboo has great, freshly made Jamaican food! We met there for the past 3 months!

If you are planning to attend please leave a comment!

**Comment by chromalley** [comment]
OOO - can I come too? I live in the neighborhood!

**Comment by gr2m** [comment]
Sure thing!

**Comment by cacheflow** [comment]
Can't wait!

**Comment by anguspiv** [comment]
I'll see yall there

**Comment by jarrettch** [comment]
okay if @cacheflow is gonna be there count me out 😆

**Comment by bkmorgan3** [comment]
I'll be there.  I just found this group a while ago so looking forward to meeting you all.

**Comment by RohithSurya** [comment]
I'll be there...
See you guys!

**Comment by jimmygranadino** [comment]
Interested in attending as well 🙂

**Comment by gr2m** [comment]
Afterschool care was canceled for my kids today 🤷 I'll come earlier at 12:10 so feel free to come early as well. I'll have to leave at 1pm unfortunately. I hope to see you all by then!

**Comment by chromalley** [comment]
I'm under the weather today folks, so I will have to wait until the next one.

**Comment by gr2m** [comment]
@chromalley happy to meet another time for a coffee at Harun or similar? I usually work at https://themetaphorclub.com/ between 9.30am - 4pm

**Comment by chromalley** [comment]
@gr2m I always wondered about that place! I'd be down to meet next Monday or Wednesday afternoon if you are available.

**Comment by gr2m** [comment]
I'll be there!

**Comment by gr2m** [comment]
Hey did I take the picture with someone else's phone? I don't see it in my library 🤷

**Comment by anguspiv** [comment]
Doh! Knew I forgot something. Here we go! 
![PXL_20231003_193720711.jpg](https://github.com/jsla/lunch.js/assets/1724500/c0c658ca-64ef-4acc-8f41-4ff86bc063b6)

**Comment by gr2m** [comment]
thank you! Legendary lunch.js! We back baby!!! Hope to see y'all next time!

**Comment by machikoyasuda** [comment]
@gr2m I'm jelly!!!!!!!! I see you @cacheflow + @jarrettch 👋 👋

**Comment by bkmorgan3** [comment]
It was really cool to meet you last week.  Hope to join again soon

**Comment by gr2m** [comment]
Hey Baldwin Hills is back, hope to see y'all there: #394
