### ISSUE TITLE
Eagle Rock - October 3, 2023

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#387]
# Eagle Rock
### @ Taco/Social, 1627 Colorado Blvd, Los Angeles, CA 90041

This is the NELA meetup that is normally at Bon Vivant in Atwater Village. This month, we're trying a new location in Eagle Rock, Taco/Social, which opened recently.

![bitmoji](https://sdk.bitmoji.com/render/panel/8b681f55-6f51-49db-87cb-0b97070cde69-470ea12f-a05e-412b-ad18-69e4cdf3ab87-v1.png?transparent=1&palette=1&width=246)

Championed By: Jon Jandoc @jjandoc 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by maximbert** [comment]
Oooh, this is close to me! I was gonna trek to the west side, but this is perfect. See you there.
