### ISSUE TITLE
Calling All Champions - November 7th, 2023

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#388]
Hey Everyone,

The next first Tuesday of the month is November 7th, 2023
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Santa Monica
Baldwin Hills / Crenshaw / Leimert Park
Atwater Village / Eagle Rock

pinging previous champions...
@powernerd @StevenKitzes @gr2m @davidguttman @jarrettch @jcblw @JakeDluhy @jjandoc @swatana3 @ultamatt

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by machikoyasuda** [comment]
@jjandoc Hey Jon, I saw that you hosted the Eagle Rock lunch last month. I'd love to help co-host another Eagle Rock lunch inn November!

**Comment by gr2m** [comment]
Here we go again: https://github.com/jsla/lunch.js/issues/389

**Comment by anguspiv** [comment]
Hey Folks,

Thanks so much for helping Lunch.js to keep going, couldn't do it without you! Next Lunch.js is Dec. 5th, 2023 #391. So go ahead and get your local lunches setup! Just one more before the end of the year!
