### ISSUE TITLE
Eagle Rock - November 7, 2023

### ISSUE THREAD

**Issue by jjandoc** [jsla/lunch.js#390]
# Eagle Rock
### @ Taco/Social, 1627 Colorado Blvd, Los Angeles, CA 90041

![bitmoji](https://sdk.bitmoji.com/render/panel/8b681f55-6f51-49db-87cb-0b97070cde69-470ea12f-a05e-412b-ad18-69e4cdf3ab87-v1.png?transparent=1&palette=1&width=246)

Championed By: Jon Jandoc @jjandoc 

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by machikoyasuda** [comment]
Would love to attend!

ps. @aroduribe come with!

**Comment by aroduribe** [comment]
> Would love to attend!
> 
> ps. @aroduribe come with!

I'm free. See ya there @machikoyasuda

**Comment by maximbert** [comment]
I'll be there as well 👋

**Comment by machikoyasuda** [comment]
@boovius

**Comment by savetheclocktower** [comment]
I'll try very hard to make this — it's long past time for me.

**Comment by machikoyasuda** [comment]
Thanks for hosting @jjandoc!

and great to meet you @maximbert. 

Looks like I'll be hosting a Pasadena one next month, because we have quite a few Pasadena folks. Would love to organize December's. Keep your eyes peeled.
