### ISSUE TITLE
Calling All Champions - February 6, 2024

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#393]
Hey Everyone,

Welcome back, and happy new year! 🥳 

The next first Tuesday of the month is February 6, 2024
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Santa Monica
Baldwin Hills / Crenshaw / Leimert Park
Atwater Village / Eagle Rock

pinging previous champions...
@powernerd @StevenKitzes @gr2m @davidguttman @jarrettch @jcblw @JakeDluhy @jjandoc @swatana3 @ultamatt @machikoyasuda

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by danvgar** [comment]
This will be my first one! Excited to participate. I'm based in Alhambra/Pasadena/626 area. Happy to discuss champion duties and how I can help. @anguspiv

**Comment by danvgar** [comment]
> This will be my first one! Excited to participate. I'm based in Alhambra/Pasadena/626 area. Happy to discuss champion duties and how I can help. @anguspiv

Ah disregard, just found [CONTRIBUTING.md](https://github.com/jsla/lunch.js/blob/master/CONTRIBUTING.md). I will review it later and see if I can jump in!

**Comment by machikoyasuda** [comment]
@danvgar Hey Dan - Would you like to be a co-host for the Feb. Pasadena event? In December, we hosted it at Dog Haus in Old Pasadena and got roughly 15-20 attendees: https://github.com/jsla/lunch.js/issues/392

Would love to have you as a co-host and get even more attendees this time around!

**Comment by gr2m** [comment]
Let's go Baldwin Hills / Crenshaw / Leimert Park: #394 - new location! Y'all love it!

**Comment by danvgar** [comment]
> @danvgar Hey Dan - Would you like to be a co-host for the Feb. Pasadena event? In December, we hosted it at Dog Haus in Old Pasadena and got roughly 15-20 attendees: #392
> 
> Would love to have you as a co-host and get even more attendees this time around!

Yes happy to co-host an upcoming lunch, feel free to @ me on the Slack!

**Comment by feemcgill** [comment]
Would love to meet up east side Pasadena etc!

**Comment by anguspiv** [comment]
Thanks everyone for your help in championing another great Lunch.js! I created the next call for champions, for March 5th! #397 
When you have a chance, please go ahead and create your local event and lets spread the news. 
You guys are awesome and I really appreciate all your help!
