### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - February 6th, 2024

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#394]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Gregor Martynus @gr2m

New location! ORA is what used to be Hot and Cold Coffee, it's a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

**Comment by cloudbring** [comment]
I'm coming. I haven't been to a jsla event since well before the pandemic.

**Comment by gr2m** [comment]
Cool! Bring friends! See you there!

**Comment by gloriliale** [comment]
I'll be there!

**Comment by jarrettch** [comment]
I think I can make it

**Comment by gr2m** [comment]
I'm looking forward to see you all! There is a K Line metro station right around the corner if you want to come with metro:
https://www.google.com/maps/dir/ORA,+4331+Degnan+Blvd,+Los+Angeles,+CA+90008/Leimert+Park+Station,+4330+Crenshaw+Blvd,+Los+Angeles,+CA+90008/@34.0046998,-118.3328583,19z/data=!3m2!4b1!5s0x80c2b78826cd0cf9:0x83c223b7ef193e3!4m14!4m13!1m5!1m1!1s0x80c2b98d07565037:0xb73d049306f0f296!2m2!1d-118.3318369!2d34.0050846!1m5!1m1!1s0x80c2b767060a1a27:0x7d0e000ce0c2171c!2m2!1d-118.3327019!2d34.0045911!3e2?entry=ttu

And if you need to a place to do some working you can work at Ora and come co-work with me at my Coworking Space across the metro station: https://themetaphorclub.com/

**Comment by gr2m** [comment]
I'm at the first to table on the right, wearing a yellow jacket

**Comment by gr2m** [comment]
Damn I forgot to take a picture again! We had @gloriliale and @jarrettch attend! I hope to see you again next time! Ora is a great space to meet, eat, have coffee, work, and just hangout!

**Comment by jarrettch** [comment]
i was in such a rush i forgot about the picture @gr2m. thanks for setting it up again and it was a pleasure meeting you @gloriliale! great conversation.
