### ISSUE TITLE
🌹 🚃 🚲 Pasadena - February 6, 2024

### ISSUE THREAD

**Issue by machikoyasuda** [jsla/lunch.js#395]
# Pasadena
### @ [Dog Haus](https://doghaus.com/) in Old Pasadena on [Green St. and `Big Bang Theory Way`](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu)

Fast casual. Good bike parking, large outdoor eating area _and_ a large indoor area in case it rains ☔ , very close to **A Line - Del Mar Station**, next to paid and street car parking. Close to cafes for co-working afterwards.

Menu: https://doghaus.com/menu/ - vegetarian, vegan options available.

Championed by: @machikoyasuda 

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by machikoyasuda** [comment]
It's Lunch.js again folks 🎉 

@savetheclocktower @cnk @maximbert @boovius @kangkyu @ericrwolfe @jjandoc @xta @dannyk08 @anguspiv @aahx @ClarisseNicole8 @jorgerro @JRHutson @matikin9 @max-mapper 

Please invite your coding friends in the Pasadena/SGV/NELA areas.

**Comment by sheriffderek** [comment]
I can make it.

**Comment by matikin9** [comment]
yay @machikoyasuda!  I'm going to try to make it.  I've put it on my calendar.

**Comment by danvgar** [comment]
Thank you so much for setting up the issue, @machikoyasuda ! Passing this along to my network!

**Comment by machikoyasuda** [comment]
@feemcgill

**Comment by nyarly** [comment]
Marking my calendar

**Comment by cityhubla** [comment]
@matikin9 pinged me, and I'm down!

**Comment by ClarisseNicole8** [comment]
I'll be there!

**Comment by NolanChan** [comment]
Will be there!

**Comment by junjun107** [comment]
I will be there too

**Comment by aahx** [comment]
I'll be there as well

**Comment by Philc90** [comment]
I'm tentatively interested, if I can take off early from work

**Comment by alexlitel** [comment]
Very late, but just saw this a little earlier on the LA Dev & Design group. Will try to make it tomorrow if I can.

**Comment by ClarisseNicole8** [comment]
I won't be able to make it, after all. I had something come up.

**Comment by machikoyasuda** [comment]
Hello! It's rainy, but we're still here! We are sitting *inside* at the large table behind the bar. Come find us 👋

**Comment by kurikurichan** [comment]
@machikoyasuda I can't make it today anymore but will definitely come to the next one :)

**Comment by junjun107** [comment]
The heavy rain ruined my schedule today. Sorry I can't make it 😞. I will definitely go to the next one.

**Comment by cnk** [comment]
Hope everyone had a good time. I didn't make it this round but hope to see you next month.

**Comment by feemcgill** [comment]
Dang missed it! Hope you all are staying cozy!

**Comment by cityhubla** [comment]
Thanks @machikoyasuda for getting us all together for lunch!

I mentioned to some folks at the lunch about maptimeLA and a board game night

The board game night is this Friday at the coworking space I work at in Chinatown, [Studious Coworking](https://studious.work/). We play many games, with social party games from Codenames to Cataan to very long games like Star Trek Ascendency. They post events here, [Chinatown Coworking Meetup](https://www.meetup.com/la-chinatown-coworking-community/) . They have open desks available if anyone wants to work in Chinatown!

@matikin9 and I also host maptimeLA, a beginner friendly meetup group where we learn to make maps with open source tools and learn to code as well, we're hosting a workshop every month [maptimeLA meetup page](https://www.meetup.com/maptimela/

**Comment by danvgar** [comment]
Yes thank you, @machikoyasuda ! This was a great first JSLA for me, excited to join more in the future and meet those I didn't get to today

And thank you for those links, @cityhubla ! Those sound amazing, I'll definitely check them out. Is it okay to share with my network as well?

**Comment by machikoyasuda** [comment]
thanks for coming all!

if someone wants to organize the March lunch, i'd greatly appreciate it - as i'll be on leave for a few months 👋

**Comment by cityhubla** [comment]
@danvgar sure! share away!
