### ISSUE TITLE
Pasadena / South Pasadena - March 5, 2024 

### ISSUE THREAD

**Issue by danvgar** [jsla/lunch.js#396]
# Pasadena / South Pasadena
### Location voting options below! Use reaction emojis as votes

Championed By: @danvgar

Vote:
- 🎉 [Dog Haus in Old Pasadena on Green St. & Big Bang Theory Way](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu) - Fast casual. Good bike parking, wide outdoor space, very close to A Line - Memorial Park Station, has paid and street car parking. Close to cafes for co-working afterwards.

If you are planning to attend subscribe to the issue to get notifications for new comments.

**Comment by nyarly** [comment]
Ooh, it's tomorrow already

**Comment by danvgar** [comment]
> Ooh, it's tomorrow already

Woops, sorry for not updating this! Thank you for the reminder, @nyarly !

Looks like everyone voted for Dog Haus, so we will be there at 12:30pm! 

93 E Green St, Pasadena, CA 91105

**Comment by sheriffderek** [comment]
OK. Looks like I'll be the one holding down the fort. 

I'll be there by 12pm.

See you all there! : )

**Comment by prolixmagus** [comment]
I'll be there too! Newbie here.

**Comment by sheriffderek** [comment]
I didn't have a cool JSLA hat!! So, I bought a big yellow duck.

![IMG_6686](https://github.com/jsla/lunch.js/assets/2066617/779886eb-dc64-4e6c-a18e-bcd29e507c43) - So, if you see that duck! That's JSLA today. :)

The weather is nice enough - and the tables outside seem better than the smaller booths that kinda broke people up last time.

**Comment by nyarly** [comment]
Sorry to miss this time - things came up

**Comment by sdeep27** [comment]
great time! thanks for organizing
