### ISSUE TITLE
Calling All Champions - March 5th, 2024

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#397]
Hey Everyone,

The next first Tuesday of the month is March 5th, 2024
Please create new issues when you get the chance.

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Santa Monica
Baldwin Hills / Crenshaw / Leimert Park
Atwater Village / Eagle Rock
Old Town Pasadena

pinging previous champions...
@StevenKitzes @gr2m @davidguttman @jarrettch @gr2m @danvgar
@machikoyasuda

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by danvgar** [comment]
Link to Pasadena / South Pasadena event for March 2024 available here! #396

**Comment by anguspiv** [comment]
Hey everyone!
Thanks again for hosting your local Lunch.js! I created the next Call for Champions #399 Feel free to go ahead and create your local events for next month!
