### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - March 5th, 2024

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#398]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Gregor Martynus @gr2m

New location! ORA is what used to be Hot and Cold Coffee, it's a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

**Comment by jarrettch** [comment]
See ya there!

**Comment by ldeavila** [comment]
I'll join. See you there.

**Comment by gr2m** [comment]
Great looking forward to meeting you!

**Comment by gr2m** [comment]
I'm here, at the table right at the entry

**Comment by ldeavila** [comment]
Was good meeting everyone. See y'all next time.

**Comment by jarrettch** [comment]
Likewise! Great lunch and chat. Hope to see y'all again in April!

**Comment by mwrather** [comment]
Great to talk to you all!

**Comment by gr2m** [comment]
It was great meeting y'all! Hope to see you all on April 2nd!

![Image](https://github.com/jsla/lunch.js/assets/39992/6e121a59-e6b7-49b0-a65f-087093d80e14)

**Comment by gr2m** [comment]
Here we go again: April 2!
https://github.com/jsla/lunch.js/issues/400
