### ISSUE TITLE
West Hollywood - August 2nd, 2016

### ISSUE THREAD

**Issue by davidguttman** [jsla/lunch.js#4]

**Comment by mrsmuneton** [comment]
I'm all about it! 
@temojin
@krainboltgreene

What do you say want to make this happen?  @temojin what was that restaurant you had mentioned?

also @krainboltgreene thanks for the Babel fun yesterday!

**Comment by krainboltgreene** [comment]
Sounds great.

**Comment by mrsmuneton** [comment]
@krainboltgreene wheres good to eat, want to do something like Barney's Beanery, or is there another place that you would recommend?

**Comment by mrsmuneton** [comment]
Lets do 12:30, I look forward to seeing anyone who can make it!

**Comment by mrsmuneton** [comment]
@krainboltgreene hope to see you at 12:30 at Barney's Beanery, looking forward to talking more!

**Comment by krainboltgreene** [comment]
My crew  (aka the wolfers) will be dropping by, but not eating. We've got
an interview lunch soon after!

**Comment by mrsmuneton** [comment]
that sounds awesome!  looking forward to seeing you wolfers =)

**Comment by mrsmuneton** [comment]
@krainboltgreen had a great time at lunch! Thanks for bringing your crew and making the first West Hollywood lunch.js.la a thing!!!

**Comment by temojin** [comment]
totally missed this! I started seeing the mentions about an hr before but I was not in West Hollywood. Hope you had a great event! See you next time!
