### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - April 2, 2024

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#400]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Gregor Martynus @gr2m

ORA is a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

**Comment by ldeavila** [comment]
See ya there.

**Comment by markpinero** [comment]
Will be there!

**Comment by jarrettch** [comment]
See ya there!

**Comment by gr2m** [comment]
It was wonderful to see all again!

![Image](https://github.com/jsla/lunch.js/assets/39992/ce8b7b4d-7e5d-4455-81a2-532bc99183b8)

**Comment by mwrather** [comment]
@ldeavila @gr2m and @jarrettch -- here's the [Remix meetup](https://www.meetup.com/los-angeles-remix-meetup/events/299753014]) I was talking about — it's Sunday in case you want to come.

**Comment by ldeavila** [comment]
Thanks for this @mwrather . Signed up. I may use Remix on a micro side project.

**Comment by gr2m** [comment]
here we go again: https://github.com/jsla/lunch.js/issues/403
