### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - May 7, 2024

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#403]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Gregor Martynus @gr2m

ORA is a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

**Comment by ldeavila** [comment]
I'm in.

**Comment by ldeavila** [comment]
Also, I started learning Remix. Maybe we can add this as a topic of conversation? Having conversation topics may help draw in other attendants.

**Comment by gr2m** [comment]
all topics are welcome! Happy to chat about it and to learn from your experiences.

**Comment by Spiteless** [comment]
I'm coming for the first time :)

**Comment by quipcode** [comment]
interested and planning on attending! Thanks, @ldeavila for sharing this 👍

**Comment by gr2m** [comment]
Yay new people, I'm looking forward to meet you all!

**Comment by partapparam** [comment]
Looking forward to it!

**Comment by jarrettch** [comment]
I'll be there!

**Comment by gr2m** [comment]
Ora now has 50% discount on all coffee drinks 8am-9am! Come and get a great cappuccino for <$3!

**Comment by jarrettch** [comment]
Not gonna make it after all. had something important come up. 😔

**Comment by Spiteless** [comment]
Just got here, gonna get something to eat :)

**Comment by partapparam** [comment]
Sorry, have to miss this as well everyone. Hope to catch the next one!

**Comment by quipcode** [comment]
Not gonna be able to make this one either

**Comment by ldeavila** [comment]
Good seeing some new faces. Missed seeing the regulars.

**Comment by gr2m** [comment]
I forgot to take the picture! It was great seeing new faces. See you all next time!

**Comment by gr2m** [comment]
I'll be out of town on June 4th, would someone else like to host the next lunch.js at Ora? There is really not much to do, just create a new issue, mention the issue here and in #405, and just show up and have lunch 😁
