### ISSUE TITLE
🌹 🚃 🚲 Pasadena - May 7, 2024

### ISSUE THREAD

**Issue by danvgar** [jsla/lunch.js#404]
# Pasadena
### @ [Dog Haus](https://doghaus.com/) in Old Pasadena on [Green St. and `Big Bang Theory Way`](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu)
Fast casual. Good bike parking, large outdoor eating area _and_ a large indoor area in case it rains ☔ , very close to **A Line - Del Mar Station**, next to paid and street car parking. Close to cafes for co-working afterwards.

Menu: https://doghaus.com/menu/ - vegetarian, vegan options available.

Championed by: @danvgar (Feel free to message me on Slack if anyone else wants to take over)

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by danvgar** [comment]
This is in a few days! Don't forget to invite your coding friends in the Pasadena/SGV/NELA areas!

@machikoyasuda @sheriffderek @matikin9 @feemcgill @nyarly @cityhubla @clarissenicole8 @nolanchan @junjun107 @aahx @philc90 @alexlitel @kurikurichan @cnk @davidwiese @ericwolfe @savetheclocktower @augustnmonteiro @prolixmagus @thealinamichelle @andrewjackp @jessedevs @cnk

**Comment by danvgar** [comment]
Just got here! Sitting outside in a white hat. Come by and say hi!

**Comment by dcotelessa** [comment]
I'm here as well

**Comment by danvgar** [comment]
Thank you everyone for coming out!! 🎉
