### ISSUE TITLE
Santa Monica - April 4th 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#41]
# Santa Monica
### @ [N.Y. & C. Pizza](https://www.yelp.com/biz/ny-and-c-pizza-santa-monica)

Let's vote to see where we're eating tomorrow. This is a Shotgun Poll!
[Mainland Poke](https://www.yelp.com/biz/mainland-poke-shop-los-angeles) $$ :tada:
[Flower Child](https://www.yelp.com/biz/flower-child-santa-monica) $$ :heart:
[N.Y. & C. Pizza](https://www.yelp.com/biz/ny-and-c-pizza-santa-monica) $$  :smile:

Championed By: Nate Lubeck @etanlubeck

**Comment by ashwell** [comment]
@etanlubeck @jcblw @anguspiv 

can any of you pick this up? I'm pretty swamped right now (while also suffering from decision fatigue)

**Comment by anguspiv** [comment]
I work up in Thousand Oaks now, so I'm out

**Comment by gavindoughtie** [comment]
Firehouse? I'd be down.

**Comment by JMSantos94** [comment]
N.Y. & C. Pizza +1

**Comment by etanlubeck** [comment]
I'm here. Sitting at the tall tops. Head count!

**Comment by jadware** [comment]
on my way

**Comment by ricklesgibson** [comment]
On my way as well

**Comment by etanlubeck** [comment]
Cheers! See you guys next month

**Comment by etanlubeck** [comment]
Heyo! Time to pick a spot for next month! https://github.com/jsla/lunch.js/issues/49
