### ISSUE TITLE
🌹 🚃 🚲 Pasadena - Aug 6, 2024

### ISSUE THREAD

**Issue by danvgar** [jsla/lunch.js#412]
# Pasadena
### @ [Dog Haus](https://doghaus.com/) in Old Pasadena on [Green St. and `Big Bang Theory Way`](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu)
Fast casual. Good bike parking, large outdoor eating area _and_ a large indoor area in case it rains ☔ , very close to **A Line - Del Mar Station**, next to paid and street car parking. Close to cafes for co-working afterwards.

Menu: https://doghaus.com/menu/ - vegetarian, vegan options available.

Championed by: @danvgar (Feel free to message me on Slack if anyone else wants to take over)

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by danvgar** [comment]
@machikoyasuda @sheriffderek @matikin9 @feemcgill @nyarly @cityhubla @clarissenicole8 @nolanchan @junjun107 @aahx @philc90 @alexlitel @kurikurichan @cnk @davidwiese @ericwolfe @savetheclocktower @augustnmonteiro @prolixmagus @thealinamichelle @andrewjackp @jessedevs @cnk @dcotelessa @evanshortiss @uptownhr

**Comment by danvgar** [comment]
Even if you haven't been before, all are welcome! Come make friends!

**Comment by JesseDevs** [comment]
I haven’t been to one of these meetups yet, but planning to make an effort to be at this one. 

See you there!

**Comment by savetheclocktower** [comment]
I’m in.

**Comment by dcotelessa** [comment]
In!

**Comment by ClarisseNicole8** [comment]
I'm in.

**Comment by dcblair** [comment]
I'll be there! 🤘🏽

**Comment by adanaltamira** [comment]
I'll be there. Coming from Ojai, CA.

**Comment by anguspiv** [comment]
Ack sorry guys, work got busy and won't be able to make it today. I'll catch y'all again next month?

**Comment by dcblair** [comment]
Hey, y'all, I have an interview today. Won't be able to make it. :(

**Comment by ClarisseNicole8** [comment]
I'm not going to be able to make it today. See you all next month!

**Comment by danvgar** [comment]
Just got here! Let's meet inside in the back!

**Comment by savetheclocktower** [comment]
We’re at a big table inside. Air conditioning!

**Comment by danvgar** [comment]
Great seeing everyone again, as always! Here is the JSLA Slack link for those who didn't have it:

https://jsla.slack.com/join/shared_invite/zt-1nf1yc1f6-ohkEU1TqC3AuHTSiscYHmg
