### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - August 6, 2024

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#413]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Jarrett Harris @jarrettch 

ORA is a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

**Comment by gr2m** [comment]
:wave: I'll be there! Thanks for setting it up @jarrettch

**Comment by trilliumsmith** [comment]
Will also be there!

**Comment by quipcode** [comment]
will be there

**Comment by ldeavila** [comment]
75% chance that I'll be there.

**Comment by jarrettch** [comment]
Unfortunately I am sick. Y'all hold down the fort without me!

**Comment by trillium** [comment]
Ah, bummer, hope you feel better soon!

**Comment by gr2m** [comment]
Oh man I was looking forward to see you again! Let me know when you get better, we can meet then! Get well soon!!

**Comment by quipcode** [comment]
I made it to ORA, currently in a cubby hole. lmk if anyone else is coming

**Comment by ldeavila** [comment]
I'll be there.

**Comment by gr2m** [comment]
Coming on now. Black shirt with names of local streets and yellow backpack/shoes

**Comment by gr2m** [comment]
It was nice meeting y'all. ![image](https://github.com/user-attachments/assets/419633a9-564e-4093-a696-8bfe7d0b85fc)
