### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - September 3, 2024

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#416]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Jarrett Harris @jarrettch 

ORA is a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). Please let your champion know, or reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team) for any violation or incident, and we will take appropriate action.

**Comment by gr2m** [comment]
I'll be there!

**Comment by gr2m** [comment]
Hey I hope to see you tomorrow! I'll make the trip from Westwood just for y'all!

**Comment by jarrettch** [comment]
> Hey I hope to see you tomorrow! I'll make the trip from Westwood just for y'all!

On my way now!

**Comment by trillium** [comment]
Ah bummer. Tried to catch the end of today's meet but I think I just missed you all

**Comment by gr2m** [comment]
It was just @jarrettch and me and I had to take care of an incident. But @jarrettch was so kind and sit with me anyway. Thank you friend! Hope to see more of you next time!

**Comment by jarrettch** [comment]
@trillium yeah I stayed a little bit after @gr2m left but based on the timestamp I had probably just walked out when you came by. there's always next month!
