### ISSUE TITLE
Manhattan Beach - September 3, 2024

### ISSUE THREAD

**Issue by etnlbck** [jsla/lunch.js#417]
# Beach Cities (Redondo, Hermosa, Manhattan, El Segundo)
### @ [Islands Restaurant in Manhattan Village](https://maps.app.goo.gl/smxdZ8EFMA4atavY6)

Championed By: Nate Lubeck @etnlbck 

I'll be wearing a ball cap with an Aura character on it.
![aura](https://aglitch.art/cdn/shop/files/Aura_v2.png?width=80)

If you plan to attend, you can subscribe to the issue to get notifications for new comments.

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). Please let your champion know, or reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team) for any violation or incident, and we will take appropriate action.

**Comment by etnlbck** [comment]
Got a spot on the patio in the cor ner

**Comment by teenwolfblitzer** [comment]
I totally forgot this was happening coming out of the long weekend. Wish I could've made it 😞

**Comment by etnlbck** [comment]
Yeah, i figured that might be the case. But I wanted to get the party started. Lol. There's always next month. ✌️

[Nate Lubeck - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2r8owa)	[2r8owa]

On September 3, 2024 at 21:00 GMT, Kevin Chang ***@***.***> wrote:

I totally forgot this was happening coming out of the long weekend. Wish I could've made it 😞
