### ISSUE TITLE
Culver City - September 3rd, 2024

### ISSUE THREAD

**Issue by higgins** [jsla/lunch.js#418]
# Culver City
### Picnic @ Carlson Park, 12:30pm

Championed By: @higgins

I like making these events approachable to folks who like to bring their own food.
So, let's eat at Carlson Park in Culver City!

Good food options nearby if you prefer:
* [Jackson Market](https://www.jacksonmarketanddeli.com/menu) 🥪
* [Homestate](https://www.myhomestate.com/culvercity/) 🏡
* [Grain cafe](https://www.thegraincafe.com/) 🌱
* and plenty more!

I'll be the guy who looks kinda like his github profile but with a beard and no glasses. At one of the picnic tables

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). Please let your champion know, or reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team) for any violation or incident, and we will take appropriate action.

**Comment by trillium** [comment]
Planning on attending!

**Comment by funbunch** [comment]
Hoping to make this one!

**Comment by trillium** [comment]
Ah we forgot to take a photo!

**Comment by higgins** [comment]
> Ah we forgot to take a photo!

@trillium @funbunch @shinjonathan ...or did we?!
![lunchjs_sept](https://github.com/user-attachments/assets/01ef8827-2d09-4ea6-b077-e42e1400f5f1)

**Comment by trillium** [comment]
Right, my mistake

**Comment by danstepanov** [comment]
just finding this, will try to make the next one
