### ISSUE TITLE
Pasadena -  September 3, 2024

### ISSUE THREAD

**Issue by dcotelessa** [jsla/lunch.js#419]
# Pasadena
### @ [Dog Haus](https://doghaus.com/) in Old Pasadena on [Green St. and Big Bang Theory Way](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu)

Fast casual. Good bike parking, large outdoor eating area and a large indoor area in case it rains ☔ , very close to A Line - Del Mar Station, next to paid and street car parking. Close to cafes for co-working afterwards.

Menu: https://doghaus.com/menu/ - vegetarian, vegan options available.

Championed By: David Cotelessa @dcotelessa

If you are planning to attend subscribe to the issue to get notifications for new comments.

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). Please let your champion know, or reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team) for any violation or incident, and we will take appropriate action.

**Comment by ClarisseNicole8** [comment]
I'm in!

**Comment by savetheclocktower** [comment]
I'll be there.

**Comment by ClarisseNicole8** [comment]
I had a work meeting come up and I won't be able to make it today!

**Comment by EthanEFung** [comment]
Nice to meet y'all yesterday! Thanks @dcotelessa for hosting.
