### ISSUE TITLE
DTLA - April 4th 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#42]
# DTLA
### @ Guisados

541 S Spring St (in the Spring Arcade Building)

Find Me: I'll be wearing black Nikes and a black cap 👀 or you can text me at 323.246.9683
Championed By: @malinatran

**Comment by machikoyasuda** [comment]
i nominate @malinatran  :)

**Comment by malinatran** [comment]
count me in! 👍

**Comment by machikoyasuda** [comment]
@malinatran wanna choose a place for 4/4?

I like Guisados.

@matikin9 @LearningNerd @eirinikos @sogoiii more lunchjs downtown people :)

**Comment by eirinikos** [comment]
@machikoyasuda I second and ❤️  Guisados! but @malinatran you should choose a place!

April 4th -- Election Day yet again.

**Comment by matikin9** [comment]
YES!

**Comment by LearningNerd** [comment]
I'll try to make it again, and totally happy with Guisados! :)

**Comment by eirinikos** [comment]
tagging @jdorfman @kennethlee @plantprojects

**Comment by jdorfman** [comment]
Down as a clown Charlie Brown

**Comment by kennethlee** [comment]
Doubt I can make it, but I'll definitely try :P

**Comment by eirinikos** [comment]
@iwilliams and @ozywuli from PXL Bros are joining 🌮

**Comment by malinatran** [comment]
# GUISADOS it is! won by popular vote ✅ 
### address: 541 s spring st in the spring arcade bldg 
### i'll be wearing black nikes and a black cap 👀

**Comment by shampine** [comment]
I will try to make it. Also will see if anyone from our office is interested.

**Comment by ashwell** [comment]
@malinatran thanks for championing the event! I'll add you as a collaborator

**Comment by LearningNerd** [comment]
Pinging @howdyjessie who's also downtown I believe and who I really want to catch up with again soon! :) and @murriel is working downtown now too!! :) alsooo @VincentG123 isn't far away!

**Comment by murriel** [comment]
Sounds great, thanks for the note @LearningNerd! Work schedule permitting I would definitely love to make it down. Also completely unrelated if anyone is interested in playtesting my company's VR Application this Saturday we are looking for a few more volunteers :)

**Comment by matikin9** [comment]
@murriel what time?! are you looking for specific types of users?  i'm a total n00b with VR :D

**Comment by VincentG123** [comment]
I'll do my best to make it! I'm assuming public transit is the way to go... lol

**Comment by murriel** [comment]
@matikin9 there are a few times throughout the day, but definitely open and welcome to beginners! Actually it's pretty great for people not familiar with VR because the idea is for this to be accessible to everyone out there :) Will send you a message ;) Also sorry all but prob working through lunch today, crunch time. :( but hoep to make the next one!

**Comment by jdorfman** [comment]
Here in open shirt
