### ISSUE TITLE
Calling All Champions - Oct. 1, 2024

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#420]
Hey Everyone,

The next first Tuesday of the month is Oct. 1, 2024
Please create new issues when you get the chance.

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). We ask that our champions help guests adhere to the Code of Conduct, and let guests know they can reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team). 

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Santa Monica
Baldwin Hills / Crenshaw / Leimert Park
Atwater Village / Eagle Rock
Pasadena
Manhattan Beach

pinging previous champions...
@dcotelessa @higgins @gr2m @etnlbck @jarrettch 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by danvgar** [comment]
Didn't see one for October yet, happy to champion again!

https://github.com/jsla/lunch.js/issues/422

**Comment by jarrettch** [comment]
Baldwin Hills/Crenshaw/Leimert Park:
- https://github.com/jsla/lunch.js/issues/421
