### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - October 1, 2024 

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#421]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Jarrett Harris @jarrettch 

ORA is a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). Please let your champion know, or reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team) for any violation or incident, and we will take appropriate action.

**Comment by RadicalRoy** [comment]
Will check it out!

**Comment by danstarns** [comment]
Sounds fun!

**Comment by gr2m** [comment]
Danmn I'm sorry I missed it's lunch.js day and I won't be able to make it today! Sorry to miss you all!

**Comment by jarrettch** [comment]
I'm here at a smaller table in the front. Pink polo and hat.

**Comment by trillium** [comment]
Was a great meet!

**Comment by jarrettch** [comment]
Great conversation! Thanks for coming out @trillium @RadicalRoy! [20241001_134150.jpg](https://github.com/user-attachments/assets/dd3cc873-5311-462a-afe6-8b5f2afa1add)
