### ISSUE TITLE
🌹 🚃 🚲 Pasadena - Oct 1, 2024

### ISSUE THREAD

**Issue by danvgar** [jsla/lunch.js#422]
# Pasadena
### @ [Dog Haus](https://doghaus.com/) in Old Pasadena on [Green St. and `Big Bang Theory Way`](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu)
Fast casual. Good bike parking, large outdoor eating area _and_ a large indoor area in case it rains ☔ , very close to **A Line - Del Mar Station**, next to paid and street car parking. Close to cafes for co-working afterwards.

Menu: https://doghaus.com/menu/ - vegetarian, vegan options available.

Championed by: @danvgar (Feel free to message me on Slack if anyone else wants to take over)

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by danvgar** [comment]
@machikoyasuda @sheriffderek @matikin9 @feemcgill @nyarly @cityhubla @clarissenicole8 @nolanchan @junjun107 @aahx @philc90 @alexlitel @kurikurichan @cnk @davidwiese @ericwolfe @savetheclocktower @augustnmonteiro @prolixmagus @thealinamichelle @andrewjackp @jessedevs @cnk @dcotelessa @evanshortiss @uptownhr

**Comment by danvgar** [comment]
Even if you haven't been before, all are welcome! Come make friends!

**Comment by dcotelessa** [comment]
I'm in.

**Comment by cnk** [comment]
It would be great to see everyone but I am out of town that day. See you all in November.

**Comment by prolixmagus** [comment]
I’ll be there!Sent from my iPhoneOn Sep 18, 2024, at 12:12 PM, temojin ***@***.***> wrote:﻿
put me as tentative

**Comment by ClarisseNicole8** [comment]
I am a tentative yes.

**Comment by nyarly** [comment]
I'm in

**Comment by jcandeli** [comment]
I'm in!

**Comment by kkchu791** [comment]
I'm in!

**Comment by danvgar** [comment]
Inside towards the back at the long table, wearing a white shirt!

**Comment by temojin** [comment]
It's today! I thought it was tomorrow :(

**Comment by danvgar** [comment]
Great seeing everyone again, as always! Here is the JSLA Slack link for those who didn't have it:

https://jsla.slack.com/join/shared_invite/zt-1nf1yc1f6-ohkEU1TqC3AuHTSiscYHmg

Feel free to connect and share LinkedIns and other info there as well
