### ISSUE TITLE
Calling All Champions - Dec. 3, 2024

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#423]
Hey Everyone,

The next first Tuesday of the month is Dec. 3, 2024
Please create new issues when you get the chance.

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). We ask that our champions help guests adhere to the Code of Conduct, and let guests know they can reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team). 

Note that Lunch.js runs much smoother when each location has two champions. Feel free to share champion duties with another member of your lunch location!

Previous Lunch Locations
Santa Monica
Baldwin Hills / Crenshaw / Leimert Park
Atwater Village / Eagle Rock

pinging previous champions...
@dcotelessa @higgins @gr2m @etnlbck @jarrettch

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in. Comment on this thread if you need me to remove you from the above list of previous champions.

If you want to start a new neighborhood Lunch.js check out the champion guide and comment here to get started!

**Comment by gr2m** [comment]
I'll host the Baldwin Hills event: https://github.com/jsla/lunch.js/issues/423. Looking forward to meet old and new friends!

**Comment by danvgar** [comment]
Woops, never saw this! Creating a Pasadena event now!

- https://github.com/jsla/lunch.js/issues/425

**Comment by anguspiv** [comment]
Hey Everyone!

The next lunch.js is up! #426 

Thanks for all your help this year with keeping Lunch.js going. Looking forward to another year, of meeting and learning from all you wondering folks!

--Angus
