### ISSUE TITLE
Baldwin Hills / Crenshaw / Leimert Park - December 3, 2024

### ISSUE THREAD

**Issue by gr2m** [jsla/lunch.js#424]
# Baldwin Hills / Crenshaw / Leimert Park
### @ [ORA](https://maps.app.goo.gl/EXwxq7sfNypE3uAS7)

Championed By: Jarrett Harris @gr2m 

ORA is a super nice place with great coffee, healthy food options and internet to work there.

If you are planning to attend please leave a comment!

As a reminder, Lunch.js events follow the [JS.LA Code of Conduct](https://js.la/code-of-conduct). Please let your champion know, or reach out to [Angus Perkerson](mailto:angusp@angusp.com) or any [JS.LA Team Member](https://js.la/team) for any violation or incident, and we will take appropriate action.

**Comment by trillium** [comment]
I'll be attending!

**Comment by gr2m** [comment]
Was just @trillium and me today, and I was the worst host coming late and leaving early, really sorry for that! I promise next time I'll be the there the full hour again!

**Comment by jarrettch** [comment]
Don't be too hard on yourself @gr2m! Thank you for picking up December and hosting. Hopefully I can host and make it in January depending on work. Glad you made it @trillium!

**Comment by gr2m** [comment]
Here we go again!
