### ISSUE TITLE
🌹 🚃 🚲 Pasadena - Dec 3, 2024

### ISSUE THREAD

**Issue by danvgar** [jsla/lunch.js#425]
# Pasadena
### @ [Dog Haus](https://doghaus.com/) in Old Pasadena on [Green St. and `Big Bang Theory Way`](https://www.google.com/maps/place/Dog+Haus/@34.145588,-118.148216,17.16z/data=!3m1!5s0x80c2c3704b11f8c1:0x19535fb10274966f!4m6!3m5!1s0x80c2c3703bee7813:0xd69f8b62d49eaca1!8m2!3d34.1446723!4d-118.148375!16s%2Fg%2F1hc4np5gw?entry=ttu)
Fast casual. Good bike parking, large outdoor eating area _and_ a large indoor area in case it rains ☔ , very close to **A Line - Del Mar Station**, next to paid and street car parking. Close to cafes for co-working afterwards.

Menu: https://doghaus.com/menu/ - vegetarian, vegan options available.

Championed by: @danvgar (Feel free to message me on Slack if anyone else wants to take over)

If you are planning to attend, subscribe to the issue to get notifications for new comments.

**Comment by danvgar** [comment]
@machikoyasuda @sheriffderek @matikin9 @feemcgill @nyarly @cityhubla @clarissenicole8 @nolanchan @junjun107 @aahx @philc90 @alexlitel @kurikurichan @cnk @davidwiese @ericwolfe @savetheclocktower @augustnmonteiro @prolixmagus @thealinamichelle @andrewjackp @jessedevs @cnk @dcotelessa @evanshortiss @uptownhr @adanaltamira @xta @dcblair

**Comment by savetheclocktower** [comment]
Leaving town for a week that very morning! I'll make the next one.

**Comment by dcotelessa** [comment]
In.

**Comment by davidwiese** [comment]
Going to try to make this one

**Comment by ClarisseNicole8** [comment]
I will try to make this one.

**Comment by FatCatLikesBeer** [comment]
Ooo I'm new here I want to go!

**Comment by danvgar** [comment]
> Ooo I'm new here I want to go!

Come by! All are welcome!

**Comment by yanalina** [comment]
I will come, I'm also new!

**Comment by sheriffderek** [comment]
On my way. Going for early instead of late this time! ;)

**Comment by danvgar** [comment]
Surprisingly busy! I'll be outside in a denim jacket and mustard(??) hoodie

**Comment by cnk** [comment]
Good to see everyone! Hope some of you will be inspired to join our new book group - Mondays 6 PM on Zoom. See https://jsla.slack.com/archives/C03PZLMJ6/p1729616197632109 for details.

**Comment by davidwiese** [comment]
Nice meeting everyone today! If you'd like to connect on linkedin you can
find me here <https://www.linkedin.com/in/davidwiesedev>

**Comment by danvgar** [comment]
Appreciate everyone joining!! Below is the slack channel for those who haven't joined yet.

https://jsla.slack.com/join/shared_invite/zt-1nf1yc1f6-ohkEU1TqC3AuHTSiscYHmg
