### ISSUE TITLE
West Hollywood - April 4th, 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#44]
# West Hollywood
### @ TBA

Championed By: Rachelle Gray @rrrapture

Vote on the location!
:laughing: [Luv2Eat Thai Bistro](https://www.yelp.com/biz/luv2eat-thai-bistro-los-angeles)
:tada: [Wirtshaus](https://www.yelp.com/biz/wirtshaus-los-angeles)

**Comment by Rrrapture** [comment]
Hello WeHo and Hollywood folks! 

Tagging @davidguttman  @mrsmuneton @temojin @krainboltgreene @lmordell  @lsfisher @maytaldahan

Know of anyone else in this area that might be interested in attending?

**Comment by davidguttman** [comment]
I'm in!

**Comment by jadware** [comment]
Wirsthaus!

**Comment by Rrrapture** [comment]
Hey all, 

I just saw on the Wirsthaus website that they are only open for lunch Friday-Sunday. @davidguttman @jadware want to reschedule or do you have another lunch idea on La Brea?

**Comment by Rrrapture** [comment]
Cancelling this month's lunch, we'll try again in May. Open to suggestions!
