### ISSUE TITLE
Calling All Champions - May 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#46]
## Hey `lunch.js` Champions! ##

The next first Tuesday of the month is `May 2nd, 2017`
Please create new issues when you get the chance.
## Current Champions ##
Culver City / Playa Vista - @machikoyasuda / @jarrettch ( #47 )
SF Valley - @anguspiv ( #48 )
Santa Monica - @etanlubeck ( #49 )
DTLA (Downtown) - @malinatran ( #50 )

## Locations with Champions Needed
West Hollywood

If you see a neighborhood not listed, it would be awesome if you would champion it! Just add a comment here to get started.

**Comment by malinatran** [comment]
I can do DTLA again if there's an interest :)

**Comment by machikoyasuda** [comment]
@xtine is interested in DTLA, @malinatran <3

**Comment by malinatran** [comment]
Yay, let's do it!
