### ISSUE TITLE
Culver City / Playa Vista - May 2nd, 2017 at  🕧 12:30

### ISSUE THREAD

**Issue by machikoyasuda** [jsla/lunch.js#47]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @jarrettch & @machikoyasuda

**Comment by machikoyasuda** [comment]
@aroduribe :)

**Comment by aroduribe** [comment]
I'll be there!

**Comment by jarrettch** [comment]
@gr2m @jimthoburn @derekmiranda @seanwestfall @derduher c'mon out next month y'all!

**Comment by gr2m** [comment]
I'll be out of town in May and half of June :( Note that I've been to phorage yesterday with my fam and the back room was filled with clutter. Maybe check in with them a few days before lunch.js to make sure it's free again :)

**Comment by jarrettch** [comment]
We will miss you again Gregor. Yeah that back room has had a bunch of supplies and stuff in it the last couple months. Luckily we've been able to take over that middle table but good point, maybe can't count on getting that table every month.

**Comment by Basscord** [comment]
I'll be there!

**Comment by seanwestfall** [comment]
yeah, I'm coming again too guys. Was great the last time.

**Comment by eveafeline** [comment]
I'll be there with a few friends ;)

**Comment by rouzbeh84** [comment]
gonna try and make it 👍

**Comment by jimthoburn** [comment]
Gonna try to make it too!

**Comment by jarrettch** [comment]
I just called and they said there's still a bunch of supplies in that private room. It has been like that all year. Sigh.

**Comment by machikoyasuda** [comment]
https://twitter.com/jsdotla/status/859513872750747648 :)
