### ISSUE TITLE
SF Valley - May 2nd, 2017 at 🕧 12:30

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#48]
# SF Valley
### @ [Public School 818](http://www.psontap.com/locations/ps818/)
15300 Ventura Blvd #102G
Sherman Oaks, CA 91403

Championed By: Angus Perkerson @anguspiv

Looking forward to meeting everyone there at Public School.

**Comment by ashwell** [comment]
cc: @remarks

**Comment by remarks** [comment]
We had our previous one at [Hamptons 818](https://www.yelp.com/biz/hamptons-818-sherman-oaks) but I'm down for either!

@SeanCox @sheelah

**Comment by anguspiv** [comment]
@remarks I've added Hamptons as a voting option. I'm have no preference as I only starting working in the area recently.

**Comment by anguspiv** [comment]
Hey Everyone, also for future reference, where are people located. SF Valley is a pretty large area in general, so there are enough people interested in smaller regions, we might split this group up some.

Me, I'm working out of Woodland Hills.

**Comment by SeanCox** [comment]
I think both places are good. I live in Burbank.

**Comment by sheelah** [comment]
Either is good! I'm in Sherman Oaks.

**Comment by anguspiv** [comment]
Since no-one really has a preference, I will keep it at Public School for now. Looking forward to seeing you all!

**Comment by anguspiv** [comment]
Hey Everyone,
Looking forward to seeing y'all. I'll be the guy with the yellow baseball cap, and blue and yellow hoodie.

**Comment by anguspiv** [comment]
Grabbed a table inside under the periodic table

**Comment by remarks** [comment]
Sorry everyone! Wanted to make it but I've been sick in bed for the past few days. I'll catch you all for the next one.

**Comment by anguspiv** [comment]
@remarks, @SeanCox @sheelah I've created the next lunch.js issue #52 so we can start talking about it, and maybe promoting it with other people.

**Comment by anguspiv** [comment]
Hey everyone, next event #67 !
