### ISSUE TITLE
Santa Monica - May 2, 2017 🍕 12:30pm

### ISSUE THREAD

**Issue by etanlubeck** [jsla/lunch.js#49]
# Santa Monica
### @ [Vitos Pizza](https://www.yelp.com/biz/vitos-pizza-santa-monica)

Championed By: Nate Lubeck @etanlubeck

## Whatup :pizza: and ![JavaScript Lovers](https://img.shields.io/badge/style-lovers-green.svg?style=plastic&label=javascript&colorA=000000&colorB=f5dd3d)

I'm looking for suggestions of pizza places to add to the poll for this month? I'm open to going to one of the pizza places we've been to in the past but also open to new suggestions.

[800 Degrees](https://www.yelp.com/biz/800-degrees-neapolitan-pizzeria-los-angeles) $$ :tada:
[Vitos Pizza](https://www.yelp.com/biz/vitos-pizza-santa-monica) $$ :smile:

**Comment by JMSantos94** [comment]
http://www.800degreespizza.com/ is good, but maybe a bit far for some.

**Comment by etanlubeck** [comment]
@JMSantos94 I'll add it to the poll. Thanks!

**Comment by etanlubeck** [comment]
Looking forward to kicking it with you all today!

**Comment by jadware** [comment]
On my way 15min
