### ISSUE TITLE
DTLA - May 2, 2017 🌮 12:30pm

### ISSUE THREAD

**Issue by malinatran** [jsla/lunch.js#50]
# DTLA
### @ [Guisados](http://www.guisados.co/menu/)
541 S Spring St, 
Los Angeles, CA 90013

Championed By: Malina Tran @malinatran

Just thought I'd switch it up! Are any folks down to check this place out? 😄 We can also go to Guisados if we have some die-hard Guisadians out there.

I'll be wearing a black hat and Jackie O sunglasses.

**Comment by jdorfman** [comment]
Down see you there

**Comment by xtine** [comment]
I haven't been to Guisados in a while, I would be down for that. 😋

**Comment by simonyangme** [comment]
I'd be very interested in Guisados :open_mouth:

**Comment by eirinikos** [comment]
See you all at Strada tomorrow <3

Tagging @arbonap @plantprojects @ozywuli @iwilliams !!

**Comment by arbonap** [comment]
Sounds good to me, can't wait to meet you all!

**Comment by malinatran** [comment]
I hear ya, @xtine + @simonyangme. Let's do Guisados instead! Strada also doesn't seem to have any veggie / vegan options? 🤔 Hope that's cool with you, @jdorfman, @eirinikos, + @arbonap.

**Comment by jdorfman** [comment]
It's beyond ok. It's literally downstairs from my apt. #happycamper

**Comment by matikin9** [comment]
Thanks @LearningNerd for reminding me about this!  See you all tomorrow!

**Comment by LearningNerd** [comment]
Yup I'm in! See you all again tomorrow! :)

**Comment by eirinikos** [comment]
I love Guisados!! See you all tomorrow ❤️

**Comment by ashwell** [comment]
How did lunch.js go in DTLA today?!

**Comment by jdorfman** [comment]
@ashwell nom nom nom NaN nom

**Comment by ashwell** [comment]
@jdorfman next time tweet us a pic of those tasty number noms!
