### ISSUE TITLE
Calling All Champions - June 6th 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#51]
## Hey `lunch.js` Champions! ##

The next first Tuesday of the month is `June 6th, 2017`
Please create new issues when you get the chance.
## Current Champions ##
Culver City / Playa Vista - @machikoyasuda / @jarrettch ( #54 )
SF Valley - @anguspiv ( #52 )
Santa Monica - @etanlubeck ( #53 )
Koreatown/Mid-Wilshire - @davidkim310 ( #55 )

## Locations with Champions Needed
DTLA (Downtown)
West Hollywood

If you see a neighborhood not listed, it would be awesome if you would champion it! Just add a comment here to get started.

**Comment by ashwell** [comment]
@machikoyasuda @jarrettch @anguspiv @etanlubeck @malinatran 

If you can't champion your location next month let us know so we can find someone to fill in!

**Comment by davidkim310** [comment]
Hey guys! New to the group! I would love to champion Koreatown - Mid-Wilshire area! Or if you guys need someone to fill in, I would be glad to!

**Comment by machikoyasuda** [comment]
@davidkim310 Koreatown <3

**Comment by ashwell** [comment]
Hey Champions, the first Tuesday in July is the 4th so we are going to do lunch.js a week later on the 11th.

See ticket #58 thanks!
