### ISSUE TITLE
SF Valley - June 6th, 2017 at 12:30pm

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#52]
# SF Valley
### @ [Hamptons 818](https://www.yelp.com/biz/hamptons-818-sherman-oaks) 
14917 Ventura Blvd
Sherman Oaks, CA 91403

Championed By: Angus Perkerson @anguspiv

**Comment by sheelah** [comment]
I'm good with Hamptons 818, but I'll throw out a few other options as well:

[Blu Jam Cafe](https://www.yelp.com/biz/blu-jam-cafe-sherman-oaks-2)
[Mendocino Farms](https://www.yelp.com/biz/mendocino-farms-sherman-oaks?osq=Mendocino+Farms)
[Carnival Restaurant](https://www.yelp.com/biz/carnival-restaurant-sherman-oaks) - middle eastern, really good hummus

**Comment by remarks** [comment]
👌

**Comment by remarks** [comment]
Anyone else available for lunch on this day? 😁

**Comment by SeanCox** [comment]
I hope to make it. Totally spaced on the last one.

**Comment by anguspiv** [comment]
Hey everyone,
I updated the location to Hamptons 818. Hope to see you there!

**Comment by sheelah** [comment]
I'm going to have to miss this one.  Hope to see you all @ the next one!

**Comment by ashwell** [comment]
Hope lunch.js SFV, I hope it was fun, note that the next lunch.js will be on July 11th

**Comment by anguspiv** [comment]
Hey Everyone checkout the next one #59
