### ISSUE TITLE
Santa Monica - June 6th, 2017 at 12:30pm

### ISSUE THREAD

**Issue by etanlubeck** [jsla/lunch.js#53]
# Santa Monica
### @ [Vito's Pizza](https://www.yelp.com/biz/vitos-pizza-santa-monica)

Championed By: Nate Lubeck @etanlubeck

Three options for next month are:
[Vito's Pizza](https://www.yelp.com/biz/vitos-pizza-santa-monica) :tada:
[The Curious Palate](http://www.thecuriouspalate.com/) :thumbsup:
[Mondo Taco](https://www.yelp.com/biz/mondo-taco-santa-monica-3) ❤️

**Comment by etanlubeck** [comment]
Got a couple options for lunch next month. Cast you vote and feel free to invite co-workers. Cheers!
@ricklesgibson @JMSantos94 @ashwell @jcblw @jadware @mnicole @dancingshell

**Comment by etanlubeck** [comment]
@ricklesgibson @jadware @dancingshell are you interested in participating?

**Comment by dancingshell** [comment]
How can we vote for tacos?

**Comment by ashwell** [comment]
@dancingshell now you can!

**Comment by etanlubeck** [comment]
See you guys tomorrow

**Comment by JMSantos94** [comment]
See you guys there!
Our team is going as well 😄

**Comment by etanlubeck** [comment]
Was great seeing everybody today.

**Comment by etanlubeck** [comment]
New lunch js is up - Cast your votes! https://github.com/jsla/lunch.js/issues/61
