### ISSUE TITLE
Culver City x Playa Vista - June 6th, 2017 at 12:30pm

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#54]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @jarrettch

**Comment by jarrettch** [comment]
Two weeks away guys who's in? @aroduribe @gr2m @jimthoburn @derekmiranda @seanwestfall @Basscord @eveafeline @rouzbeh84

**Comment by Basscord** [comment]
I'm in!

**Comment by aroduribe** [comment]
I'm adding it to my calendar. I'll go!

**Comment by jimthoburn** [comment]
Hooray!   :o)

**Comment by machikoyasuda** [comment]
i won't be able to attend this time around. thank you @jarrettch for holding it down.

**Comment by seanwestfall** [comment]
I'll be there again this time guys. 👍

**Comment by gr2m** [comment]
@seanwestfall we are not all guys ;) 

I can’t make it I'm still out of town, looking forward to see you again next time!

**Comment by derekmiranda** [comment]
i'll be there!!

**Comment by eveafeline** [comment]
I'll be there also!

**Comment by johntran** [comment]
@JackieCabinet and I will be there :)

**Comment by johntran** [comment]
It was good to see everyone!

@Basscord @seanwestfall @jarrettch @rouzbeh84 & Aaron(?may have butchered your name)
