### ISSUE TITLE
Koreatown/Mid-Wilshire - June 6th, 2017 at 12:30 PM

### ISSUE THREAD

**Issue by davidkim310** [jsla/lunch.js#55]
# Koreatown/Mid-Wilshire
### @ :tada: [City Center Food Court - Lots of variety](https://www.yelp.com/biz/city-center-food-court-los-angeles)

Championed By: David Kim @davidkim310

**Comment by tinachungshi** [comment]
City Center Food Court!

**Comment by davidguttman** [comment]
Looks like City Center is the winner?

**Comment by davidkim310** [comment]
City Center it is!

**Comment by OppaKimchee** [comment]
sounds good!

**Comment by ashwell** [comment]
Hope it was a good first-time lunch.js!

The next lunch.js will be on July 11th
