### ISSUE TITLE
Calling all Champions - July 11th 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#58]
## Hey `lunch.js` Champions! ##

The next first Tuesday of the month is `July 4th` since this is a holiday we plan to push lunch back a week and hold it on **`July 11th, 2017`**
Please create new issues when you get the chance.
## Current Champions ##
Culver City / Playa Vista - @jarrettch #60
SF Valley - @anguspiv #59
Santa Monica - @etanlubeck #61
DTLA - @davidkim310 #63
Burbank - @bradstemke #64
West Hollywood - @devwells

## Locations with Champions Needed
None! Unless you want to start a new neighborhood lunch.js!

If you see a neighborhood not listed, it would be awesome if you would champion it! Just add a comment here to get started.

**Comment by bradstemke** [comment]
Hello! I would like to champion Burbank next month. Commenting here to get started.

**Comment by ashwell** [comment]
Awesome @bradstemke! I'll go ahead and make sure you get added to the repo as a contributor so you can edit issue labels.

All you should need to do is create a new issue for Burbank, we have an issue template that should be easy to follow. If you have any questions you can comment here, or reach out through the js.la/slack lunch.js room, or PM me directly (@ashwell on slack as well)

**Comment by ashwell** [comment]
alright, @bradstemke you should have an invite to the repo from github, once you accept you should be all set!

**Comment by anguspiv** [comment]
Hey @bradstemke, once you make an issue. I would recommend commenting and linking to it in the SF Valley one. I know some of the folks that have come work closer to Burbank

**Comment by bradstemke** [comment]
Thanks so much! I will get that issue up very soon! 

Sounds good, I will drop a link in there as well, thanks!

**Comment by devwells** [comment]
Hi :) I can Champion West Hollywood! 
@ashwell

**Comment by ashwell** [comment]
Awesome @devwells I'll get you added as a contributor, feel free to create an issue for the West Hollywood group. There is an issue template to follow if you have any questions you can message me on the js.la/slack either in the lunchjs room or privately (I'm @ashwell on there too)

**Comment by ashwell** [comment]
Great lunch.js everyone! If you have any comments, questions, or concerns about how things are going/went let me know. You can find me on the [js.la slack](https://jsla.slack.com/messages/@ashwell/)
