### ISSUE TITLE
SF Valley  - July 11th 2017 @ 12:30 PM

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#59]
# SF Valley
### @ TBD

Championed By: Angus Perkerson @anguspiv

Its that time again to vote for a place to have lunch and talk shop. Please through your ideas out where to eat. And we will start voting in a week or so!

**Comment by bradstemke** [comment]
Hello! I created a Burbank lunch js if anyone is interested. Was told a few people might be. Thanks!

https://github.com/jsla/lunch.js/issues/64

**Comment by anguspiv** [comment]
🏏 🏏 🏏 ...

**Comment by anguspiv** [comment]
Welp, no one is interested soooo, I'll cancel this one

**Comment by anguspiv** [comment]
New event at #67
