### ISSUE TITLE
Culver City x Playa Vista - July 11th, 2017 at 12:30pm

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#60]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @jarrettch 

I'm fine with Phorage but figured we could open it up this time if we wanted to switch it up or just had a place they wanted to try out.

**Comment by 8bitDesigner** [comment]
I would like to selfishly 👍 this and say that Phorage is rad.

**Comment by jarrettch** [comment]
Haha, Phorage is indeed rad. Just wanted to give the option. Phorage it is!

**Comment by jarrettch** [comment]
Woah, this is tomorrow! Who's in?

@8bitDesigner @aroduribe @gr2m @jimthoburn @derekmiranda @seanwestfall @Basscord @eveafeline @rouzbeh84 @johntran @JackieCabinet

**Comment by gr2m** [comment]
sorry @jimthoburn and I will go to [the Santa Monica lunch.js](https://github.com/jsla/lunch.js/issues/61#issuecomment-314207101) tomorrow

**Comment by toiye** [comment]
I'm in.  Will try to bring another from the team too.

**Comment by ayurkows** [comment]
Phorage is right around the corner from me, will try to be there if nothing comes up 👍

**Comment by jaimemendozadev** [comment]
I'll be in the area. My first js.la lunch. Yay! 😄

**Comment by aroduribe** [comment]
I want to go but I have work 👎 we should plan a coffee.js...

**Comment by seanwestfall** [comment]
Hey guys, really wanted to come, but have an appointment today at 1:30 that I have to go to. So next month, I'll be sure to be there.

**Comment by johntran** [comment]
I won't be there. Sorry :( Company lunch

**Comment by 8bitDesigner** [comment]
Sorry all, had a small production fire come up; catch you next time!
