### ISSUE TITLE
Santa Monica - July 11, 2017 @ 12:30pm

### ISSUE THREAD

**Issue by etanlubeck** [jsla/lunch.js#61]
# Santa Monica
### @ [Sunny Blue](https://www.yelp.com/biz/sunny-blue-santa-monica) && Beach Park Picnic 

Championed By: Nate Lubeck @etanlubeck

It's that time again to vote for where we're eating and conversing!

[Taco Libre](https://www.yelp.com/biz/taco-libre-santa-monica-santa-monica?osq=tacos) $$ :smile: :taco:
[Stella Barra Pizzeria](https://www.yelp.com/biz/stella-barra-pizzeria-santa-monica?osq=Pizza) $$ :tada: 🍕  
[Bareburger](https://www.yelp.com/biz/bareburger-santa-monica) $$ :heart: 🍔 
[Sunny Blue](https://www.yelp.com/biz/sunny-blue-santa-monica) && Beach Park Picnic :thumbsup: :sushi:

![Sushi Party Dance](https://media1.giphy.com/media/EdSHevYJy1CH6/giphy.gif)

**Comment by etanlubeck** [comment]
@machikoyasuda I heard you may be down this way, now?

**Comment by machikoyasuda** [comment]
I will be there. How about Sunny Blue 🍙🍵 and a beach park picnic 🌴🌊? 

Sent from my iPhone

On Jun 16, 2017, at 1:45 AM, Nate Lubeck <notifications@github.com> wrote:

@machikoyasuda I heard you may be down this way, now?

**Comment by etanlubeck** [comment]
Woo! That's a good suggestion. I'll add that to the poll.

**Comment by jadware** [comment]
looks like sunny blue and bareburger are next to each other

sunny blue +1

**Comment by machikoyasuda** [comment]
also, @kpearson too. we're finally work neighbors 🏢

**Comment by gr2m** [comment]
I’m in :) Another good option for picnic to go is [Simply Salad](https://goo.gl/maps/7PoX1FfKgTD2). Both work for me

**Comment by jdorfman** [comment]
In but sorry @machikoyasuda I must go with Taco Libre $$ 😄 🌮

Did you get the memo? Tuesdays belong to Tacos.

**Comment by kpearson** [comment]
Down for whatever

**Comment by rouzbeh84** [comment]
had to retract my vote since i'm a maybe but if you'd like to include it to be the tiebreaker, I pick picnic & Sunny Blue

**Comment by etanlubeck** [comment]
Picnic it is!

**Comment by Basscord** [comment]
Wow looks like Santa Monica is the place to be this time. Count me in!

**Comment by gr2m** [comment]
@jimthoburn and I will be there :)

**Comment by machikoyasuda** [comment]
Hi all -- Meeting at Sunny Blue at 12:30 🍙  on 2728 Main St. & then walk to Ocean View Park 🏖 . See you!

**Comment by gr2m** [comment]
If you come late, see you at Ocean View Park

**Comment by ashwell** [comment]
Great beach side picnic everyone! Looking forward to next month!

**Comment by jimthoburn** [comment]
@Basscord and @sdillahey had some beautiful o-musubi from Sunny Blue…

![brian](https://user-images.githubusercontent.com/926616/28144704-035c2392-6722-11e7-9967-0ae155d0c337.jpg)

![stacey](https://user-images.githubusercontent.com/926616/28144710-087ad08a-6722-11e7-967b-a1aeb73cb81a.jpg)

![beach](https://user-images.githubusercontent.com/926616/28144876-fe0b07a4-6722-11e7-9b9d-a140d9bbdf0e.jpg)

That was so nice, eating lunch by the ocean. Thanks organizers! ☀️ 🌊 🍙
