### ISSUE TITLE
Burbank - July 11th, 2017

### ISSUE THREAD

**Issue by bradstemke** [jsla/lunch.js#64]
# Burbank
### @ Tender Greens
https://www.yelp.com/biz/tender-greens-burbank?osq=Tender+Greens

Championed By: Brad Stemke @bradstemke

**Comment by bradstemke** [comment]
Does anyone wanting to come have a preference on food type?

Was thinking maybe,

Tender Greens - salads
Mi Casitas - mexican
Santoros - sandwiches

**Comment by grandsyntax** [comment]
My coworker and I are interested. Tender greens is good, or really any of the above.

**Comment by bradstemke** [comment]
Great! Let's do Tender Greens this month!

**Comment by grandsyntax** [comment]
👍

**Comment by bradstemke** [comment]
Also, I look pretty similar to my photo here, and will just be outside at 12:30, feel free to PM me in our Slack channel.

**Comment by bradstemke** [comment]
Thanks for coming! Till next time
