### ISSUE TITLE
West Hollywood - July 11 @ 12:30

### ISSUE THREAD

**Issue by devwells** [jsla/lunch.js#65]
# West Hollywood 
### @ Dialog Cafe

https://www.yelp.com/biz/dialog-cafe-west-hollywood

Championed By: Devin Wells @devwells

**Comment by laras126** [comment]
Dialog Cafe! https://www.yelp.com/biz/dialog-cafe-west-hollywood

**Comment by devwells** [comment]
@laras126 Dialog looks good! I think that Bricks and Scones might be a bit too far. 

What do you think of Black Swan Cafe? - https://www.yelp.com/biz/black-swan-cafe-los-angeles-2?osq=Lunch
I've never been there, but it looks good on Yelp

**Comment by laras126** [comment]
I haven't been to Black Swan, but that looks great as well! I'm in for wherever.

**Comment by devwells** [comment]
@laras126 Let's do Dialog! I really want to try it :)

**Comment by laras126** [comment]
@devwells Sweet, see you there tomorrow! I'll post something on the Slack channel.

**Comment by davidguttman** [comment]
I'll be there!

**Comment by ashwell** [comment]
I hope lunch was tasty! Until next month may all your lunches be yummy!
