### ISSUE TITLE
Calling all Champions - August 1st 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#66]
## Hey `lunch.js` Champions!

The next first Tuesday of the month is **`August 1st`**
Please create new issues when you get the chance.

## Current Champions
If anyone is unable to champion let me know, or reach out to those that have attended your location to see if someone wants to step in.

Culver City / Playa Vista - @jarrettch
SF Valley - @anguspiv
Santa Monica - @etanlubeck 
DTLA - @davidkim310 
Burbank - @bradstemke 
West Hollywood - @devwells 
Thousand Oaks - @fhwrdh

## Locations with Champions Needed

None! Unless you want to start a new neighborhood lunch.js!

If you see a neighborhood not listed, it would be awesome if you would champion it! Just add a comment here to get started.

**Comment by fhwrdh** [comment]
Hi @ashwell, I'm interested in possibly championing a new neighborhood. There are a few of us out here in the Westlake Village / Thousand Oaks area that make the trip to js.la and there isn't a lunch.js near us. Can we set up a Conejo Valley lunch.js?

**Comment by ashwell** [comment]
@fhwrdh sounds great! I'll get you added as a contributor so you can get started with a Thousand Oaks lunch.js

**Comment by ashwell** [comment]
I hope all the lunch.js events were good today!

Until next month!
