### ISSUE TITLE
SF Valley - August 1st 2017 @ 12:30 PM

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#67]
# SF Valley
### @ [Hamptons 818](https://www.yelp.com/biz/hamptons-818-sherman-oaks)

Championed By: Angus @anguspiv

Because of the late notice, I went ahead and chose a place. Let me know if this works for everyone.

**Comment by remarks** [comment]
Sorry! I'm working in LA so I can't make the Valley lunches from now on.

**Comment by powernerd** [comment]
I'd like to drop in and meet some other developers. Open to all?

**Comment by sheelah** [comment]
Got a meeting during this :( Next time!

**Comment by anguspiv** [comment]
@powernerd Yea, its completely open to anyone. We'd be glad to have you.

**Comment by anguspiv** [comment]
Welp, seems like its just me and you @powernerd, I might bring a couple coworkers too. But it'll be fun to meet you!

**Comment by powernerd** [comment]
I'll be there! I invited a couple former coworkers, but I don't think they can make it today.

**Comment by anguspiv** [comment]
Hey @powernerd it was great seeing you. 

Everyone else, I've created the next event at #74 
Hope to see you there
