### ISSUE TITLE
Thousand Oaks - August 1st 2017 @ 12:30

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#68]
# Thousand Oaks
### @ [Finney's Crafthouse]( https://www.yelp.com/biz/finneys-crafthouse-westlake-village-2)
982 S Westlake Blvd
Westlake Village, CA 91361

Championed By: Franklin @fhwrdh

Let's try a lunch.js in the Conejo Valley! I have a few folks from my office in Westlake Village, but we'd love to meet up with others in the area. Open to suggestions on a location, but we will default to [Finney's Crafthouse]( https://www.yelp.com/biz/finneys-crafthouse-westlake-village-2) for this first instance.

----
As no other suggestions have been made, [Finney's Crafthouse]( https://www.yelp.com/biz/finneys-crafthouse-westlake-village-2) will be our location.

**Comment by ashwell** [comment]
@fhwrdh looks great! I would suggest adding a comment mentioning anyone you think my want to go so they get a github notification

**Comment by machikoyasuda** [comment]
805 <3 @cdransf @smeads  and the rest of the folks from 805developershub.com

**Comment by cdransf** [comment]
Looks good! I'm still out on paternity leave but I can try and make it in from Camarillo.

**Comment by fhwrdh** [comment]
Excellent! Adding @namini67 @Zhuochengyu @HuoShengdi and will probably grab a few others from our office.

**Comment by cdransf** [comment]
Hey all! I don't think I'll be able to make it to this one, but I'm pretty confident I can make the next and maybe drag along some coworkers as well.

**Comment by fhwrdh** [comment]
Can I get a rough head count for today? If there are enough to warrant it, I can reserve a table. @machikoyasud,  @smeads, anyone else going to make it?

**Comment by machikoyasuda** [comment]
@fhwrdh i'm going to the santa monica one!

**Comment by namini67** [comment]
@fhwrdh I will attend 🙋‍♀️

**Comment by HuoShengdi** [comment]
I'm in planning all day, don't think I can make it

**Comment by fhwrdh** [comment]
@machikoyasuda yes, should have realized you are down that way. Enjoy the Santa Monica event!

**Comment by fhwrdh** [comment]
Thanks to all who made it today. Looking forward to next month!

**Comment by ashwell** [comment]
Check out the next lunch at https://github.com/jsla/lunch.js/issues/78
