### ISSUE TITLE
Culver City x Playa Vista - August 1st, 2017 at 12:30pm

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#69]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @jarrettch

**Comment by jarrettch** [comment]
@toiye jaimemendozadev @seanwestfall @ayurkows @8bitDesigner y'all in? And any and everyone else is welcome as well!

**Comment by ashwell** [comment]
@jarrettch you forgot the @ for @jaimemendozadev

but now that I mentioned him he should get a notification

**Comment by jarrettch** [comment]
Ooops! Thanks for catching that! Sorry Jaime!

**Comment by jaimemendozadev** [comment]
LOL, I got it! Unless something comes up, I'm in! Is it still Phorage though?

**Comment by ayurkows** [comment]
I'll try to be there!

**Comment by seanwestfall** [comment]
I'll be there tomorrow, See you there @jarrettch, I'll try to remember the picture this time.

**Comment by jaimemendozadev** [comment]
Hey guys, I hate to do this at the last minute, but I'm just too swamped with work so I can't make it today. Maybe next time. Apologies.

**Comment by jarrettch** [comment]
All good @jaimemendozadev maybe next time! Missed ya!
