### ISSUE TITLE
Santa Monica - Tuesday, August 1st, 2017 

### ISSUE THREAD

**Issue by jcblw** [jsla/lunch.js#70]
### @ [Flower Child](https://foursquare.com/v/flower-child/575c6399498eb08777285693)

[1332 2nd St, Santa Monica, CA 90401](https://www.google.com/maps?daddr=34.01532287178361,-118.49747856141374)

Championed by: @jcblw

**Comment by jcblw** [comment]
Hello beautiful people, hope to see all your wonderful faces at lunchjs

@etanlubeck @ashwell @machikoyasuda @jadware  @gr2m @jdorfman @rouzbeh84 @kpearson @Basscord @jimthoburn @mnicole @dancingshell 

tag anyone I missed

**Comment by remarks** [comment]
👋 I can come if y'all have space for me 😄

**Comment by Basscord** [comment]
Count me in!

**Comment by itsjustmath** [comment]
Can I come, @jcblw?

**Comment by jcblw** [comment]
@itsjustmath of course

**Comment by gr2m** [comment]
I’m planning to come? Any recommendations for a  place to get some work done before / after lunch.js in Santa Monica?

**Comment by mnicole** [comment]
my team will be there! @gr2m i would recommend the santa monica library on 7th and santa monica blvd. they have a bunch of work stations upstairs.

**Comment by Basscord** [comment]
@gr2m I like Blankspaces over on 2nd street. $20 drop-in for 5 hours.
http://www.blankspaces.com/location/santa-monica/

**Comment by jcblw** [comment]
last day of voting!

**Comment by itsjustmath** [comment]
@jcblw [ 🕺  💃  🐔  👀 ](http://chachachicken.com/)

**Comment by ashwell** [comment]
Just had an all hands scheduled for tomorrow, not going to make it this month :(

I hope it's a good one!

**Comment by machikoyasuda** [comment]
@gr2m there's one of these in santa monica now w/ free wifi too: https://www.capitalone.com/local/losangeles-santamonica/

**Comment by machikoyasuda** [comment]
@cielzee come out to samo!

**Comment by dancingshell** [comment]
I too will be at the all hands meeting ✋ 😞 ✋

**Comment by jcblw** [comment]
See y'all today 🎉 🚴 🏖

**Comment by ricklesgibson** [comment]
I'm hoping to be out of the dentist on time so if I am I'll see you there.

**Comment by remarks** [comment]
Ahh I'll be a little late 😒

**Comment by remarks** [comment]
Looks like I didn't plan this well enough 😅 Enjoy lunch everybody!

**Comment by gr2m** [comment]
I’m hear inside by the window standing tables on my computer 👋

**Comment by jcblw** [comment]
Great seeing y'all today! 

![20582740_503512319993585_7901635975095255040_n](https://user-images.githubusercontent.com/578259/28849138-94206052-76ca-11e7-8863-d81abfa949b0.jpg)

**Comment by jimthoburn** [comment]
Here’s one more photo with us and our lunches. Nice smiles everybody!   : )

![lunch-js-flower-child](https://user-images.githubusercontent.com/926616/28952407-df596052-7885-11e7-8b59-66c5a2ccaefd.jpg)

**Comment by jcblw** [comment]
thanks @jimthoburn
