### ISSUE TITLE
Calling all Champions - September 5th 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#73]
## Hey lunch.js Champions!

The next first Tuesday of the month is September 5th
Please create new issues when you get the chance.

## Current Champions

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

Culver City / Playa Vista #76 - @jarrettch
Sherman Oaks  #74 - @anguspiv
Santa Monica - @etanlubeck
DTLA - @davidkim310
Burbank - @bradstemke
West Hollywood - #77 @laras126
Thousand Oaks - #78 @fhwrdh

## Locations with Champions Needed

None! Unless you want to start a new neighborhood lunch.js!

If you see a neighborhood not listed, it would be awesome if you would champion it! Just add a comment here to get started.

**Comment by anguspiv** [comment]
Since we have Burbank and Thousand Oaks, I will just narrow SF Valley to Sherman Oaks now

**Comment by ashwell** [comment]
Lunch champions, @jarrettch @etanlubeck @davidkim310 @bradstemke @devwells and @fhwrdh please create lunch event tickets at your earliest convenience so we can get voting started.

If you are no longer able to champion the event please let me know

**Comment by ashwell** [comment]
I hope lunch.js when great for everyone! If you are up to champion next month go ahead make the next lunch ticket at your leisure. If you aren't going to be able to champion next month go ahead and comment on #80 so we can get the word out.

Thanks to everyone for organizing!
