### ISSUE TITLE
Sherman Oaks - September 5th, 2017 @ 12:30pm

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#74]
# Sherman Oaks
### @ [Mendocino Farms](http://mendocinofarms.com/sherman-oaks/)  
14141 Ventura Blvd.  
Sherman Oaks, CA 91423

Championed By: Angus @anguspiv

Hey Everyone, 
Hope to see you come out to Sherman Oaks, and just a reminder, but this open to everyone to come by and talk shop. Looking forward to seeing everyone.

**Comment by sheelah** [comment]
I'll throw a couple out there:
- [Mendocino Farms](http://mendocinofarms.com/sherman-oaks/)
- [Blue Jam Cafe](http://www.blujamcafe.com/map-sherman-oaks/)

**Comment by powernerd** [comment]
Count me in
My vote: 
- [x] [Mendocino Farms](http://mendocinofarms.com/sherman-oaks/)

**Comment by sheelah** [comment]
Mendocino Farms sounds good to me 👍

**Comment by anguspiv** [comment]
Looks like we have a place for lunch. I'm looking forward to hanging with you guys,
and have a great weekend until then.

**Comment by anguspiv** [comment]
Hey everyone, I won't be able to make it, as something has come up at work today. Sorry I can't be there, but you guys have all the fun without me

**Comment by sheelah** [comment]
We missed you, @anguspiv!  Hopefully next time we all can make it.  Nice meeting you, @powernerd!

**Comment by anguspiv** [comment]
Hey Everyone, next event is Oct. 3rd. Hope to see yo there. Check it out at #81
