### ISSUE TITLE
Culver City x Playa Vista - September 5th, 2017 at 12:30pm

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#76]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: @jarrettch

**Comment by jarrettch** [comment]
@aroduribe @toiye @jaimemendozadev @seanwestfall @ayurkows @8bitDesigner @eveafeline @rouzbeh84 @johntran @JackieCabinet This is next week! Anyone in?

**Comment by rouzbeh84** [comment]
I'm down! think i got out of a work trip 👍

**Comment by jaimemendozadev** [comment]
Put me down for now. 👍 Hopefully I won't have to cancel last minute like last time.

**Comment by aroduribe** [comment]
I'll probably hang out with the Santa Monica crew at that same time :)

**Comment by jaimemendozadev** [comment]
Ratz. Can't make it cuz I've had car problems over the weekend and need to get it fixed. Bummer. Sorry guys.

**Comment by jarrettch** [comment]
Sorry to miss you @jaimemendozadev! I'm also out now, had a meeting moved due to the holiday yesterday to today at 1pm so I can't make it. But for anyone planning to go, still go!

Maybe we should consider changing days when there is a Monday holiday moving forward? @ashwell  @davidguttman

**Comment by seanwestfall** [comment]
@jarrettch Can't make it too today, I have some work to do. Next time!

**Comment by rouzbeh84** [comment]
so wait, is anybody going anymore haha?

cc: @aroduribe @ayurkows @8bitDesigner @eveafeline  @johntran @JackieCabinet

**Comment by jarrettch** [comment]
@rouzbeh84 I'm checking right now to see if i can either move this meeting or skip it all together, waiting on a response right now

**Comment by jarrettch** [comment]
I'm stuck with this meeting @rouzbeh84 sorry :(
