### ISSUE TITLE
Thousand Oaks - September 5th, 2017 @ 12:30pm

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#78]
# Thousand Oaks
### @ TBD

Championed By: Franklin @fhwrdh

Hi all,
Hope to see everyone interested from Thousand Oaks and nearby areas.

❤️  [Bollywood](https://www.yelp.com/biz/bollywood-indian-restaurant-westlake-village-3)

**Comment by Zhuochengyu** [comment]
+1 for Bollywood

**Comment by zeke** [comment]
Whoa hey cool I live near here! Would love to attend.

Thanks to @gr2m for pointing this out.

**Comment by jxv** [comment]
Bollywoooo!

**Comment by fhwrdh** [comment]
@zeke Excellent!
@jxv Are you going to join us Joe?

**Comment by jxv** [comment]
@fhwrdh I'm considering it. I'll let you know before Monday.

**Comment by cdransf** [comment]
Bollywood sounds good to me.

**Comment by hippee-lee** [comment]
Bollywood

**Comment by fhwrdh** [comment]
Sounds like we have a decision on location!

**Comment by ipnicholson** [comment]
I'll be there 🙌

**Comment by zeke** [comment]
Nice to meet you folks today.  Please let me know if you have any recommended spots for hacking. 
💻 🌴

**Comment by fhwrdh** [comment]
Was great meeting / seeing everyone today. Looking forward to next month!
