### ISSUE TITLE
Santa Monica September 5 12:30 

### ISSUE THREAD

**Issue by fierceblonde** [jsla/lunch.js#79]
# Santa Monica
### @ Tender Greens  
201 Arizona Ave
Santa Monica, CA 90401
https://www.yelp.com/biz/tender-greens-santa-monica?osq=tender+greens

Championed By:  fierceblonde

**Comment by jcblw** [comment]
@fierceblonde thanks for setting this months SAMO lunchjs

@ashwell @machikoyasuda @jadware @gr2m @jdorfman @rouzbeh84 @Basscord @jimthoburn @mnicole @dancingshell

Hope to see you all there ✌️😁

tag anyone I missed

**Comment by gr2m** [comment]
you bet :) @machikoyasuda @kpearson

**Comment by kyasui** [comment]
Have room for one more? @fierceblonde @jcblw

**Comment by jcblw** [comment]
of course @kyasui!

**Comment by machikoyasuda** [comment]
I can't make it today sadly - have fun y'all. Thank you so much @fierceblonde for organizing!

**Comment by jcblw** [comment]
damn next one @machikoyasuda

**Comment by seanwestfall** [comment]
@jcblw I think I mentioned I was going to come to this one with a friend/coworker of mine to you at drink.js last week, but it turned out that we can't come... -_- Sorry @jcblw ,  Next time!

**Comment by jcblw** [comment]
its cool @seanwestfall next time!

**Comment by jcblw** [comment]
Actually looking at my schedule and I have a meeting at 1 today 😤 so Im not going to make it. Can someone take pictures?

**Comment by kyasui** [comment]
Ah also, wont be able to make it. Next time!

**Comment by gr2m** [comment]
I'm here :) anybody else?

**Comment by fierceblonde** [comment]
yes we are here. my coworker wears grey shirt and red shorts

On Sep 5, 2017 12:36 PM, "Gregor Martynus" <notifications@github.com> wrote:

I'm here :) anybody else?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jsla/lunch.js/issues/79#issuecomment-327280292>, or mute
the thread

**Comment by gr2m** [comment]
Long lines :) are we staying here or are we leaving?

**Comment by fierceblonde** [comment]
yes we already ordered

**Comment by fierceblonde** [comment]
i meant yes to staying

**Comment by mnicole** [comment]
my team had a lunch event today and couldn't make it, but see you all next month!

**Comment by gr2m** [comment]
Where are you at?

**Comment by fierceblonde** [comment]
outside seating

**Comment by ashwell** [comment]
I just last min set up the Santa Monica event, let me know if you're in!

https://github.com/jsla/lunch.js/issues/86

**Comment by kpearson** [comment]
I'm in. 

— Kit

On Sat, Sep 30, 2017 at 3:32 PM Ryan Bogle

<
mailto:Ryan Bogle <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I just last min set up the Santa Monica event, let me know if you're in!

https://github.com/jsla/lunch.js/issues/86

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/jsla/lunch.js/issues/79#issuecomment-333340280
, or

**Comment by justincrich** [comment]
I'm in
