### ISSUE TITLE
SF Valley - September 6th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#8]
# SF Valley
### @ TBD

Championed By: You?
As the champion you can pick a place,
or be really cool and make a poll
use reaction emojis as votes
include yelp links, or don't, whatever

**Comment by machikoyasuda** [comment]
hi andrew @wingedearth - you & your coworkers could totally start up the sf valley lunch.js out there in calabasas! :)

**Comment by wingedearth** [comment]
Hi Machiko,

Nice to hear from you. What is this sf valley lunch.js of which you speak?

Andrew

**Comment by machikoyasuda** [comment]
Hi Andrew,

It's not very complicated - just eating weekday work lunch with friends from who go to (or want to go to) the js.la meetups. Choose a place to eat and @ashwell & I can invite other SFV js.la people to commune over food! 

Machiko

**Comment by wingedearth** [comment]
Hey Machiko,

I’ll totally look into setting this up some time. In the meantime, check out this awesome Hackathon:

https://www.meetup.com/OC-Virtual-Reality-Meetup/events/233005681/?platform=hootsuite <https://www.meetup.com/OC-Virtual-Reality-Meetup/events/233005681/?platform=hootsuite>

It’s Monster VR teaming up with Titmouse (the makers of Venture Bros. and Metalocalypse on Adult Swim). Very cool stuff. I’m psyched to go to this. If you’re interested in going, contact them asap.

Cheers,
Andrew

**Comment by ashwell** [comment]
October SF Valley lunch.js issue is open, https://github.com/jsla/lunch.js/issues/16

STILL LOOKING FOR A CHAMPION!

**Comment by wingedearth** [comment]
How about Sagebrush Cantina on Calabasas Road as a venue?
