### ISSUE TITLE
Sherman Oaks - Oct. 3rd, 2017

### ISSUE THREAD

**Issue by anguspiv** [jsla/lunch.js#81]
# Sherman Oaks
### @ [Blu Jam Cafe](https://www.yelp.com/biz/blu-jam-cafe-sherman-oaks-2)
15045 Ventura Blvd
Sherman Oaks, CA 91403

Championed By: Angus @anguspiv

Okay, its been set, we are going to [Blue Jam Cafe](https://www.yelp.com/biz/blu-jam-cafe-sherman-oaks-2)

**Comment by charlestseng** [comment]
I'm In

**Comment by sheelah** [comment]
Likewise.  A couple ideas:
- [Blu Jam Cafe](https://www.yelp.com/biz/blu-jam-cafe-sherman-oaks-2)
- [Garden Cafe](https://www.yelp.com/biz/garden-cafe-sherman-oaks)

**Comment by powernerd** [comment]
I'll be there 
 - [x] [Blu Jam Cafe](https://www.yelp.com/biz/blu-jam-cafe-sherman-oaks-2)
 - [ ] [Garden Cafe](https://www.yelp.com/biz/garden-cafe-sherman-oaks)

**Comment by anguspiv** [comment]
Lets do Blu Jam Cafe!

**Comment by anguspiv** [comment]
Thanks for coming out everyone! I'll see you next time

**Comment by anguspiv** [comment]
@charlestseng @sheelah @powernerd Hey Guys, I have a feeling I won't be able to make the Next Lunch.js, (I'll be flying back from a wedding) can one of you guys champion the next Lunch.js for Sherman Oaks? All you need to do is just create an issue, and update it with labels, and info

**Comment by sheelah** [comment]
@anguspiv [Done](https://github.com/jsla/lunch.js/issues/88)! Wasn't able to add labels or set an assignee, however 👎
