### ISSUE TITLE
Thousand Oaks - Oct. 3rd, 2017

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#82]
# Thousand Oaks
### @ [Sumo Sushi](https://www.yelp.com/biz/sumo-japanese-restaurant-newbury-park)
**1714 Newbury Rd
Newbury Park, CA 91320**

Championed By: Franklin @fhwrdh

Hi all,
Hope to see everyone interested from Thousand Oaks and nearby areas.

**Comment by ashwell** [comment]
@fhwrdh I know it is a little confusing but the emoji listed in the issue template are the ones that can be used as [GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) and we typically stick to those so people don't have to comment to vote, they can just add a reaction.

For reference, this is the list
```
:+1: thumbs up
:-1: thumbs down
:smile:
:tada:
:confused:
:heart:
```

**Comment by fhwrdh** [comment]
Thanks, @ashwell. I fixed them, though I still prefer the ones I originally had there :smile.

**Comment by hippee-lee** [comment]
Two ideas for Newbury Park if folks want to go there. 

1. https://www.yelp.com/biz/sumo-japanese-restaurant-newbury-park
2. Sharky's in Newbury Park

<img width="995" alt="screen shot 2017-09-19 at 10 55 54 am" src="https://user-images.githubusercontent.com/433692/30607261-3663be98-9d29-11e7-8e31-5bbff2889e93.png">

**Comment by fhwrdh** [comment]
Hi @hippee-lee. I think your Sumo and my Sumo are the same Sumo!

**Comment by hippee-lee** [comment]
Is that a vote? 😛

**Comment by fhwrdh** [comment]
That sounds like a vote to me 😄

**Comment by ipnicholson** [comment]
Would love to go, and like that this to Camarillo, but I'll be out of town  ¯\_😆_/¯

**Comment by ashwell** [comment]
@fhwrdh if you could update the main ticket comment with a set location before Monday that would be great! Thanks for being a lunch champion!

**Comment by zeke** [comment]
Not gonna make it out tomorrow after all. Reaction retracted. Have a nice lunch :)

**Comment by jxv** [comment]
Sorry. Won't be able to make this one.

**Comment by toddgeist** [comment]
I am coming and bringing one other person with me

**Comment by fhwrdh** [comment]
Was great to see everyone and meet some new people. Thanks everyone.
