### ISSUE TITLE
Culver City x Playa Vista - October 3rd, 2017 at 12:30pm

### ISSUE THREAD

**Issue by jarrettch** [jsla/lunch.js#83]
# Culver City x Playa Vista
### @  [Phorage](http://phoragela.com/)

3300 Overland Avenue, Los Angeles, CA 90034

Championed by: Sean - @seanwestfall

**Comment by aroduribe** [comment]
Any thoughts of starting a Lunch.js on the east side (thinking Silverlake)?

**Comment by jarrettch** [comment]
@aroduribe probably better to bring that up in #80 or maybe check with the folks that have been to the DTLA lunch.js

**Comment by aroduribe** [comment]
Who's the go to DTLA person?

**Comment by ashwell** [comment]
@aroduribe I know, @davidkim310, @malinatran, @matikin9, and  @LearningNerd have all championed previous DTLA events.

**Comment by seanwestfall** [comment]
@ashwell I can champions the Culver City Phorage for this month. Just can't do it indefinitely.

**Comment by jarrettch** [comment]
Thanks @seanwestfall for this month. Unfortunately my job voted to have our weekly engineering meeting every Tuesday at 1pm so obviously I can't make that. Carry the torch!

**Comment by seanwestfall** [comment]
As mentioned in the slack channel, I'll be there from 12:30 to 1:30 PM.
