### ISSUE TITLE
Santa Monica - October 3rd, 2017 

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#86]
# Santa Monica
### @ [M Street Kitchen](https://www.yelp.com/biz/m-street-kitchen-santa-monica-2)
**2000 Main St
Santa Monica, CA 90405**

Championed By: Ryan Bogle @ashwell
I might not be able to make it, if someone wants to pick this up that would be awesome.

If this is out of the way for people let me know

**Comment by christineywang** [comment]
I'm in!

**Comment by Basscord** [comment]
I’m there!

**Comment by mnicole** [comment]
i have a 1:30 meeting today so i can't make it :(

**Comment by derekmiranda** [comment]
I'll be coming!

**Comment by justincrich** [comment]
Hey for this lunch are we going to meet out front first or do we have a reservation? 

Justin

**Comment by derekmiranda** [comment]
Think I'm the first one here so I got a table for 4. I'm in the corner near the windows, wearing glasses and a white shark shirt

**Comment by ashwell** [comment]
Sorry I couldn't make it, hope everything went well!

If anyone is interested in being the champion for this location let me know and I'll tell you how to get started.

**Comment by ShrayBans** [comment]
Nice meeting you guys!

**Comment by ashwell** [comment]
Sorry I couldn't be there, hope it was a good one!

**Comment by ashwell** [comment]
Is anyone from the previous lunch events willing to champion SM lunch.js?
