### ISSUE TITLE
Calling all Champions - November 7th 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#87]
## Hey lunch.js Champions!

The next first Tuesday of the month is November 7th
Please create new issues when you get the chance.

### West Side
Culver City / Playa Vista - **looking for a champion**
Santa Monica - **looking for a champion**

### SF Valley
Sherman Oaks - @anguspiv
Thousand Oaks - @fhwrdh
Burbank - still happening @bradstemke?

## LA Proper
DTLA - **looking for champion?**
West Hollywood - **looking for champion**

## South Side
South Bay - @rouzbeh84 

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js comment here to get started!

**Comment by billbitt** [comment]
@ashwell I could champion an LA Proper lunch.  I'm in Silverlake, but could do West Hollywood or DTLA

**Comment by ashwell** [comment]
@billbitt sounds good, feel free to open an issue for either location.

**Comment by ashwell** [comment]
Totally last min but if you think your location is up for it lunch.js December would be next Tuesday! (the 5th)
