### ISSUE TITLE
Sherman Oaks - Nov 7th, 2017

### ISSUE THREAD

**Issue by sheelah** [jsla/lunch.js#88]
# Sherman Oaks
### @ [Garden Cafe](https://www.yelp.com/biz/garden-cafe-sherman-oaks)

Championed By: Sheelah @sheelah

**Comment by ashwell** [comment]
Hey@sheelah! Thanks for championing the event! I have added you as a contributor so once you accept the invite you should have the ability to add and remove labels.

**Comment by charlestseng** [comment]
Thanks @sheelah.   My vote is 1. Garden Cafe

**Comment by sheelah** [comment]
Sounds good to me @charlestseng!  I've updated the location above.

**Comment by sheelah** [comment]
@anguspiv @powernerd Anyone else planning on joining tomorrow, so we know how many to expect?

**Comment by powernerd** [comment]
Not me. I'll be headed to the Los Feliz lunch.js (since I am working from the east side of the city on Tuesdays). Have a great lunch and I'll see you guys around at the other js.la events.

**Comment by anguspiv** [comment]
Me and @charlestseng won't be making it either. Ha, kinda funny, well, we can do another one in Dec.!

**Comment by sheelah** [comment]
Sounds good @anguspiv.  No shortage of food options in the area - hah :)

**Comment by anguspiv** [comment]
Hey Guys, there is a new event setup #104
