### ISSUE TITLE
Thousand Oaks - Nov 7th, 2017

### ISSUE THREAD

**Issue by fhwrdh** [jsla/lunch.js#89]
# Thousand Oaks
###  [Urban Plates](https://www.yelp.com/biz/urban-plates-thousand-oaks)

Championed By: Franklin @fhwrdh

Hi all,
Hope to see everyone interested from Thousand Oaks and nearby areas.

**Comment by hippee-lee** [comment]
😄

**Comment by fhwrdh** [comment]
I'm going to break the 2-2 tie with a vote for Urban Plates. We can hit Mouthful next month!

**Comment by johnlonganecker** [comment]
I will be making an appearance as well!

**Comment by fhwrdh** [comment]
Excellent John! See you then and tomorrow night.

**Comment by gnarmedia** [comment]
Awesome, hope to make it!

**Comment by sdall2000** [comment]
Planning to go as well thanks.

**Comment by fhwrdh** [comment]
Thanks for coming out everyone! See you all next time.
