### ISSUE TITLE
West Hollywood - September 6th, 2016

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#9]
# West Hollywood
### Next lunch is Tuesday, September 6th, 2016 12:30 PM

Championed By: David Guttman @davidguttman 

Where will we eat?

❤️ : Shake Shack
🎉 : Kitchen 24
😆 : Guisados

**Comment by chgrp-hung** [comment]
shake shack

**Comment by mrsmuneton** [comment]
we talked about Kitchen 24 when we met up last time so thats an option.

Looking forward to getting together!

:sunny:

**Comment by davidguttman** [comment]
cc @temojin & @krainboltgreene

**Comment by maytaldahan** [comment]
First timer but can happily make either of those locations. I just have to move a meeting around.

**Comment by davidguttman** [comment]
Looks like [Kitchen 24](https://www.yelp.com/biz/kitchen24-west-hollywood-west-hollywood) is the winner! See you there tomorrow at 12:30pm!

8575 Santa Monica Blvd
West Hollywood, CA 90069

**Comment by temojin** [comment]
Sorry all just saw this today. Can't make it this time.

**Comment by davidguttman** [comment]
Arrived! We are just inside at the first table.

**Comment by maytaldahan** [comment]
Sorry I saw this too late as well. I hope to get to join next time.

**Comment by ashwell** [comment]
the next west hollywood lunch.js has been posted, https://github.com/jsla/lunch.js/issues/15
