### ISSUE TITLE
Santa Monica - Nov 7th, 2017

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#92]
# Santa Monica
### @ [M Street Kitchen](https://www.yelp.com/biz/m-street-kitchen-santa-monica-2)
**2000 Main St
Santa Monica, CA 90405**

Championed By: Ryan Bogle @ashwell

I'd love to get someone else championing this location, so if anyone is interested please let me know.

**Comment by ashwell** [comment]
Looks like we got one vote! I'll update

**Comment by machikoyasuda** [comment]
@ashwell see u tomorrow!

**Comment by jaimemendozadev** [comment]
@ashwell @machikoyasuda I'm in! See you guys there! 😄

**Comment by mmccall** [comment]
Late RSVP, but I'm always good for M Street, see you there!

**Comment by ashwell** [comment]
Just arrived! Out front, anyone sit down yet?

**Comment by ashwell** [comment]
Great lunch! 

this was the new framework I was talking about, https://github.com/fastify/fastify

**Comment by jaimemendozadev** [comment]
Thanks for the repo @ashwell! I enjoyed hearing everyone's take on work related problems and processes. 😄
