### ISSUE TITLE
Los Feliz - Nov 7th, 2017

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#93]
#LA Proper / East Side
### @  [HomeState - Los Feliz](https://goo.gl/maps/ZSGtMMsDTRp)

Championed By: Bill Bittner @billbitt

**Comment by powernerd** [comment]
I'm working from the Eagle Rock area Tuesdays so I'll join up with you for this one. HomeState looks like a good choice for me.

**Comment by grandsyntax** [comment]
I'm in Glendale on the Griffith Park side. Will definitely try and make it!

**Comment by billbitt** [comment]
see you all in a little bit!  I'll be wearing a blue sweater and white baseball cap
