### ISSUE TITLE
Los Feliz - Dec 5th, 2017

### ISSUE THREAD

**Issue by billbitt** [jsla/lunch.js#96]
Los Feliz - Dec 5th, 2017
# Los Feliz

**Comment by davidguttman** [comment]
I'll be there!

**Comment by powernerd** [comment]
Count me in.

**Comment by billbitt** [comment]
sorry @davidguttman looks like spitz is the winner.  next time will be alcove!

**Comment by powernerd** [comment]
Döner for me, weeee!

**Comment by billbitt** [comment]
see you all at 12:30 at Spitz!  
I'll be in a blue sweater and white baseball cap.
