### ISSUE TITLE
Last Minute December Lunch.js Anyone?

### ISSUE THREAD

**Issue by ashwell** [jsla/lunch.js#97]
## Hey lunch.js Champions!

**Sorry I didn't reach out sooner!**

The next first Tuesday of the month is December 5th
Please create a new issue if you think your location is up for it on such short notice!

## Lunch Locations
Los Feliz / West Hollywood - @billbitt #96 
Culver City
Playa Vista
Santa Monica - @mnicole #98 
Sherman Oaks - @anguspiv
Thousand Oaks - @fhwrdh
Burbank?
DTLA?
South Bay - @rouzbeh84 
Valencia / Santa Clarita

If anyone is unable to champion let me know or reach out to those that have attended your location to see if someone wants to step in.

If you want to start a new neighborhood lunch.js comment here to get started!

**Comment by mnicole** [comment]
just made one for SM :) #98
