### ISSUE TITLE
Santa Monica - December 5, 2017

### ISSUE THREAD

**Issue by mnicole** [jsla/lunch.js#98]
Next lunch is Tuesday, December 5, 2017 at 12:30 PM
@ [Tocaya](http://www.tocayaorganica.com/locations/#santamonica)
507 Wilshire Blvd, Santa Monica, CA 90401

Championed By: Michele @mnicole

Vote with the emoji's for your preferred location!

😄  800 Degrees
🎉  Tocaya
❤️  Cava

**Comment by JMSantos94** [comment]
I am in!

:party_parrot:

**Comment by ashwell** [comment]
Thanks @mnicole! I just sent you an invite to become a collaborator so you can edit labels and such.

**Comment by mherodev** [comment]
I've never been to one of these, is this how I RSVP? Did I just RSVP?!

**Comment by mnicole** [comment]
Haha yeah, there's no official RSVP, so you can just show up! Although it is nice to comment or vote to get a general idea of who is coming. I'll update the location soon, but looks like it will probably be Tocaya.

**Comment by machikoyasuda** [comment]
pinging @tinuola

**Comment by tinuola** [comment]
Thanks @machikoyasuda!

**Comment by mnicole** [comment]
hi all! looking forward to seeing you today. i'll be wearing black pants and a grey gumgum hoodie. my team will get there a bit early and try and grab a table. there's usually plenty of space.

**Comment by zeke** [comment]
@groundwater and I are visiting Los Angeles this week, and working out of the Santa Monica library today. We'd love to crash your lunch!

**Comment by mherodev** [comment]
Sorry I can't make it today! 2018 resolution to hit up a JS.LA lunch 💦

**Comment by JMSantos94** [comment]
We are here o/

**Comment by mnicole** [comment]
It was great to meet you all!

![img_8978](https://user-images.githubusercontent.com/3858380/33632688-43df885a-d9c3-11e7-8fd2-e7400d973e6e.JPG)

**Comment by groundwater** [comment]
👋  great to meet everyone!
